### ISSUE TITLE
Attempt to invoke virtual method 'java.util.Set java.util.HashMap.entrySet()' on a null object reference

### ISSUE THREAD

**Issue by smedic** [Instabug/Instabug-Android#100]
Sometimes, I get this crash and stacktrace refers to potential library issue. 
This may be related to my usage of the library, but I am not quite sure.

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.util.Set java.util.HashMap.entrySet()' on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set java.util.HashMap.entrySet()' on a null object reference
       at com.instabug.library.model.b.toJson(UserAttributes.java:50)
       at com.instabug.library.model.b.toString(UserAttributes.java:72)
       at java.lang.String.valueOf(String.java:2896)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at com.instabug.library.internal.storage.cache.CacheManager.migrateCache(CacheManager.java:269)
       at com.instabug.library.internal.storage.cache.UserAttributesCacheManager$2.run(UserAttributesCacheManager.java:57)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.instabug.library.util.threading.b$1.run(PriorityThreadFactory.java:28)
       at java.lang.Thread.run(Thread.java:764)

If you have any idea, please point me in the right direction.
Thanks!

**Comment by Korazy** [comment]
@smedic apologies for the delay, would you be able to have it set to 4.15.3 specifically and let me know if it works? :)

**Comment by smedic** [comment]
@Korazy 
I changed version to 4.15.3, as you suggested. 
This bug is not easy to reproduce, so I will keep eyes on it and let you know about outcome. 
Thanks!

**Comment by smedic** [comment]
@Korazy If we put 4+, it will use the latest library (4.15.3). I think that won't help in this case.

**Comment by smedic** [comment]
@Korazy Any news about this ? We are stuck with this error and getting more and more crash reports.

**Comment by Korazy** [comment]
@smedic apologies for the delay. Just to confirm, you have multidex enabled correct?

**Comment by smedic** [comment]
@Korazy Yes, I have multidex enabled in my app.

**Comment by Korazy** [comment]
@smedic this issue should be fixed as of version 8.0 (which was just released). Please try it out and feel free to reopen the issue in case you still receive the crash :)
