### ISSUE TITLE
Crash: OutOfMemoryError

### ISSUE THREAD

**Issue by AdamSantosCA** [Instabug/Instabug-Android#110]
We are seeing lots of app crashes in our Android app due to to OutOfMemoryErrors in Instabug. Most of the crashes seem to be in Android SDK 24 & 25. We are using Instabug version 4.15.3.

```
data:text/text;charset=utf-8,
java.lang.RuntimeException: An error occurred while executing doInBackground()
	 at android.os.AsyncTask$3.done(AsyncTask.java:318)
	 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	 at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	 at java.lang.Thread.run(Thread.java:762)

Caused by: 
java.lang.OutOfMemoryError: Failed to allocate a 37748744 byte allocation with 16773232 free bytes and 30MB until OOM
	 at java.util.Arrays.copyOf(Arrays.java:3352)
	 at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	 at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	 at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:606)
	 at java.lang.StringBuilder.append(StringBuilder.java:215)
	 at org.json.JSONStringer.string(JSONStringer.java:344)
	 at org.json.JSONStringer.key(JSONStringer.java:375)
	 at org.json.JSONObject.writeTo(JSONObject.java:720)
	 at org.json.JSONStringer.value(JSONStringer.java:237)
	 at org.json.JSONArray.writeTo(JSONArray.java:613)
	 at org.json.JSONStringer.value(JSONStringer.java:233)
	 at org.json.JSONObject.writeTo(JSONObject.java:720)
	 at org.json.JSONObject.toString(JSONObject.java:689)
	 at com.instabug.library.network.Request.getRequestBody(Request.java:237)
	 at com.instabug.library.network.NetworkManager$1.subscribe(NetworkManager.java:85)
	 at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	 at io.reactivex.Observable.subscribe(Observable.java:12025)
	 at com.instabug.library.analytics.network.a.a(AnalyticsService.java:58)
	 at com.instabug.library.analytics.network.InstabugAnalyticsUploaderService.a(InstabugAnalyticsUploaderService.java:46)
	 at com.instabug.library.analytics.network.InstabugAnalyticsUploaderService.runBackgroundTask(InstabugAnalyticsUploaderService.java:39)
	 at com.instabug.library.network.a.onHandleWork(InstabugBackgroundService.java:28)
	 at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
	 at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
	 at android.os.AsyncTask$2.call(AsyncTask.java:304)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	 at java.lang.Thread.run(Thread.java:762)
```

**Comment by AdamSantosCA** [comment]
We are currently testing a build with 8.0.2 for release later today. We were hoping it would fix the issue, but I didn't see any reference to this specific bug in your issues or release notes. Thanks for confirming it has been addressed. I'll let you know how it works.

**Comment by AdamSantosCA** [comment]
@Korazy We did a release earlier today and have seen two crashes due to this issue since then when using 8.0.2.

**Comment by AdamSantosCA** [comment]
One more bit of information. We are also using Crashlytics 4.9.4. It looks like every time we call Crashlytics.logException(), we get a corresponding OOM exception and crash in Instabug.

The app initially used Crashlytics for crash reporting and analytics, but then we added Instabug for user feedback. The two worked together previously until we recently upgraded both.

**Comment by Korazy** [comment]
Apologies for the delay in my response on hear. Rami, my colleague you reached out to on the support channel, and I will be following up to make sure this error is resolved.

**Comment by Korazy** [comment]
The fix should be included in the next release. Please feel free to reopen the issue if you still face it then :)
