### ISSUE TITLE
Out of memory bug

### ISSUE THREAD

**Issue by pstambrecht** [Instabug/Instabug-Android#111]
Here is a crash log of OOM error.
```
java.lang.OutOfMemoryError
	at java.lang.String.<init>(String.java:354)
	at java.lang.String.<init>(String.java:393)
	at okio.Buffer.readString(Buffer.java:631)
	at okio.Buffer.readString(Buffer.java:614)
	at com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.intercept(InstabugOkhttpInterceptor.java:150)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
```

**Comment by Korazy** [comment]
Hey @pstambrecht 

Thanks for reaching out! Are you on version 8.0.2 of the SDK? This error should be fixed there :)

**Comment by Korazy** [comment]
Please feel free to reopen the issue if it occurs again with you on the latest version :)
