### ISSUE TITLE
Xamarin.Android Launch NoClassDefFoundError Crash

### ISSUE THREAD

**Issue by kmjonmastro** [Instabug/Instabug-Android#112]
Hi, we are currently evaluating Instabug. We have followed the instructions for Xamarin.Android and we are getting the below error:

`{Java.Lang.ClassNotFoundException: Didn't find class "com.instabug.chat.R$drawable" on path: DexPathList[[zip file "/data/app/com.app.mobile.instabug-wWUN2X-gzHNcQQzojuJ9xg==/base.apk"],nativeLibraryDirectories=[/data/app/com.app.mobile.instabug-wWUN2X-gzHNcQQzojuJ9xg==/lib/x86, /data/app/com.app.mobile.instabug-wWUN2X-gzHNcQQzojuJ9xg==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
  --- End of managed Java.Lang.ClassNotFoundException stack trace ---
java.lang.ClassNotFoundException: Didn't find class "com.instabug.chat.R$drawable" on path: DexPathList[[zip file "/data/app/com.app.mobile.instabug-wWUN2X-gzHNcQQzojuJ9xg==/base.apk"],nativeLibraryDirectories=[/data/app/com.app.mobile.instabug-wWUN2X-gzHNcQQzojuJ9xg==/lib/x86, /data/app/com.app.mobile.instabug-wWUN2X-gzHNcQQzojuJ9xg==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.instabug.chat.ChatPluginWrapper.getTalkToUsOption(ChatPluginWrapper.java:72)
	at com.instabug.chat.ChatPluginWrapper.getPromptOptions(ChatPluginWrapper.java:63)
	at com.instabug.chat.ChatPlugin.getPromptOptions(ChatPlugin.java:48)
	at com.instabug.library.core.plugin.PluginsManager.getPluginsPromptOptions(PluginsManager.java:83)
	at com.instabug.library.invocation.InvocationManager.getAvailablePromptOptions(InvocationManager.java:312)
	at com.instabug.library.invocation.InvocationManager.isPromptOptionsAvailable(InvocationManager.java:396)
	at com.instabug.library.invocation.InvocationManager.listen(InvocationManager.java:181)
	at com.instabug.library.invocation.InvocationManager.access$200(InvocationManager.java:43)
	at com.instabug.library.invocation.InvocationManager$3.accept(InvocationManager.java:377)
	at com.instabug.library.invocation.InvocationManager$3.accept(InvocationManager.java:371)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:265)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:184)
	at com.instabug.library.core.eventbus.EventBus.post(EventBus.java:24)
	at com.instabug.library.tracking.InstabugInternalTrackingDelegate.handleActivityResumedEvent(InstabugInternalTrackingDelegate.java:108)
	at com.instabug.library.tracking.InstabugActivityLifecycleListener.onActivityResumed(InstabugActivityLifecycleListener.java:33)
	at android.app.Application.dispatchActivityResumed(Application.java:216)
	at android.app.Activity.onResume(Activity.java:1313)
	at mvvmcross.platforms.android.views.MvxSplashScreenActivity.n_onResume(Native Method)
	at mvvmcross.platforms.android.views.MvxSplashScreenActivity.onResume(MvxSplashScreenActivity.java:39)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
	at android.app.Activity.performResume(Activity.java:7117)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)`

Project Settings:
```
<TargetFrameworkVersion>v8.1</TargetFrameworkVersion>
<AndroidEnableMultiDex>true</AndroidEnableMultiDex>

nuget: Instabug-for-android version 8.0.0
```

**Comment by Korazy** [comment]
Hey @kmjonmastro 

Thanks for pointing this out, we will look into it and get back to you :)

**Comment by Korazy** [comment]
Hey @kmjonmastro 

Can you tell me when this error occurs? Would you be able to provide us with your Instabug code as well?

**Comment by kmjonmastro** [comment]
@Korazy this happens in MainApplication.OnCreate, after the 	```
var builder = new Instabug.Builder(this, "token_code");
			builder.SetInvocationEvents(InstabugInvocationEvent.Shake)
			  .Build();
```

**Comment by Korazy** [comment]
Thank you, we’re currently still working on finding a fix for the issue. Apologies for the delay.

**Comment by Korazy** [comment]
Would you be able to confirm if your integration code is in your App class and that you downloaded the instabug-for-android nuget package?

**Comment by ihassantariq** [comment]
@Korazy  I am facing the same issue. And I can confirm that I have tried it on Application class OnCreate() Method. But I am getting the same issue.

**Comment by ihassantariq** [comment]
Also, how could it be in the App class? This is android specific implementation. I have tried your implementation within the MainActivity OnCreate() method and in the Android Application OnCreate() method. Still seeing the same issue.

**Comment by ihassantariq** [comment]
I will update and let you know. Thanks for fixing it.

**Comment by rdiaa** [comment]
It's our pleasure to help you

**Comment by rdiaa** [comment]
@ihassantariq 

It's our pleasure to help you

**Comment by ihassantariq** [comment]
@rdiaa by the way you have done the same thing which I have proposed to your support team. Added a new nuget package? have you changed anything else?
