### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference ControlButton.java:47

### ISSUE THREAD

**Issue by dung90it** [Instabug/Instabug-Android#118]
java.lang.NullPointerException: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
	 at com.instabug.library.annotation.a.a(ControlButton.java:47)
	 at com.instabug.library.annotation.b.h.a(ZoomedShape.java:94)
	 at com.instabug.library.annotation.c.a(MarkUpDrawable.java:109)
	 at com.instabug.library.annotation.AnnotationView.onDraw(AnnotationView.java:322)
	 at android.view.View.draw(View.java:17469)
	 at android.view.View.draw(View.java:17381)
	 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	 at android.view.View.draw(View.java:17472)
	 at android.view.View.draw(View.java:17381)
	 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	 at android.view.View.draw(View.java:17379)
	 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	 at android.view.View.draw(View.java:17472)
	 at android.view.View.draw(View.java:17381)
	 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	 at android.view.View.draw(View.java:17472)
	 at android.view.View.draw(View.java:17381)
	 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	 at android.view.View.draw(View.java:17472)
	 at android.view.View.draw(View.java:17381)
	 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	 at android.view.View.draw(View.java:17379)
	 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	 at android.view.View.draw(View.java:17472)
	 at android.view.View.draw(View.java:17381)
	 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	 at android.view.View.draw(View.java:17379)
	 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	 at android.view.View.draw(View.java:17379)
	 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	 at android.view.View.draw(View.java:17379)
	 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	 at android.view.View.draw(View.java:17379)
	 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	 at android.view.View.draw(View.java:17472)
	 at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:3205)
	 at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:3258)
	 at android.view.ViewRootImpl.draw(ViewRootImpl.java:3162)
	 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2934)
	 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2523)
	 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1438)
	 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7398)
	 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
	 at android.view.Choreographer.doCallbacks(Choreographer.java:695)
	 at android.view.Choreographer.doFrame(Choreographer.java:631)
	 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	 at android.os.Handler.handleCallback(Handler.java:739)
	 at android.os.Handler.dispatchMessage(Handler.java:95)
	 at android.os.Looper.loop(Looper.java:158)
	 at android.app.ActivityThread.main(ActivityThread.java:7224)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Korazy** [comment]
Hey @dung90it 

Thanks for reaching out. Can you please let me know which SDK version this is on?

**Comment by dung90it** [comment]
This crash happens on instabug:8.0.3 with samsung SM-G900T

**Comment by Korazy** [comment]
@dung90it we're currently working on a fix for this. Will keep you updated regarding the progress of it.

**Comment by Korazy** [comment]
@dung90it would you be able to tell us the steps that led to this crash?

**Comment by Korazy** [comment]
This should now be fixed in the latest release.
