### ISSUE TITLE
 An error occurred while doing InstabugSessionUploaderService's required task DatabaseManager

### ISSUE THREAD

**Issue by MinaWadee** [Instabug/Instabug-Android#130]
Unable to init Instabug

### Instabug integration code

```
        Instabug bugSquad = new Instabug.Builder(this.getApplication(), "TOKEN")
                .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT)
                .build();

        bugSquad.setDebugEnabled(true);
```

### SDK Version
8.0.9
### Android Version
8.1.0
### Device Model
Huawei Nova 3i

### Error from Log
10-14 15:28:46.735 8172-8240/com.projs.app.proj E/INSTABUG - InstabugSessionUploaderService: An error occurred while doing InstabugSessionUploaderService's required task DatabaseManager is not initialized, call init(..) method first.
                                                                                                   java.lang.IllegalStateException: DatabaseManager is not initialized, call init(..) method first.
                                                                                                       at com.instabug.library.internal.storage.cache.db.DatabaseManager.getInstance(DatabaseManager.java:24)
                                                                                                       at com.instabug.library.internal.storage.cache.a.a(SessionDbHelper.java:62)
                                                                                                       at com.instabug.library.network.worker.uploader.InstabugSessionUploaderService.a(InstabugSessionUploaderService.java:41)
                                                                                                       at com.instabug.library.network.worker.uploader.InstabugSessionUploaderService.runBackgroundTask(InstabugSessionUploaderService.java:30)
                                                                                                       at com.instabug.library.network.a.onHandleWork(InstabugBackgroundService.java:28)
                                                                                                       at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
                                                                                                       at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
                                                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:345)
                                                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                       at java.lang.Thread.run(Thread.java:784)

**Comment by ramiimagdi** [comment]
Hey @MinaWadee, thank you for reaching out to us!

Please allow me some time to investigate this further with the team and get back to you as fast as possible.

**Comment by ramiimagdi** [comment]
Hello again @MinaWadee, 

After investigating the issue, it seems like the application gets terminated before Instabug even gets initialized, and that's a very weird behavior.

However, we have made this snapshot: `8.0.10.4-SNAPSHOT` that might be helpful in solving this problem. Also, please make sure your application is initialized in the application class.

**Comment by MinaWadee** [comment]
we have tried this 8.0.10.4-SNAPSHOT and still not working

**Comment by ramiimagdi** [comment]
Hey @mohkin and @MinaWadee,
My apologies for any inconvenience, I totally understand the urgency here.

I was wondering if you could share with us a sample application with the same scenario so that we can investigate it further, that would be really helpful.

**Comment by mohkin** [comment]
Hi @ramiimagdi,
Would an APK help you diagnose the issue?

**Comment by ramiimagdi** [comment]
Hi @mohkin, 
An APK will be fine to check whether the behavior is reproducible on all devices or not. However, we require a written code so that we can be able to troubleshoot the issue and get to know the root cause of it.

**Comment by ramiimagdi** [comment]
Hello again @mohkin, 
Have you had the chance to create a sample application? So that we can start troubleshooting the issue as fast as possible 😊

**Comment by mohkin** [comment]
Hi @ramiimagdi ,
We are working on a sample, we will try to get it ready by tomorrow morning

**Comment by ramiimagdi** [comment]
Hi @mohkin, have you had the chance to create the sample application? 
Thank you!

**Comment by julo15** [comment]
@ramiimagdi I'm seeing this as well. In my case, my app code is definitely failing somewhere early in our initialization code in javascript (which we will need to fix). However, if an app's code fails early on, how can we avoid Instabug crashing like this? Is there a promise or something we can wait on to know 'okay, Instabug is fully initialized and ready now'?

**Comment by donovancarthew** [comment]
We are experiencing the same issue. At some point is seems that the instabug internal storage becomes currupt, and from that point on the user cannot even open the app, it just keeps crashing with the following exception (captured from bugsnag)
DatabaseManager is not initialized, call init(..) method first.
DatabaseManager.java:24com.instabug.library.internal.storage.cache.db.DatabaseManager.getInstance
