### ISSUE TITLE
NullPointerException in SynchronizationManager at issue reporting

### ISSUE THREAD

**Issue by sfseyhan** [Instabug/Instabug-Android#135]
Instabug is crashing after issue is reported if it was disabled and enabled before. Crash doesn't happen if we never disable Instabug.

### Stacktrace
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
       at com.instabug.chat.synchronization.SynchronizationManager.sync(SynchronizationManager.java:81)
       at com.instabug.bug.e.j(LiveBugManager.java:191)
       at com.instabug.bug.e.c(LiveBugManager.java:47)
       at com.instabug.bug.e$1$1.run(LiveBugManager.java:183)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Steps to Reproduce the Problem
//Build instabug
new Instabug.Builder(getApplication(), BuildConfig.INSTABUG_TOKEN).build();
//Disable instabug
Instabug.disable();
//Enable instabug
Instabug.enable();

//Report issue causes crash after this point.

### Instabug integration code
```
//OnCreate of Application
new Instabug.Builder(this, BuildConfig.INSTABUG_TOKEN)
                        .setInvocationEvents(InstabugInvocationEvent.FLOATING_BUTTON, InstabugInvocationEvent.SCREENSHOT).build();
Instabug.disable();
```

```
//OnCreate of MainActivity
if (isInstabugFeatureEnabled() && !Instabug.isEnabled()) {
Instabug.enable();
}
// isInstabugFeatureEnabled() is where we determine if instabug will be enabled using firebase remote config
```

### SDK Version
8.0.11

### Android Version
Android 7-8-9

### Device Model
Google Pixel XL

**Comment by Korazy** [comment]
Hey @sfseyhan 

Thank you for reaching out and for providing all these details! We're looking into this now and will get you a fix as soon as possible.

**Comment by Korazy** [comment]
Hey @sfseyhan 

Would you be able to try this custom build and let me know if everything works out? **8.0.11.7-SNAPSHOT**

To grab a snapshot, please add the following as well:
```
repositories {
    maven {
        // TODO add this only if interested in getting SNAPSHOT releases
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by sfseyhan** [comment]
@Korazy app doesn't crash with the snapshot version, but even if we get a success message, the reports are not going through. Reported the issue here: https://github.com/Instabug/Instabug-Android/issues/137

**Comment by sfseyhan** [comment]
The other issue I linked seems to be irrelevant to this one and it was just lacking error handling in case the trial account has expired.

**Comment by Korazy** [comment]
I'm happy to hear that the crash for this issue is resolved now. I'll close this issue now so that we don't confuse the two tickets. I'll also be following up with @rdiaa regarding the other issue for you.

**Comment by jlmcdonnell** [comment]
I'm seeing this issue again in `8.7.2`

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
	 at com.instabug.chat.synchronization.SynchronizationManager.sync(SynchronizationManager.java:100)
	 at com.instabug.bug.e.j(LiveBugManager.java:195)
	 at com.instabug.bug.e.c(LiveBugManager.java:49)
	 at com.instabug.bug.e$1$2.run(LiveBugManager.java:187)
	 at android.os.Handler.handleCallback(Handler.java:873)
	 at android.os.Handler.dispatchMessage(Handler.java:99)
	 at android.os.Looper.loop(Looper.java:214)
	 at android.app.ActivityThread.main(ActivityThread.java:6986)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```
