### ISSUE TITLE
Nullpointer exception initializing BugReportFragment

### ISSUE THREAD

**Issue by SimonPSH** [Instabug/Instabug-Android#143]
We have noticed a new crash related to the initialization of the BugReportFragment.  This strictly from crash reporting and we do not have reproduction steps.

### Stack trace

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{bike.smarthalo.app/com.instabug.bug.view.BugReportingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.library.model.State com.instabug.bug.model.Bug.getState()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.library.model.State com.instabug.bug.model.Bug.getState()' on a null object reference
       at com.instabug.bug.view.c.initContentViews(BugReportingFragment.java:209)
       at com.instabug.library.core.ui.ToolbarFragment.initViews(ToolbarFragment.java:33)
       at com.instabug.library.core.ui.BaseFragment.onCreateView(BaseFragment.java:38)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
       at com.instabug.library.core.ui.BaseFragmentActivity.onStart(BaseFragmentActivity.java:51)
       at com.instabug.bug.view.BugReportingActivity.onStart(BugReportingActivity.java:91)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
       at android.app.Activity.performStart(Activity.java:7200)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2918)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

### Steps to Reproduce the Problem

Production crash, no steps to reproduce

### Expected Behavior

No crash

### Actual Behavior

Crash

### Instabug integration code

        new Instabug
                .Builder(this, "")
                .setCrashReportingState(Feature.State.DISABLED)
                .build();

        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);
        BugReporting.setInvocationEvents(InstabugInvocationEvent.SHAKE);
        Instabug.disable();

We disable Instabug on initialization as we only enable it once the user session has started.

### SDK Version

Instabug 8+

### Android Version

8.0.0

### Device Model

Samsung SM-G965W

**Comment by vezikon** [comment]
Hi @SimonPSH, `8.0.14.11-SNAPSHOT` should solve your issue. 

Please, don't forget to add this to your app-level build.gradle file in order to grab the snapshot. 

```
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by mzelzoghbi** [comment]
Hi @SimonPSH, I’m closing this issue because it has been inactive for a month.

Please reopen if you still encounter this issue with the latest version *8.0.16*

Thank you! :blush:
