### ISSUE TITLE
ConfigLoader Crash

### ISSUE THREAD

**Issue by MahmoudB** [Instabug/Instabug-Android#144]
### Steps to Reproduce the Problem

The issue happens while the device state is in Background.

### Instabug integration code

```
    public void build() {
        if (Instabug.isBuilt()) {
            return;
        }

        new Builder(mApplication, BuildConfig.INSTABUG_TOKEN)
                .setCrashReportingState(State.DISABLED)
                .setInAppMessagingState(State.ENABLED)
                .setPushNotificationState(State.ENABLED)
                .setSurveysState(State.ENABLED)
                .setViewHierarchyState(State.DISABLED)
                .build();

        BugReporting.setAttachmentTypesEnabled(true, false, false, false);
        // Don't send user email to instabug (privacy policy)
        BugReporting.setInvocationOptions(InvocationOption.EMAIL_FIELD_HIDDEN);
        FeatureRequests.setEmailFieldRequired(false);
        BugReporting.setInvocationOptions(InvocationOption.COMMENT_FIELD_REQUIRED);
        BugReporting.setShakingThreshold(750);
        Instabug.setNotificationIcon(R.drawable.ic_notification_papillon);
        BugReporting.setOnInvokeCallback(this::onInstabugDisplayed);
        Instabug.onReportSubmitHandler(it -> onInstabugSent());
    }
```
### SDK Version
8.0.11
### Android Version
This bug happens mainly on **Android 6** `93%` but can happen also on **Android 5** and **Android 8**.

### Full Stack Trace

```
Caused by java.util.ConcurrentModificationException
       at java.util.Hashtable$HashIterator.nextEntry(Hashtable.java:727)
       at java.util.Hashtable$EntryIterator.next(Hashtable.java:778)
       at java.util.Hashtable$EntryIterator.next(Hashtable.java:778)
       at org.jacoco.agent.rt.internal_8ff85ea.ConfigLoader.loadSystemProperties(SourceFile:56)
       at org.jacoco.agent.rt.internal_8ff85ea.ConfigLoader.load(SourceFile:37)
       at org.jacoco.agent.rt.internal_8ff85ea.Offline.(SourceFile:29)
       at com.instabug.library.Instabug.$jacocoInit(SourceFile)
       at com.instabug.library.Instabug.(SourceFile)
```

**Comment by mzelzoghbi** [comment]
Hey @MahmoudB, please feel free to reopen this thread again if you need further assistance on this issue, we'd love to help you out!

Thank you 😊
