### ISSUE TITLE
java.lang.NullPointerException · uri

### ISSUE THREAD

**Issue by svalsan-lyft** [Instabug/Instabug-Android#149]
### Steps to Reproduce the Problem
NA
### Expected Behavior
Should not crash
### Actual Behavior
NA
### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
instabug version 8.0.2
### Android Version
6.0.1, level 23
### Device Model
WindsongAOB
### [Optional] Project That Reproduces the Issue

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69398, result=-1, data=Intent { (has extras) }} to activity {xxx.xxx.xxx/com.instabug.bug.view.BugReportingActivity}: java.lang.NullPointerException: uri
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
        at android.app.ActivityThread.-wrap16(ActivityThread.java:-1)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: uri
        at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:60)
        at android.content.ContentResolver.query(ContentResolver.java:474)
        at android.content.ContentResolver.query(ContentResolver.java:434)
        at android.app.Activity.managedQuery(Activity.java:2007)
        at com.instabug.library.internal.storage.AttachmentsUtility.getGalleryImagePath(SourceFile:61)
        at com.instabug.bug.view.e.a(SourceFile:207)
        at com.instabug.bug.view.c.onActivityResult(SourceFile:516)
        at android.support.v4.app.FragmentActivity.onActivityResult(SourceFile:160)
        at android.app.Activity.dispatchActivityResult(Activity.java:6456)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)

**Comment by hanaamohamed** [comment]
Hello Svalsan, 
You can use this snapshot `    implementation 'com.instabug.library:instabug:8.0.14.28-SNAPSHOT'
`
this would fix your issue, and let me know if there's anything else

**Comment by MCeley** [comment]
@svalsan-lyft What device is WindsongAOB? I'm seeing a similar device name reporting from my ADT-1, but I also see the device reporting correctly as the ADT-1.

**Comment by lassana** [comment]
Hi there!
Does anyone know what `WindsongAOB` is?

**Comment by pouyactm** [comment]
Does anyone know what WindsongAOB is?

**Comment by pamelaschuldiner** [comment]
Same here! What is that? 

java.lang.RuntimeException: Unable to start service com.instabug.chat.network.InstabugMessageUploaderService@9a066a6 with Intent { cmp=com.principal.dx.cuprumapp/com.instabug.chat.network.InstabugMessageUploaderService }: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@8f08801 rejected from java.util.concurrent.ThreadPoolExecutor@f5c77d2[Running, pool size = 3, active threads = 3, queued tasks = 128, completed tasks = 70]

Device And OS: unknown WindsongAOB, OS Level 23 
Locale: zh 
Screen Size: 720x1280 
Density: mdpi 
Location: N/A, United States 
App Version: 1.0.6440 (6436) 
Duration: 00:03:24 
Tags:

**Comment by pamelaschuldiner** [comment]
Same here! What is that?

java.lang.RuntimeException: Unable to start service com.instabug.chat.network.InstabugMessageUploaderService@9a066a6 with Intent { cmp=com.example/com.instabug.chat.network.InstabugMessageUploaderService }: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@8f08801 rejected from java.util.concurrent.ThreadPoolExecutor@f5c77d2[Running, pool size = 3, active threads = 3, queued tasks = 128, completed tasks = 70]

Device And OS: unknown WindsongAOB, OS Level 23
Locale: zh
Screen Size: 720x1280
Density: mdpi
Location: N/A, United States
App Version: 1.0.6440 (6436)
Duration: 00:03:24
Tags:

**Comment by doerstechenterprise** [comment]
WindSongAOB Is a Bot Device owned by Google playstore Review Team .

**Comment by hanaamohamed** [comment]
Hello @pamelaschuldiner, This is a different issue, you can use our latest version 8.4.0 and if you still facing it, feel free to open an issue with it.
@svalsan-lyft I'm closing this issue, feel free to reopen it if you still facing it.
