### ISSUE TITLE
Crash on 8.0.14

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#150]
Getting crash reports from clients:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.instabug.bug.model.Bug.e()' on a null object reference
       at com.instabug.bug.view.c.a(SourceFile:1002)
       at com.instabug.bug.view.c.a(SourceFile:93)
       at com.instabug.bug.view.c$6$1.run(SourceFile:962)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by eygraber** [comment]
Just had this happen on 8.0.14 while recording screen:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.instabug.bug.model.Bug.e()' on a null object reference
        at com.instabug.bug.view.BugReportingActivity.d(BugReportingActivity.java:314)
        at com.instabug.bug.view.f.a(BugReportingPresenter.java:38)
        at com.instabug.bug.view.BugReportingActivity.onCreate(BugReportingActivity.java:112)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6680) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by vezikon** [comment]
Hi @eygraber, Thank you for reporting this. We will look into it and provide you with a solution really soon.

**Comment by vezikon** [comment]
Hi @eygraber, `8.0.14.11-SNAPSHOT` should solve your issue. 

Please, don't forget to add this to your app-level build.gradle file in order to grab the snapshot. 

```
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by mzelzoghbi** [comment]
Hi @eygraber, I’m closing this issue because it has been inactive for a month. Please reopen if you still encounter this issue with the latest version **8.0.19** Thank you! :blush:
