### ISSUE TITLE
Noticing a lot of crashes

### ISSUE THREAD

**Issue by alexsullivan114** [Instabug/Instabug-Android#152]
### Steps to Reproduce the Problem

Nothing specific, since the crashes happen randomly

### Expected Behavior

No crashes

### Actual Behavior

A non trivial number of crashes

### Instabug integration code
```
    Instabug.Builder(application, BuildConfig.INSTANT_BUG_KEY)
      .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT)
      .build()
    BugReporting.setPromptOptionsEnabled(BUG)
```
...

`myOkHttpClient.addInterceptor(InstabugOkhttpInterceptor())`

...

```
  override fun dispatchTouchEvent(ev: MotionEvent?): Boolean {
    InstabugTrackingDelegate.notifyActivityGotTouchEvent(ev, this)
    return super.dispatchTouchEvent(ev)
  }
```

^ In my `BaseActivity`

### SDK Version

Multiple versions, currently seeing a crash on `8.0.13`

### Android Version

Android Pie

### Device Model

Pixel 2 XL

A little more information:

I'm noticing a lot of crashes in my app that are originating from the Instabug library. The majority of my apps crashes over the course of its lifetime have come from the `BugReportingFragment` class, though those crashes seem to have stopped since I updated to `8.0.13`. I am, however, now seeing a crash coming from the `AnnotationView` class. I've also seen crashes, again from older versions of the library, from the `ViewUtils` class and the `MicUtils` class.

I'm wondering if I'm integrating the library wrong somehow. The initial initialization code happens in my custom application class's `onCreate` method. The network interceptor code runs when building a single global `okHttp` instance.

Any help would be much appreciated!

**Comment by vezikon** [comment]
Hi @alexsullivan114, 

Does your app have multiple processes or a foreground service?

**Comment by alexsullivan114** [comment]
Nope.

**Comment by vezikon** [comment]
Can you share with me the crashes coming from `BugReportingFragment` and `AnnotationView`?

**Comment by alexsullivan114** [comment]
@vezikon I'm sorry I don't know how I missed this. This is the latest crash I'm seeing in production in`BugReportingFragment`:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.library.model.State com.instabug.bug.model.Bug.getState()' on a null object reference
       at com.instabug.bug.view.c.initViews(BugReportingFragment.java:259)
       at com.instabug.library.core.ui.BaseFragment.onCreateView(BaseFragment.java:38)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
       at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at com.instabug.library.core.ui.BaseFragmentActivity.onStart(BaseFragmentActivity.java:50)
       at com.instabug.bug.view.BugReportingActivity.onStart(BugReportingActivity.java:123)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
       at android.app.Activity.performStart(Activity.java:7165)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2938)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```.

This is an (old) annotation view crash. We don't seem to be seeing it anymore though:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.instabug.library.annotation.d.a()' on a null object reference
       at com.instabug.library.annotation.AnnotationView.getScaledDrawables(AnnotationView.java:150)
       at com.instabug.library.annotation.AnnotationView.onSizeChanged(AnnotationView.java:143)
       at android.view.View.sizeChange(View.java:20848)
       at android.view.View.setFrame(View.java:20809)
       at android.widget.ImageView.setFrame(ImageView.java:1201)
       at android.view.View.setLeftTopRightBottom(View.java:20844)
       at android.transition.ChangeBounds$ViewBounds.setLeftTopRightBottom(ChangeBounds.java:502)
       at android.transition.ChangeBounds$ViewBounds.setBottomRight(ChangeBounds.java:497)
       at android.transition.ChangeBounds$3.set(ChangeBounds.java:102)
       at android.transition.ChangeBounds$3.set(ChangeBounds.java:99)
       at android.animation.PropertyValuesHolder.setAnimatedValue(PropertyValuesHolder.java:962)
       at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:990)
       at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1339)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1471)
       at android.animation.ValueAnimator.pulseAnimationFrame(ValueAnimator.java:1490)
       at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1163)
       at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1054)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:693)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

This was a large crash we saw in an earlier version:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.library.model.State com.instabug.bug.model.Bug.getState()' on a null object reference
       at com.instabug.bug.view.c.initViews(BugReportingFragment.java:258)
       at com.instabug.library.core.ui.BaseFragment.onCreateView(BaseFragment.java:38)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at com.instabug.library.core.ui.BaseFragmentActivity.onStart(BaseFragmentActivity.java:50)
       at com.instabug.bug.view.BugReportingActivity.onStart(BugReportingActivity.java:123)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
       at android.app.Activity.performStart(Activity.java:7165)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2938)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

There's several more but hopefully that gets the point across.

**Comment by vezikon** [comment]
@alexsullivan114 does your app use an alarm manager or push notifications?

**Comment by alexsullivan114** [comment]
@vezikon No neither.

**Comment by vezikon** [comment]
@alexsullivan114 Thank you, the annotation view crash was fixed in recent versions. The other crash we are on them. I'll provide you a fix for you really soon.

**Comment by mzelzoghbi** [comment]
Hi @alexsullivan114, I’m closing this issue because of inactivity. Please reopen if you still encounter this issue with the latest version 8.0.19 Thank you! 😊
