### ISSUE TITLE
Crash: SecurityException in Android O

### ISSUE THREAD

**Issue by sembozdemir** [Instabug/Instabug-Android#161]
We see a crash in Android O devices in our Crashlytics reports. Please see the stacktrace.
```
Caused by java.lang.SecurityException: Caller no longer running, last stopped +8s350ms because: timed out while starting
       at android.os.Parcel.readException(Parcel.java:1967)
       at android.os.Parcel.readException(Parcel.java:1913)
       at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:191)
       at android.app.job.JobParameters.dequeueWork(JobParameters.java:196)
       at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
       at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

When I investigate this issue, I found [this one](https://issuetracker.google.com/issues/63622293) in Google Issue Tracker. There is something wrong with `JobIntentService` in Android O. I tried to find a workaround this. There is a workaround in OneSignal SDK. They have own `JobIntentService` implementation. Please see this workaround [here](https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/JobIntentService.java#L342).
I think you should apply the same workaround. Unfortunately, we decided to remove InstaBug SDK from our application until this issue is fixed because of this crash.

### Steps to Reproduce the Problem
It comes from crash reports we could not determine steps to reproduce

### Expected Behavior
App should not crash

### Actual Behavior
App crashes

### Instabug integration code
    Instabug.Builder(this,
            if (!AppUtil.isProductionBuild()) INSTABUG_DEBUG_TOKEN else INSTABUG_PROD_TOKEN)
            .setInvocationEvent(InstabugInvocationEvent.SHAKE)
            .build()

### SDK Version
8.0.11

### Android Version
Android O

**Comment by mzelzoghbi** [comment]
Hey @sembozdemir 

Thanks for reporting this, you can use this snapshot 
```
implementation 'com.instabug.library:instabug:8.0.14.14-SNAPSHOT'
```

And don't forget to add this to your app `build.gradle` before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
    ...
}

```
Please let me know if everything works out.

**Comment by mzelzoghbi** [comment]
Hi @SimonPSH, I’m closing this issue because it has been fixed and released. Please reopen if you still encounter this issue with the latest version 8.0.19 Thank you! 😊

**Comment by WangDingchun** [comment]
it also crash on version 8.3.1

**Comment by WangDingchun** [comment]
@mzelzoghbi

**Comment by eygraber** [comment]
I'm seeing this on Instabug version 9.0.5.

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:353)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
Caused by java.lang.SecurityException: Caller no longer running, last stopped +829ms because: timed out while starting
       at android.os.Parcel.readException(Parcel.java:1951)
       at android.os.Parcel.readException(Parcel.java:1897)
       at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:191)
       at android.app.job.JobParameters.dequeueWork(JobParameters.java:196)
       at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:315)
       at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:640)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:390)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

Device
Brand: motorola
Model: moto e5 play
Orientation: Portrait
RAM free: 421.88 MB
Disk free: 580.47 MB
Operating System
Version: 8.0.0
Orientation: Portrait
Rooted: No
Crash
Date: Mar 25, 2020, 10:02:00 AM
App version: 3.0.0.42 (673)

```

**Comment by mzelzoghbi** [comment]
@eygraber I am not sure if it is Instabug Related or not as I can't see our package name in this stack trace.
This issue is an androidx framework related and there is already some open ticket in [google issue tracker](https://issuetracker.google.com/issues?q=SecurityException:%20Caller%20no%20longer%20running) 
However we added more defensive code in our latest release to avoid this crash.
Can you try **9.1.0** and let us know if it fixed the issue.?

Thank You

**Comment by eygraber** [comment]
It looks to me like [you wrote a blog post about this issue occurring in Instabug ¯\_(ツ)_/¯] (https://medium.com/@eng.zak/workaround-to-solve-securityexception-caused-by-jobintentservice-1f4b0e688a26).

In any case, I updated to 9.1.0 and we'll see if that helps, although this crash has only happened once out of 100s of thousands of sessions so not sure how to validate that it got fixed.
