### ISSUE TITLE
InstaBug Onboarding App Launch - Resources not found

### ISSUE THREAD

**Issue by paixols** [Instabug/Instabug-Android#165]
### Steps to Reproduce the Problem
> When initializing InstaBug application crashes with LOGS: 

```
android.content.res.Resources$NotFoundException: Resource ID #0x7f080107
--
1 | at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:215)
2 | at android.content.res.Resources.getValue(Resources.java:1316)
3 | at android.support.v7.widget.AppCompatDrawableManager.createDrawableIfNeeded(AppCompatDrawableManager.java:235)
4 | at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
5 | at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
6 | at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
7 | at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:86)
8 | at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:94)
9 | at com.instabug.library.ui.onboarding.d.initViews(OnboardingPagerFragment.java:76)
10 | at com.instabug.library.core.ui.BaseFragment.onCreateView(BaseFragment.java:38)
11 | at android.support.v4.app.Fragment.performCreateView(Fragment.java:2442)
12 | at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
13 | at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
14 | at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
15 | at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
16 | at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
17 | at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
18 | at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
19 | at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
20 | at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
21 | at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:146)
22 | at android.support.v4.view.ViewPager.populate(ViewPager.java:1244)
23 | at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
24 | at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
25 | at com.instabug.library.ui.custom.InstabugViewPager.onMeasure(InstabugViewPager.java:80)
26 | at android.view.View.measure(View.java:22071)
27 | at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
28 | at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
29 | at android.view.View.measure(View.java:22071)
30 | at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
31 | at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
32 | at android.view.View.measure(View.java:22071)
33 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
34 | at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
35 | at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
36 | at android.view.View.measure(View.java:22071)
37 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
38 | at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
39 | at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
40 | at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
41 | at android.view.View.measure(View.java:22071)
42 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
43 | at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
44 | at android.view.View.measure(View.java:22071)
45 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
46 | at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
47 | at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
48 | at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
49 | at android.view.View.measure(View.java:22071)
50 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
51 | at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
52 | at com.android.internal.policy.DecorView.onMeasure(DecorView.java:724)
53 | at android.view.View.measure(View.java:22071)
54 | at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2422)
55 | at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1504)
56 | at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
57 | at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
58 | at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
59 | at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
60 | at android.view.Choreographer.doCallbacks(Choreographer.java:723)
61 | at android.view.Choreographer.doFrame(Choreographer.java:658)
62 | at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
63 | at android.os.Handler.handleCallback(Handler.java:790)
64 | at android.os.Handler.dispatchMessage(Handler.java:99)
65 | at android.os.Looper.loop(Looper.java:164)
66 | at android.app.ActivityThread.main(ActivityThread.java:6494)
67 | at java.lang.reflect.Method.invoke(Native Method)
68 | at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
69 | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

### Expected Behavior
Show onboarding shaking image on application launch.

### Actual Behavior
Application crashes due to default Instabug integration

### Instabug integration code
```
Instabug.Builder(this, <key>)
                .setInvocationEvents(InstabugInvocationEvent.SHAKE)
                .build()
```

### SDK Version
> Instabug Version in Gradle ```8+```
### Android Version
> Android 8.1.0
### Device Model
> Google Pixel XL

### Questions
How can I disable the InstaBug onboarding process?

**Comment by mzelzoghbi** [comment]
Hi @paixols 
Thanks for reporting this issue. We tried to reproduce this issue but we couldn't. Could you send a sample app with the issue, please? It will help us to fix the issue quickly.

For you question about disabling onboarding you can use this API 
```
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);
```

**Comment by paixols** [comment]
Hi @mzelzoghbi 
I have been receiving this issue on my analytics. It looks like it's only happening on Google Pixel XL phones. I will post more information if this happens on more devices. 

I will try to reproduce it locally on other devices so I can share a sample app.

**Comment by mzelzoghbi** [comment]
Hi @paixols, I’m closing this issue because it has been inactive for a month. Please reopen if you still encounter this issue with the latest version 8.2.2 Thank you! 😊

**Comment by mykhailo-gaidai** [comment]
@mzelzoghbi although I'm not the OP, I'm having multiple occurrences of this issue on 8.2.2 and 8.3.0 over the last couple of weeks

**Comment by rdrobinson3** [comment]
We are seeing this as well in 8.5.0. It is actually our top crash now. In our case the both users were on a Nexus 6 running Android 7.1.1. 

`Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x7f0800ba
       at android.content.res.ResourcesImpl.getValue + 190(ResourcesImpl.java:190)
       at android.content.res.Resources.getValue + 1290(Resources.java:1290)
       at android.support.v7.widget.AppCompatDrawableManager.createDrawableIfNeeded + 235(AppCompatDrawableManager.java:235)
       at android.support.v7.widget.AppCompatDrawableManager.getDrawable + 200(AppCompatDrawableManager.java:200)
       at android.support.v7.widget.AppCompatDrawableManager.getDrawable + 191(AppCompatDrawableManager.java:191)
       at android.support.v7.content.res.AppCompatResources.getDrawable + 102(AppCompatResources.java:102)
       at android.support.v7.widget.AppCompatImageHelper.setImageResource + 86(AppCompatImageHelper.java:86)
       at android.support.v7.widget.AppCompatImageView.setImageResource + 94(AppCompatImageView.java:94)
       at com.instabug.library.ui.onboarding.d.initViews + 74(d.java:74)
       at com.instabug.library.core.ui.InstabugBaseFragment.onCreateView + 38(InstabugBaseFragment.java:38)
       at android.support.v4.app.Fragment.performCreateView + 2439(Fragment.java:2439)
       at android.support.v4.app.FragmentManagerImpl.moveToState + 1460(FragmentManagerImpl.java:1460)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState + 1784(FragmentManagerImpl.java:1784)
       at android.support.v4.app.FragmentManagerImpl.moveToState + 1852(FragmentManagerImpl.java:1852)
       at android.support.v4.app.BackStackRecord.executeOps + 802(BackStackRecord.java:802)
       at android.support.v4.app.FragmentManagerImpl.executeOps + 2625(FragmentManagerImpl.java:2625)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether + 2411(FragmentManagerImpl.java:2411)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute + 2366(FragmentManagerImpl.java:2366)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction + 2243(FragmentManagerImpl.java:2243)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss + 654(BackStackRecord.java:654)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate + 146(FragmentPagerAdapter.java:146)
       at android.support.v4.view.ViewPager.populate + 1244(ViewPager.java:1244)
       at android.support.v4.view.ViewPager.populate + 1092(ViewPager.java:1092)
       at android.support.v4.view.ViewPager.onMeasure + 1622(ViewPager.java:1622)
       at com.instabug.library.ui.custom.InstabugViewPager.onMeasure + 80(InstabugViewPager.java:80)
       at android.view.View.measure + 19857(View.java:19857)
       at android.widget.RelativeLayout.measureChildHorizontal + 715(RelativeLayout.java:715)
       at android.widget.RelativeLayout.onMeasure + 461(RelativeLayout.java:461)
       at android.view.View.measure + 19857(View.java:19857)
       at android.widget.RelativeLayout.measureChildHorizontal + 715(RelativeLayout.java:715)
       at android.widget.RelativeLayout.onMeasure + 461(RelativeLayout.java:461)
       at android.view.View.measure + 19857(View.java:19857)
       at android.view.ViewGroup.measureChildWithMargins + 6083(ViewGroup.java:6083)
       at android.widget.FrameLayout.onMeasure + 185(FrameLayout.java:185)
       at android.support.v7.widget.ContentFrameLayout.onMeasure + 143(ContentFrameLayout.java:143)
       at android.view.View.measure + 19857(View.java:19857)
       at android.view.ViewGroup.measureChildWithMargins + 6083(ViewGroup.java:6083)
       at android.widget.LinearLayout.measureChildBeforeLayout + 1464(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical + 758(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure + 640(LinearLayout.java:640)
       at android.view.View.measure + 19857(View.java:19857)
       at android.view.ViewGroup.measureChildWithMargins + 6083(ViewGroup.java:6083)
       at android.widget.FrameLayout.onMeasure + 185(FrameLayout.java:185)
       at android.view.View.measure + 19857(View.java:19857)
       at android.view.ViewGroup.measureChildWithMargins + 6083(ViewGroup.java:6083)
       at android.widget.LinearLayout.measureChildBeforeLayout + 1464(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical + 758(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure + 640(LinearLayout.java:640)
       at android.view.View.measure + 19857(View.java:19857)
       at android.view.ViewGroup.measureChildWithMargins + 6083(ViewGroup.java:6083)
       at android.widget.FrameLayout.onMeasure + 185(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure + 689(DecorView.java:689)
       at android.view.View.measure + 19857(View.java:19857)
       at android.view.ViewRootImpl.performMeasure + 2275(ViewRootImpl.java:2275)
       at android.view.ViewRootImpl.measureHierarchy + 1366(ViewRootImpl.java:1366)
       at android.view.ViewRootImpl.performTraversals + 1619(ViewRootImpl.java:1619)
       at android.view.ViewRootImpl.doTraversal + 1254(ViewRootImpl.java:1254)
       at android.view.ViewRootImpl$TraversalRunnable.run + 6337(ViewRootImpl.java:6337)
       at android.view.Choreographer$CallbackRecord.run + 874(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks + 686(Choreographer.java:686)
       at android.view.Choreographer.doFrame + 621(Choreographer.java:621)
       at android.view.Choreographer$FrameDisplayEventReceiver.run + 860(Choreographer.java:860)
       at android.os.Handler.handleCallback + 751(Handler.java:751)
       at android.os.Handler.dispatchMessage + 95(Handler.java:95)
       at android.os.Looper.loop + 154(Looper.java:154)
       at android.app.ActivityThread.main + 6119(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 886(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main + 776(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main + 107(XposedBridge.java:107)`

**Comment by mzelzoghbi** [comment]
@rdrobinson3 @mykhailo-gaidai  we will look into this and get back again to you.

**Comment by mzelzoghbi** [comment]
@rdrobinson3 @mykhailo-gaidai do you ship your app using Android App Bundle? if Yes, so the issue may be due to sharing the app using P2P sharing applications that share the main .apk file and didn't share the split .apk versions

for more info about this issue please check this thread on StackOverflow https://stackoverflow.com/a/53082301/2188269

Please feel free to reopen if the issue still persists. 
Thank You
