### ISSUE TITLE
NoSuchMethodError: No virtual method setHeaders(Ljava/lang/String;)V in class NetworkLog

### ISSUE THREAD

**Issue by Axrorxoja** [Instabug/Instabug-Android#171]
Hi, after update latest version of Instabug, we can't build app because of this issue 
```
java.lang.NoSuchMethodError: No virtual method setHeaders(Ljava/lang/String;)V in class Lcom/instabug/library/model/NetworkLog; or its super classes (declaration of 'com.instabug.library.model.NetworkLog' appears in /data/app/...-PrTamdZH0NNdFWC9c9Pqvg==/split_lib_slice_0_apk.apk!classes2.dex)
        at com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.intercept(InstabugOkhttpInterceptor.java:128)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by iadcialim** [comment]
I am encountering this in 
```
implementation 'com.instabug.library:instabug:10.7.1'
implementation 'com.instabug.library:instabug-with-okhttp-interceptor:10.4.3'
```
