### ISSUE TITLE
IllegalArgumentException: reportSizeConfigurations and RuntimeException: Unable to start activity 

### ISSUE THREAD

**Issue by biokys** [Instabug/Instabug-Android#176]
Hi, We are pretty new to Instabug. After first deployment into the production, we are having 2 different exceptions, placed below. Also I am enclosing code, how we interact with SDK. Any ideas where problem could be?

### Actual Behavior

The first one

```
Fatal Exception: java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{c3e1497 ActivityRecord{fb6316 u0 com.droid4you.application.wallet/com.instabug.library.ui.onboarding.OnboardingActivity t-1 f}}
       at android.os.Parcel.createException(Parcel.java:1954)
       at android.os.Parcel.readException(Parcel.java:1918)
       at android.os.Parcel.readException(Parcel.java:1868)
       at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:8668)
       at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:3310)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3265)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5021)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4930)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
       at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4980)
       at android.app.ActivityThread.access$3300(ActivityThread.java:213)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1987)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6923)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

The second one

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.droid4you.application.wallet/com.instabug.library.invocation.invocationdialog.InstabugDialogActivity}: java.lang.IllegalStateException: Could not find active fragment with unique id a46dd4ab-51d6-4060-9426-7ef3356ba2f9
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5008)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4917)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:59)
       at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4967)
       at android.app.ActivityThread.access$3300(ActivityThread.java:235)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1936)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

### Instabug integration code

Initialization (in Application class)
```
new Instabug.Builder(this, instaBugKey)
                    .setInvocationEvents(InstabugInvocationEvent.SHAKE)
                    .build();
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);
```

And later in the app (after sigin-in)
```
if ((Instabug.isEnabled()) {
            RibeezUser user = RibeezUser.getCurrentUser();
            Instabug.identifyUser(user.getFullName(), user.getEmail());
            Instabug.setUserAttribute("User Id", user.getId());
            Instabug.setUserAttribute("Premium", user.isInPremium() ? "True" : "False");
            String installationId = RibeezInstallation.getCurrentInstallation().getInstallationId();
            if (!TextUtils.isEmpty(installationId)) {
                Instabug.setPushNotificationRegistrationToken(installationId);
            }
        }
```

Manual invoking (for the first time only)

```
Instabug.showWelcomeMessage(WelcomeMessage.State.BETA);
```

and later

```
Instabug.show();
```

### SDK Version
8.1.2

### Android Version
9 (ONLY!)

### Device Model
Samsung, Xiaomi, Motorola

**Comment by mzelzoghbi** [comment]
Hi @biokys, Thanks for pointing this out, we are looking into it and will get back to you.

**Comment by mzelzoghbi** [comment]
Hi @biokys, After investigating, this is an issue in the android framework and will be fixed in Android Q, you can get more context from google issue tracker at this [link](https://issuetracker.google.com/issues/119763078)
