### ISSUE TITLE
IllegalStateException: DatabaseManager is not initialized, call init(..) method first.

### ISSUE THREAD

**Issue by fchicken** [Instabug/Instabug-Android#181]
Hi, we found an exception in our production. Below is the stack trace. Any help would be appreciated, thanks!

```
Fatal Exception: java.lang.IllegalStateException: DatabaseManager is not initialized, call init(..) method first.
       at com.instabug.library.internal.storage.cache.db.DatabaseManager.getInstance(DatabaseManager.java:24)
       at com.instabug.library.logging.a.b(a.java:84)
       at com.instabug.library.logging.a.a(a.java:32)
       at com.instabug.library.logging.a$1.a(a.java:58)
       at com.instabug.library.logging.a$1.onNext(a.java:43)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

### Instabug integration code
```java
new Instabug.Builder(this, BuildConfig.DEBUG ? INSTABUG_TOKEN_DEBUG : INSTABUG_TOKEN)
                .setInvocationEvents(InstabugInvocationEvent.NONE)
                .build();
```
### SDK Version
8.2.0

### Android Version
4~9

### Device Model
various devices

**Comment by mzelzoghbi** [comment]
Hi @fchicken, Thanks for reporting this, We created a **SNAPSHOT** that sould fix the issue, Can you please try it and tell us if the snapshot fixed the issue for you?
```
implementation 'com.instabug.library:instabug:8.2.0.5-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

**Comment by fchicken** [comment]
Hi @mzelzoghbi, I've tried the snapshot and it fixes the issue, thanks!
