### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.library.model.State com.instabug.bug.model.a.getState()' on a null object reference BugReportingFragment.java:264

### ISSUE THREAD

**Issue by rajasekaranm** [Instabug/Instabug-Android#190]
Hi,

### Instabug integration code

**Gradle;**

`implementation 'com.instabug.library:instabug:8.2.2'`

**Java:**

` new Instabug.Builder(this, BuildConfig.INSTABUG_KEY)
                .setInvocationEvents(InstabugInvocationEvent.SHAKE)
                .build();`

**SDK Version :** 28

**Device version :**  Android P

**Device Model :**  samsung SM-G950F

**Log:**

`java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.library.model.State com.instabug.bug.model.a.getState()' on a null object reference
	 at com.instabug.bug.view.c.initViews(BugReportingFragment.java:264)
	 at com.instabug.library.core.ui.BaseFragment.onCreateView(BaseFragment.java:38)
	 at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
	 at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	 at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	 at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	 at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
	 at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
	 at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
	 at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
	 at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	 at com.instabug.library.core.ui.BaseFragmentActivity.onStart(BaseFragmentActivity.java:50)
	 at com.instabug.bug.view.BugReportingActivity.onStart(BugReportingActivity.java:118)
	 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	 at android.app.Activity.performStart(Activity.java:7348)
	 at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3132)
	 at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	 at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
	 at android.os.Handler.dispatchMessage(Handler.java:106)
	 at android.os.Looper.loop(Looper.java:214)
	 at android.app.ActivityThread.main(ActivityThread.java:7045)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)`

Kindly let me know how to fix this issue?

**Comment by mzelzoghbi** [comment]
Hey @rajasekaranm 

Thanks for reporting this, you can use this snapshot
```
implementation 'com.instabug.library:instabug:8.2.2.10-SNAPSHOT'
```
And don't forget to add this to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
    ...
}
```
Please let me know if everything works out.

**Comment by mzelzoghbi** [comment]
Hi @rajasekaranm, I’m closing this issue because it has been fixed and released. Please reopen if you still encounter this issue with the latest version **8.3.0** Thank you! :blush:
