### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: DatabaseManager is not initialized

### ISSUE THREAD

**Issue by adavis** [Instabug/Instabug-Android#191]
### Steps to Reproduce the Problem
I don't know where this is happening.

### Expected Behavior
No crash

### Actual Behavior
```
Fatal Exception: java.lang.IllegalStateException: DatabaseManager is not initialized, call init(..) method first.
       at com.instabug.library.internal.storage.cache.db.DatabaseManager.getInstance(DatabaseManager.java:24)
       at com.instabug.library.logging.a.b(a.java:84)
       at com.instabug.library.logging.a.a(a.java:32)
       at com.instabug.library.logging.a$1.a(a.java:58)
       at com.instabug.library.logging.a$1.onNext(a.java:43)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

### Instabug integration code
```
Instabug.Builder(this,
                             getString(R.string.instabug_api_key),
                             InstabugInvocationEvent.SHAKE)
                    .build()
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
```

### SDK Version
8.2.2

### Android Version
 4.4.2, 5.1, 7.0

### Device Model
TECHNO, Samsung

**Comment by francesctt** [comment]
Same crash is seen on our side :-(

**Comment by protemus** [comment]
We are also seeing this same issue in com.instabug.library:instabug:8.2.2.  Looking over a previous issue report I found an old comment that says it was fixed in this SNAPSHOT:  com.instabug.library:instabug:8.2.0.5-SNAPSHOT.  I switched to that snapshot and it works for me now.

Has this fix not made it to the main distribution of com.instabug.library:instabug:8.2.2?

**Comment by mzelzoghbi** [comment]
Hi @adavis @protemus , Thanks for reporting this, This fix will be included in the next release, for now we created a new **SNAPSHOT** from the latest distribution
```
implementation 'com.instabug.library:instabug:8.2.2.11-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by mzelzoghbi** [comment]
Hi @adavis @protemus , I’m closing this issue because it has been fixed and released. Please reopen if you still encounter this issue with the latest version **8.3.0** Thank you! 😊
