### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException android.os.TransactionTooLargeException

### ISSUE THREAD

**Issue by pahakorolev** [Instabug/Instabug-Android#194]
### Stack trace
Fatal Exception: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1948240 bytes
       at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
       at android.os.Handler.handleCallback(Handler.java:891)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7470)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by android.os.TransactionTooLargeException: data parcel size 1948240 bytes
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:1147)
       at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4005)
       at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
       at android.os.Handler.handleCallback(Handler.java:891)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7470)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
### Instabug version
We use version 8+ from your integration documentation
"com.instabug.library:instabug:8+"
### Instabug integration code
```
 Instabug.Builder(context, apiKey)
            .setInvocationEvents(InstabugInvocationEvent.SHAKE)
            .build()
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
Chats.setState(Feature.State.DISABLED);
FeatureRequests.setState(Feature.State.DISABLED);
```
### Device for example
Device
Brand: HUAWEI
Model: Mate 20
Orientation: Portrait
RAM free: 834.32 MB
Disk free: 50.07 GB
Operating System
Version: 9
Orientation: Portrait
Rooted: No
Crash
Date: May 21, 2019, 12:59:00 PM
App version: 0.4.119 (119)

![Screen Shot 2019-05-21 at 4 49 25 PM](https://user-images.githubusercontent.com/6101875/58101561-91c8dd00-7be8-11e9-96ff-5e1844440a35.png)

**Comment by Muhammadyoussef** [comment]
Hi @pahakorolev ,
Would you please include the steps to reproduce (if any) and wether or not it happens with a specific Instabug view or multiple ones? (i.e. Bug reporting)

Also it will be really helpful to enable Instabug debug logs and share with us the set of logs right before this crash occurs. 
To enable Instabug debug logs you will have to add the following line right after the integration code. 
`Instabug.setDebugEnabled(true)`

Thanks in advance!

**Comment by pahakorolev** [comment]
To my regret, this problem is not reproduced on our devices. According to the user's steps, it is reproduced after the device is shaken. As an android developer, I can assume that the problem is in transferring a screenshot of the screen through the PendingTransaction with size 1948240 bytes.

**Comment by Muhammadyoussef** [comment]
Hi @pahakorolev ,
Just to let you know, we pass `Uri`s and we make sure we never exceed the transaction limit. So, chances are that this crash is not caused by Instabug. 
Please let me know if you have any further concerns ^^

**Comment by pahakorolev** [comment]
Hi @Muhammadyoussef ,
Thank you. We will try to find out additional details about this issue.
