### ISSUE TITLE
IllegalStateException DatabaseManager is not initialized, call init method first

### ISSUE THREAD

**Issue by Axrorxoja** [Instabug/Instabug-Android#195]
![photo_2019-05-24_10-39-27](https://user-images.githubusercontent.com/5182036/58305340-2f065a00-7e11-11e9-99b7-6e6ad49021a7.jpg)

**Comment by Axrorxoja** [comment]
`2019-05-24 14:36:43.816 15617-15719/com.mysuperdispatch.android E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.mysuperdispatch.android, PID: 15617
    java.lang.IllegalStateException: DatabaseManager is not initialized, call init(..) method first.
        at com.instabug.library.internal.storage.cache.db.DatabaseManager.getInstance(DatabaseManager.java:24)
        at com.instabug.library.logging.b.a(InstabugNetworkLogDbHelper.java:22)
        at com.instabug.library.model.NetworkLog.insert(NetworkLog.java:161)
        at com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.populateNetworkResponse(InstabugOkhttpInterceptor.java:267)
        at com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.intercept(InstabugOkhttpInterceptor.java:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
`

**Comment by Axrorxoja** [comment]
2019-05-24 14:36:43.816 15617-15719/com.xxx.yyy E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.xxx.yyy, PID: 15617
    java.lang.IllegalStateException: DatabaseManager is not initialized, call init(..) method first.
        at com.instabug.library.internal.storage.cache.db.DatabaseManager.getInstance(DatabaseManager.java:24)
        at com.instabug.library.logging.b.a(InstabugNetworkLogDbHelper.java:22)
        at com.instabug.library.model.NetworkLog.insert(NetworkLog.java:161)
        at com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.populateNetworkResponse(InstabugOkhttpInterceptor.java:267)
        at com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.intercept(InstabugOkhttpInterceptor.java:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by mzelzoghbi** [comment]
Hey @Axrorxoja, Thanks for reaching out, This issue has been solved in our latest release **8.4.0**, Please reopen if you still encounter this issue Thank you! 😊

**Comment by Axrorxoja** [comment]
@mzelzoghbi thank you too much :)
