### ISSUE TITLE
Failed resolution of UserAttributesDbHelper

### ISSUE THREAD

**Issue by hugosvent** [Instabug/Instabug-Android#196]
### Steps to Reproduce the Problem
Sending report success

### Expected Behavior
Don't crash, and bug sent to dashboard

### Actual Behavior
Crash after sending bug report, bug sent are not recorded in dashbaord

### Instabug integration code
```kotlin
Instabug.Builder(this, APIKEY)
            .setInvocationEvents(InstabugInvocationEvent.NONE)
            .setReproStepsState(State.ENABLED_WITH_NO_SCREENSHOTS)
            .build()
```

stacktrace :
```
2019-05-25 14:14:54.246 15352-17119/com.bukalapak.android E/AndroidRuntime: FATAL EXCEPTION: Thread-137
    Process: com.bukalapak.android, PID: 15352
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/internal/storage/cache/db/UserAttributesDbHelper;
        at com.instabug.bug.e.g(LiveBugManager.java:201)
        at com.instabug.bug.e$1.run(LiveBugManager.java:148)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.internal.storage.cache.db.UserAttributesDbHelper" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.bukalapak.android-4XoxkbR93YftQRQkRRK70A==/base.apk"],nativeLibraryDirectories=[/data/app/com.bukalapak.android-4XoxkbR93YftQRQkRRK70A==/lib/arm, /data/app/com.bukalapak.android-4XoxkbR93YftQRQkRRK70A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.instabug.bug.e.g(LiveBugManager.java:201) 
        at com.instabug.bug.e$1.run(LiveBugManager.java:148) 
        at java.lang.Thread.run(Thread.java:764) 
2019-05-25 14:14:54.278 15352-17119/com.bukalapak.android E/MonitorLogger: [Thread-137] crash: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/internal/storage/cache/db/UserAttributesDbHelper;
        at com.instabug.bug.e.g(LiveBugManager.java:201)
        at com.instabug.bug.e$1.run(LiveBugManager.java:148)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.internal.storage.cache.db.UserAttributesDbHelper" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.bukalapak.android-4XoxkbR93YftQRQkRRK70A==/base.apk"],nativeLibraryDirectories=[/data/app/com.bukalapak.android-4XoxkbR93YftQRQkRRK70A==/lib/arm, /data/app/com.bukalapak.android-4XoxkbR93YftQRQkRRK70A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.instabug.bug.e.g(LiveBugManager.java:201) 
        at com.instabug.bug.e$1.run(LiveBugManager.java:148) 
        at java.lang.Thread.run(Thread.java:764) 
2019-05-25 14:14:54.278 15352-17119/com.bukalapak.android E/Appender: backupCurrentFile: no target log file
2019-05-25 14:14:54.278 15352-17119/com.bukalapak.android E/automationcrash: Force Start parse for automation
2019-05-25 14:14:54.278 15352-17119/com.bukalapak.android E/LoggingUtil: [Thread-137]crash: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/internal/storage/cache/db/UserAttributesDbHelper;
        at com.instabug.bug.e.g(LiveBugManager.java:201)
        at com.instabug.bug.e$1.run(LiveBugManager.java:148)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.internal.storage.cache.db.UserAttributesDbHelper" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.bukalapak.android-4XoxkbR93YftQRQkRRK70A==/base.apk"],nativeLibraryDirectories=[/data/app/com.bukalapak.android-4XoxkbR93YftQRQkRRK70A==/lib/arm, /data/app/com.bukalapak.android-4XoxkbR93YftQRQkRRK70A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.instabug.bug.e.g(LiveBugManager.java:201) 
        at com.instabug.bug.e$1.run(LiveBugManager.java:148) 
        at java.lang.Thread.run(Thread.java:764) 

```

**Comment by hugosvent** [comment]
fixed it by synchronizing instabug and instabug-with-okhttp-interceptor version.

should have not use 8+ version on instabug-with-okhttp-interceptor
