### ISSUE TITLE
SQLiteDatabaseLockedException: database is locked (code 5) when Instabug is used in several processes.

### ISSUE THREAD

**Issue by ivabra** [Instabug/Instabug-Android#203]
### Steps to Reproduce the Problem
1) Implement an Android app with background service that uses a separate process
2) Initialize Instabug library in both processes
3) Start logging actively
4) Sooner or later it will crash.

### Expected Behavior
Instabug manages separate databases for every process and doesn't crash.

### Actual Behavior
Instabug crashes with `android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode`

### Instabug integration code
```kotlin
Instabug
 .Builder(this, token)
 .setViewHierarchyState(Feature.State.ENABLED)
 .setInvocationEvents(InstabugInvocationEvent.NONE)
 .build(Feature.State.ENABLED)

Instabug.setDebugEnabled(BuildConfig.DEBUG)
Instabug.setColorTheme(InstabugColorTheme.InstabugColorThemeLight)
Instabug.setDebugEnabled(false)
CrashReporting.setState(Feature.State.DISABLED)
```

### SDK Version
8.4.0

### Android Version
Android 6 -> Android 9

### Device Model
Wide range of models. Mostly Samsung S8-S9.

### Stacktrace
```
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
#################################################################
Error Code : 5 (SQLITE_BUSY)
Caused By : The database file is locked.
	(database is locked (code 5): , while compiling: PRAGMA journal_mode)
#################################################################
    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1008)
    at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:712)
    at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:389)
    at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:363)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:252)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:203)
    at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:518)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:209)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:181)
    at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1156)
    at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1101)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:832)
    at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:681)
    at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:324)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
    at com.instabug.library.internal.storage.cache.db.SQLiteDatabaseWrapper.open(SQLiteDatabaseWrapper.java:2)
    at com.instabug.library.internal.storage.cache.db.DatabaseManager.openDatabase(DatabaseManager.java:1)
    at com.instabug.library.internal.a.h$a.b(Scope.java:1)
    at com.instabug.library.internal.a.h$a.a(Scope.java:1)
    at com.instabug.library.internal.a.h$a$1.b(Scope.java:1)
    at com.instabug.library.internal.a.b.a(DisposableData.java:5)
    at com.instabug.library.internal.a.b.a(DisposableData.java:3)
    at com.instabug.library.internal.a.b.b(DisposableData.java:2)
    at com.instabug.library.internal.a.b$1.run(DisposableData.java:1)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at com.instabug.library.util.threading.b$1.run(PriorityThreadFactory.java:5)
    at java.lang.Thread.run(Thread.java:762)
```

**Comment by mzelzoghbi** [comment]
Hey @ivabra, Thanks for reporting this. We tried to reproduce the issue but we couldn't probably we are missing something. Can you share with us a sample project with the issue?

**Comment by ivabra** [comment]
Hi @mzelzoghbi,
Thanks for investigation.
In our case, we use a foreground service (that must have its own notification)(not really sure that there is a difference in this case). We are pretty sure that the problem is several processes because we started getting crash reports with this issue right after releasing an app version with the foreground service.
It is 30 times more frequent than the next reason in our top crash reasons list.

**Comment by mzelzoghbi** [comment]
Hey @ivabra, We designed the SDK to work only on a single process but we will work on a fix and will get back to you ASAP, but till we fix this, is it really important running the service on another process?

**Comment by ivabra** [comment]
@mzelzoghbi Yes, it is quite important. We disabled Instabug for our service, so we are not able to read logs of the service in user reports.

**Comment by SAGV** [comment]
@ivabra could you explain why is it important and what benefits does it bring to the app?

**Comment by ivabra** [comment]
@SAGV because it frees up the app process from a bunch of RAM and CPU work, so it won't be killed by the system so fast.

**Comment by amrbrkt** [comment]
I highly recommend updating to our latest version `10.2.0`, this should be fixed.
I'm closing this for now, but please feel free to reopen it if you still facing the same issue.

**Comment by radityagumay** [comment]
this basically happens if the app has multi-process, and the process has to wait 2500ms to execute the queries. if the timeout exceeded it will throw SQLiteDatabaseLockedException.
