### ISSUE TITLE
Failed resolution of: Lcom/instabug/library/network/a

### ISSUE THREAD

**Issue by ajaysharma1990** [Instabug/Instabug-Android#211]
1564982580.244 16138-16672/com.WegileWildcard.transform905009 E/AndroidRuntime: FATAL EXCEPTION: AnalyticsObserver
    Process: com.WegileWildcard.transform905009, PID: 16138
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/network/a;
        at com.instabug.library.Instabug$Builder.build(Instabug.java:3406)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:3482)
        at com.WegileWildcard.transform905009.TransformApp.instaBug(TransformApp.java:249)
        at com.WegileWildcard.transform905009.login.presenter.impl.SplashPresenterImpl.hasUserSession(SplashPresenterImpl.java:47)
        at com.WegileWildcard.transform905009.login.SplashActivity.lambda$onViewInjected$0$SplashActivity(SplashActivity.java:116)
        at com.WegileWildcard.transform905009.login.SplashActivity$$Lambda$0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.ClassNotFoundException: com.instabug.library.network.a
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:3406) 
        at com.instabug.library.Instabug$Builder.build(Instabug.java:3482) 
        at com.WegileWildcard.transform905009.TransformApp.instaBug(TransformApp.java:249) 
        at com.WegileWildcard.transform905009.login.presenter.impl.SplashPresenterImpl.hasUserSession(SplashPresenterImpl.java:47) 
        at com.WegileWildcard.transform905009.login.SplashActivity.lambda$onViewInjected$0$SplashActivity(SplashActivity.java:116) 
        at com.WegileWildcard.transform905009.login.SplashActivity$$Lambda$0.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/JobIntentService;
        at com.instabug.library.Instabug$Builder.build(Instabug.java:3406) 
        at com.instabug.library.Instabug$Builder.build(Instabug.java:3482) 
        at com.WegileWildcard.transform905009.TransformApp.instaBug(TransformApp.java:249) 
        at com.WegileWildcard.transform905009.login.presenter.impl.SplashPresenterImpl.hasUserSession(SplashPresenterImpl.java:47) 
        at com.WegileWildcard.transform905009.login.SplashActivity.lambda$onViewInjected$0$SplashActivity(SplashActivity.java:116) 
        at com.WegileWildcard.transform905009.login.SplashActivity$$Lambda$0.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.JobIntentService" on path: DexPathList[[zip file "/data/app/com.WegileWildcard.transform905009-n3OxVi3MZlukri0VVl4wYw==/base.apk"],nativeLibraryDirectories=[/data/app/com.WegileWildcard.transform905009-n3OxVi3MZlukri0VVl4wYw==/lib/arm, /data/app/com.WegileWildcard.transform905009-n3OxVi3MZlukri0VVl4wYw==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:3406) 
        at com.instabug.library.Instabug$Builder.build(Instabug.java:3482) 
        at com.WegileWildcard.transform905009.TransformApp.instaBug(TransformApp.java:249) 
        at com.WegileWildcard.transform905009.login.presenter.impl.SplashPresenterImpl.hasUserSession(SplashPresenterImpl.java:47) 
        at com.WegileWildcard.transform905009.login.SplashActivity.lambda$onViewInjected$0$SplashActivity(SplashActivity.java:116) 
        at com.WegileWildcard.transform905009.login.SplashActivity$$Lambda$0.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
1564982584.314 16138-16315/com.WegileWildcard.transform905009 E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: com.WegileWildcard.transform905009, PID: 16138
    java.lang.InternalError: Thread starting during runtime shutdown
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:733)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1043)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1185)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

### I got this error while I upgrade the last 4.0.11snapshot version to 8.0.3.

###Please help me to resolve this issue

**Comment by mzelzoghbi** [comment]
Hi @ajaysharma1990, Thanks for reporting this, Can you try to upgrade to **8.5.0** it is our latest stable version and make sure that you make a clean build before running the app.

**Comment by ajaysharma1990** [comment]
Sure i will do that

**Comment by ajaysharma1990** [comment]
AGPBI: {"kind":"error","text":"error: style attribute \u0027attr/autoSizeMaxTextSize (aka com.WegileWildcard.transform905009:attr/autoSizeMaxTextSize)\u0027 not found.","sources":[{"file":"/Users/wegile/.gradle/caches/transforms-1/files-1.1/instabug-core-8.5.0.aar/f878d5b95c470ba9517f1eb437669761/res/values/values.xml","position":{"startLine":579,"startColumn":4,"startOffset":37627,"endLine":582,"endColumn":12,"endOffset":37850}}],"original":"","tool":"AAPT"}
:app:processDebugResources
:app:processDebugResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.


### Hi getting this error unable to sync the code properly

**Comment by mzelzoghbi** [comment]
@ajaysharma1990 Can you please try to invalidate **AndroidStudio** cache from **File** -> **Invalidate Cache/restart** ?

**Comment by ajaysharma1990** [comment]
@mzelzoghbi  I was tried same File -> Invalidate Cache/restart , getting no luck same error repeat again and again 
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/network/a;

i also try to re sync project with grdile also but getting no luck

FATAL EXCEPTION: main
    Process: com.WegileWildcard.transform905009, PID: 13471
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/a;
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1440)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1517)
        at com.WegileWildcard.transform905009.TransformApp.instaBug(TransformApp.java:249)
        at com.WegileWildcard.transform905009.login.presenter.impl.SplashPresenterImpl.hasUserSession(SplashPresenterImpl.java:47)
        at com.WegileWildcard.transform905009.login.SplashActivity.lambda$onViewInjected$0$SplashActivity(SplashActivity.java:116)
        at com.WegileWildcard.transform905009.login.-$$Lambda$SplashActivity$DJeysa7IGFKt8YRRjHP-Duv_BFE.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.ClassNotFoundException: android.support.v4.app.a
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1440) 
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1517) 
        at com.WegileWildcard.transform905009.TransformApp.instaBug(TransformApp.java:249) 
        at com.WegileWildcard.transform905009.login.presenter.impl.SplashPresenterImpl.hasUserSession(SplashPresenterImpl.java:47) 
        at com.WegileWildcard.transform905009.login.SplashActivity.lambda$onViewInjected$0$SplashActivity(SplashActivity.java:116) 
        at com.WegileWildcard.transform905009.login.-$$Lambda$SplashActivity$DJeysa7IGFKt8YRRjHP-Duv_BFE.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/JobIntentService;
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1440) 
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1517) 
        at com.WegileWildcard.transform905009.TransformApp.instaBug(TransformApp.java:249) 
        at com.WegileWildcard.transform905009.login.presenter.impl.SplashPresenterImpl.hasUserSession(SplashPresenterImpl.java:47) 
        at com.WegileWildcard.transform905009.login.SplashActivity.lambda$onViewInjected$0$SplashActivity(SplashActivity.java:116) 
        at com.WegileWildcard.transform905009.login.-$$Lambda$SplashActivity$DJeysa7IGFKt8YRRjHP-Duv_BFE.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.JobIntentService" on path: DexPathList[[zip file "/data/app/com.WegileWildcard.transform905009-Axe3a40uARODTyDvQQQbEg==/base.apk"],nativeLibraryDirectories=[/data/app/com.WegileWildcard.transform905009-Axe3a40uARODTyDvQQQbEg==/lib/arm, /data/app/com.WegileWildcard.transform905009-Axe3a40uARODTyDvQQQbEg==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1440) 
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1517) 
        at com.WegileWildcard.transform905009.TransformApp.instaBug(TransformApp.java:249) 
        at com.WegileWildcard.transform905009.login.presenter.impl.SplashPresenterImpl.hasUserSession(SplashPresenterImpl.java:47) 
        at com.WegileWildcard.transform905009.login.SplashActivity.lambda$onViewInjected$0$SplashActivity(SplashActivity.java:116) 
        at com.WegileWildcard.transform905009.login.-$$Lambda$SplashActivity$DJeysa7IGFKt8YRRjHP-Duv_BFE.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by mzelzoghbi** [comment]
@ajaysharma1990 Can you reproduce the issue on a sample app?

**Comment by ajaysharma1990** [comment]
i will try this one and let you know

**Comment by ajaysharma1990** [comment]
Hi
I have reproduce the same issue on sample app.

**Comment by ajaysharma1990** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.a.myapplication, PID: 7268
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/a;
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1440)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1517)
        at com.a.myapplication.MyApplication.onCreate(MyApplication.java:24)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6158)
        at android.app.ActivityThread.access$1200(ActivityThread.java:235)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.ClassNotFoundException: android.support.v4.app.a
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1440) 
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1517) 
        at com.a.myapplication.MyApplication.onCreate(MyApplication.java:24) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6158) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:235) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/JobIntentService;
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1440) 
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1517) 
        at com.a.myapplication.MyApplication.onCreate(MyApplication.java:24) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6158) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:235) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.JobIntentService" on path: DexPathList[[zip file "/data/app/com.a.myapplication-F3ncHablNGWsfsniI6cFpQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.a.myapplication-F3ncHablNGWsfsniI6cFpQ==/lib/arm, /data/app/com.a.myapplication-F3ncHablNGWsfsniI6cFpQ==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1440) 
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1517) 
        at com.a.myapplication.MyApplication.onCreate(MyApplication.java:24) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6158) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:235) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 


### This is the stack with Sample app

**Comment by ajaysharma1990** [comment]
### Hi All Please help to resolve this issue. 
I have several user getting crashes every day so i have to change the old dependency to new one.
Please help me.

**Comment by ajaysharma1990** [comment]
Any update

**Comment by mzelzoghbi** [comment]
Hi @ajaysharma1990 Can you please share with us the sample app?
