### ISSUE TITLE
App Crashed with NullPointerException

### ISSUE THREAD

**Issue by sallukp** [Instabug/Instabug-Android#218]
The crash log
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.instabug.bug.model.a.i()' on a null object reference
	 at com.instabug.bug.view.reporting.b$14.run(BaseReportingFragment.java:523)
	 at com.instabug.bug.view.reporting.b.a(BaseReportingFragment.java:588)
	 at com.instabug.bug.view.reporting.b.onClick(BaseReportingFragment.java:520)
	 at android.view.View.performClick(View.java:7352)
	 at android.view.View.performClickInternal(View.java:7318)
	 at android.view.View.access$3200(View.java:846)
	 at android.view.View$PerformClick.run(View.java:27800)
	 at android.os.Handler.handleCallback(Handler.java:873)
	 at android.os.Handler.dispatchMessage(Handler.java:99)
	 at android.os.Looper.loop(Looper.java:214)
	 at android.app.ActivityThread.main(ActivityThread.java:7045)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

### Crash happened for the following events
The following methods executed in Activity
```
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)
getDelegate().applyDayNight();
```
Then reported a bug and app crashed

### Instabug integration code
```
new Instabug.Builder(this, "__TOKEN__")
                .setInvocationEvents(InstabugInvocationEvent.SHAKE)
                .setReproStepsState(State.DISABLED)
                .build();
```

### SDK Version
`implementation 'com.instabug.library:instabug:8.7.0-SNAPSHOT'`

### Android Version
OS Level 28
### Device Model
samsung SM-G955F

**Comment by amrbrkt** [comment]
Thank you @sallukp for reporting this, we are looking into. Will get back to you as soon as possible.

**Comment by amrbrkt** [comment]
Hey @sallukp  We tried to reproduce the issue but we can't, Is it consistent overall devices or on a specific device? Also, It will be great to share with us a sample project producing the issue if possible.

**Comment by amrbrkt** [comment]
Hi @sallukp, Please update to our recent stable version `8.7.0` and let User Steps know if you still facing any problem. I'll close this issue for now.
