### ISSUE TITLE
Missing onError handler in the subscribe() method call, caused by android.os.DeadObjectException

### ISSUE THREAD

**Issue by AlexWih** [Instabug/Instabug-Android#219]
### Steps to Reproduce the Problem
Specifics steps are not known as only crashes are seen in Fabric.

### Expected Behavior
No crash.

### Actual Behavior
Crash happens:

```
 Fatal Exception: io.reactivex.b.d: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.RuntimeException: android.os.DeadObjectException
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept + 704(Functions.java:704)
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept + 701(Functions.java:701)
       at io.reactivex.internal.observers.LambdaObserver.onError + 77(LambdaObserver.java:77)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError + 63(ObservableSubscribeOn.java:63)
       at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual + 47(ObservableFromCallable.java:47)
       at io.reactivex.Observable.subscribe + 12267(Observable.java:12267)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run + 96(ObservableSubscribeOn.java:96)
       at io.reactivex.Scheduler$DisposeTask.run + 578(Scheduler.java:578)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run + 66(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call + 57(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run + 237(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201 + 154(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run + 269(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1113(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 588(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run + 818(Thread.java:818)

Caused by java.lang.RuntimeException: android.os.DeadObjectException
       at android.os.storage.StorageManager.getVolumeList + 890(StorageManager.java:890)
       at android.os.Environment$UserEnvironment.getExternalDirs + 83(Environment.java:83)
       at android.os.Environment.getExternalStorageState + 639(Environment.java:639)
       at com.instabug.library.util.DeviceStateProvider.externalMemoryAvailable + 243(DeviceStateProvider.java:243)
       at com.instabug.library.util.DeviceStateProvider.getUsedStorage + 221(DeviceStateProvider.java:221)
       at com.instabug.library.c.a.b + 154(a.java:154)
       at com.instabug.library.c.a.c + 33(a.java:33)
       at com.instabug.library.c.a$3.a + 124(a.java:124)
       at com.instabug.library.c.a$3.call + 121(a.java:121)
       at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual + 43(ObservableFromCallable.java:43)
       at io.reactivex.Observable.subscribe + 12267(Observable.java:12267)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run + 96(ObservableSubscribeOn.java:96)
       at io.reactivex.Scheduler$DisposeTask.run + 578(Scheduler.java:578)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run + 66(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call + 57(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run + 237(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201 + 154(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run + 269(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1113(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 588(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run + 818(Thread.java:818)

Caused by android.os.DeadObjectException
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact + 503(BinderProxy.java:503)
       at android.content.pm.IPackageManager$Stub$Proxy.getPackageUid + 2754(IPackageManager.java:2754)
       at android.os.storage.StorageManager.getVolumeList + 884(StorageManager.java:884)
       at android.os.Environment$UserEnvironment.getExternalDirs + 83(Environment.java:83)
       at android.os.Environment.getExternalStorageState + 639(Environment.java:639)
       at com.instabug.library.util.DeviceStateProvider.externalMemoryAvailable + 243(DeviceStateProvider.java:243)
       at com.instabug.library.util.DeviceStateProvider.getUsedStorage + 221(DeviceStateProvider.java:221)
       at com.instabug.library.c.a.b + 154(a.java:154)
       at com.instabug.library.c.a.c + 33(a.java:33)
       at com.instabug.library.c.a$3.a + 124(a.java:124)
       at com.instabug.library.c.a$3.call + 121(a.java:121)
       at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual + 43(ObservableFromCallable.java:43)
       at io.reactivex.Observable.subscribe + 12267(Observable.java:12267)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run + 96(ObservableSubscribeOn.java:96)
       at io.reactivex.Scheduler$DisposeTask.run + 578(Scheduler.java:578)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run + 66(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call + 57(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run + 237(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201 + 154(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run + 269(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1113(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 588(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run + 818(Thread.java:818)
```

### Instabug integration code
```kotlin
Instabug.Builder(application, application.getString(/*hidden*/))
    .setInvocationEvents(InstabugInvocationEvent.SHAKE)
    .build()

Instabug.setLocale(Locale.GERMAN)
CrashReporting.setState(Feature.State.DISABLED)
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
Chats.setState(Feature.State.DISABLED)
Replies.setState(Feature.State.DISABLED)
BugReporting.setShakingThreshold(900)

BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK)

Instabug.setColorTheme(com.instabug.library.InstabugColorTheme.InstabugColorThemeDark)
Instabug.setPrimaryColor(Color.WHITE)

val textPlaceHolders = InstabugCustomTextPlaceHolder()
textPlaceHolders.set(
    InstabugCustomTextPlaceHolder.Key.INVOCATION_HEADER,
    application.getString(/*hidden*/)
)

textPlaceHolders.set(
    InstabugCustomTextPlaceHolder.Key.REPORT_BUG,
    application.getString(/*hidden*/)
)

textPlaceHolders.set(
    InstabugCustomTextPlaceHolder.Key.COMMENT_FIELD_HINT_FOR_BUG_REPORT,
    application.getString(/*hidden*/)
)

textPlaceHolders.set(
    InstabugCustomTextPlaceHolder.Key.REPORT_FEEDBACK,
    application.getString(/*hidden*/)
)

textPlaceHolders.set(
    InstabugCustomTextPlaceHolder.Key.COMMENT_FIELD_HINT_FOR_FEEDBACK,
    application.getString(/*hidden*/)
)
Instabug.setCustomTextPlaceHolders(textPlaceHolders)
```

### SDK Version
```
instabugVersion = '8.4.0'
implementation "com.instabug.library:instabug:$instabugVersion"
```

### Android Version
Occurs on Android ver. 5,6,7

### Device Model
Occurs on multiple device models, majoriy is Samsung (59%)

**Comment by amrbrkt** [comment]
Thanks, @AlexWih for your report, we're working on that crash.

**Comment by Muhammadyoussef** [comment]
Hi @AlexWih, 

We wanted to let you know that `v8.7.0` now has the fix for this issue. Please accept our apologies for any inconvenience caused. We sincerely appreciate your feedback because it helps us build a better experience.

If you faced any other issues, please feel welcome to reach back out as we would be more than happy to assist.

Cheers 🥂

**Comment by AbdulmalekAlshugaa** [comment]
the same issue still appears in some devices

**Comment by Abdul-Rizwan** [comment]
Yes still facing the same issue. 

Fatal Exception: io.reactivex.exceptions.d: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
       at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:82)
       at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onError(MaybeMap.java:94)
       at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.tryOnError(MaybeCreate.java:100)
       at kotlinx.coroutines.rx2.RxMaybeCoroutine.onCancelled(RxMaybe.kt:54)
       at kotlinx.coroutines.AbstractCoroutine.onCompletionInternal(AbstractCoroutine.kt:91)
       at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:235)
       at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
       at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
       at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
