### ISSUE TITLE
java.lang.RuntimeException during Instabug.Builder().build()

### ISSUE THREAD

**Issue by harryarakkal** [Instabug/Instabug-Android#233]
### Steps to Reproduce the Problem
Upgrade to Instabug 8.7.0
Try to instantiate Instabug.

### Expected Behavior
Build without throwing an exception.

### Actual Behavior
Throws an exception.

### Instabug integration code
        // Instabug
        new Instabug.Builder( activity.getApplication(), "app token" )
                .setInvocationEvents( InstabugInvocationEvent.SCREENSHOT )
                .build();

### SDK Version
8.7.0

### Android Version
Android Pie

### Device Model
LG G7

I encountered the crash in https://github.com/Instabug/Instabug-Android/issues/224, so I tried upgrading to 8.7.0. Then, I ran into this exception which prevents the app from starting.

Caught exception: 
    java.lang.RuntimeException: Can't create handler inside thread Thread[AsyncTask #3,5,main] that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:205)
        at android.os.Handler.<init>(Handler.java:118)
        at com.instabug.chat.synchronization.SynchronizationManager.<init>(SynchronizationManager.java:69)
        at com.instabug.chat.synchronization.SynchronizationManager.init(SynchronizationManager.java:76)
        at com.instabug.chat.a.e(ChatPluginWrapper.java:32)
        at com.instabug.chat.a.b(ChatPluginWrapper.java:39)
        at com.instabug.chat.a.a(ChatPluginWrapper.java:28)
        at com.instabug.chat.ChatPlugin.init(ChatPlugin.java:30)
        at com.instabug.library.core.plugin.a.a(PluginsManager.java:35)
        at com.instabug.library.b.<init>(InstabugDelegate.java:71)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1123)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1194)
        at com.myapp.InitializeApp.safedk_Instabug$Builder_build_1b04762902b6a4faf3f63c43bcfde15e(Unknown Source:25)
        at com.myapp.InitializeApp.setupThirdPartyLibraries(InitializeApp.java:46)
        at com.myapp.InitializeApp.run(InitializeApp.java:29)
        at com.myapp.TaskBase.startTaskExecution(TaskBase.java:56)
        at com.myapp.TaskBase.access$000(TaskBase.java:12)
        at com.myapp.TaskBase$1$1.run(TaskBase.java:29)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by andrewdazs** [comment]
Same issue here... I'm using version `8.6.2`. Anyone know how to fix it?

**Comment by mzelzoghbi** [comment]
Hi @harryarakkal, Thanks for reporting this, From the integration code you shared we can see that you initialized the SDK in an Activity class & this is not recommended. We would recommend to move the integration code to the Application class and get back to us if the issue still occurs.

**Comment by mzelzoghbi** [comment]
@andrewdazs Can you try updating to the latest SDK version and make sure that the integration code is in the Application class?

**Comment by andrewdazs** [comment]
Thanks! I've made the update and everything is working fine.

**Comment by mzelzoghbi** [comment]
@andrewdazs Glad to hear that things are solved now :) If you face any problem, I will be happy to help you. 
Have a nice day 😄
