### ISSUE TITLE
Strict Mode Violation

### ISSUE THREAD

**Issue by ryanrampage1** [Instabug/Instabug-Android#235]
### Steps to Reproduce the Problem
Launch the app with strict mode enabled. 

Sample strict mode enable code: 
App.kt:
```kotlin 
        StrictMode.setVmPolicy(VmPolicy.Builder()
                .detectLeakedClosableObjects()
                .penaltyLog()
                .build())
```

This appears to be related to Issue https://github.com/Instabug/Instabug-Android/issues/95.

### Expected Behavior
No closable is leaked. 

### Actual Behavior
 A closable is leaked by the InsataBug SDK. 

```
2019-10-01 11:39:44.458 14629-14645/ D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1801)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:264)
        at java.util.zip.Inflater.finalize(Inflater.java:398)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:798)
     Caused by: java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:221)
        at java.util.zip.Inflater.<init>(Inflater.java:114)
        at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
        at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:473)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:648)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
        at com.instabug.library.network.NetworkManager$1.subscribe(NetworkManager.java:117)
        at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
        at io.reactivex.Observable.subscribe(Observable.java:12025)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:798) 
```
### Instabug integration code
Manifest: 
``` xml
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="remove"/>
```
App.kt: 
``` kotlin
Instabug.Builder(this, BuildConfig.INSTA_BUG_KEY)
                .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT)`
                .build()
```

### SDK Version
8.7.0

### Android Version
9

### Device Model
Moto g6 (Android one)

**Comment by mzelzoghbi** [comment]
Hi @ryanrampage1 , Thanks for reporting this.

From the initial investigation, it may be a false alarm or a bug in the `com.android.okhttp`. 
we will dig deep and keep you updated once we reach anything.

Thank You & Have a nice day 😃

**Comment by mzelzoghbi** [comment]
I think it is a bug in the android network Framework "okhttp", so it is safe to ignore. 

Thank You
