### ISSUE TITLE
Some crashes occured when Announcement feature is active

### ISSUE THREAD

**Issue by raymondctc** [Instabug/Instabug-Android#242]
### Steps to Reproduce the Problem
- We found that's a surge of crashes after Announcement was published.

Crash logs
```
Fatal Exception: lxf: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.ninegag.android.app/cache/instabug/assetCache/468202599: open failed: ENOENT (No such file or directory)
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
       at com.instabug.survey.announcements.cache.c$2$1.onFailed(c.java:93)
       at com.instabug.library.internal.storage.cache.AssetsCacheManager.notifyDownloadFailed(AssetsCacheManager.java:121)
       at com.instabug.library.internal.storage.cache.AssetsCacheManager$1.a(AssetsCacheManager.java:84)
       at com.instabug.library.internal.storage.cache.AssetsCacheManager$1.onFailed(AssetsCacheManager.java:74)
       at com.instabug.library.network.a.b$1.safedk_Request$Callbacks_onFailed_3ee24d61becbe85849ca0a24142d4691(b.java)
       at com.instabug.library.network.a.b$1.onError(b.java:55)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:281)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
       at android.os.Handler.handleCallback(Handler.java:742)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5603)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
```

```
Caused by java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.ninegag.android.app/cache/instabug/assetCache/468202599: open failed: ENOENT (No such file or directory)
       at libcore.io.IoBridge.open(IoBridge.java:452)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
       at com.safedk.android.internal.partials.InstabugFilesBridge.fileOutputStreamCtor(InstabugFilesBridge.java:630)
       at com.instabug.library.network.NetworkManager.handleFileDownloadRequestResponse(NetworkManager.java:314)
       at com.instabug.library.network.NetworkManager.access$600(NetworkManager.java:38)
       at com.instabug.library.network.NetworkManager$1.subscribe(NetworkManager.java:129)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
       at io.reactivex.Observable.subscribe(Observable.java:12246)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

```
Caused by android.system.ErrnoException: open failed: ENOENT (No such file or directory)
       at libcore.io.Posix.open(Posix.java)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
       at libcore.io.IoBridge.open(IoBridge.java:438)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
       at com.safedk.android.internal.partials.InstabugFilesBridge.fileOutputStreamCtor(InstabugFilesBridge.java:630)
       at com.instabug.library.network.NetworkManager.handleFileDownloadRequestResponse(NetworkManager.java:314)
       at com.instabug.library.network.NetworkManager.access$600(NetworkManager.java:38)
       at com.instabug.library.network.NetworkManager$1.subscribe(NetworkManager.java:129)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
       at io.reactivex.Observable.subscribe(Observable.java:12246)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

### Instabug integration code
```
new Instabug.Builder(application, application.getString(R.string.instabug_app_id))
                .setInvocationEvents(InstabugInvocationEvent.NONE)
                .build();
        Replies.setPushNotificationState(Feature.State.ENABLED);
        Instabug.setDebugEnabled(!AppBuildConfig.App.IS_RELEASE);
        Instabug.setPrimaryColor(ResourcesCompat.getColor(getResources(), R.color.under9_theme_black, null));
        // Arguments:initialScreenshot, extraScreenshot, galleryImage & ScreenRecording
        BugReporting.setAttachmentTypesEnabled(false, true, true, true);
        Surveys.setShouldShowWelcomeScreen(true);
        Chats.setState(Feature.State.DISABLED);
        CrashReporting.setState(Feature.State.DISABLED);
```

### SDK Version
8.7.0

### Android Version
All

**Comment by mzelzoghbi** [comment]
Hi @raymondctc ,

First of all, please accept our sincerest apologies for taking some time to come up with a fix for your issue. This was fixed in our latest version `9.0.3` 

Please give it a try, and let me know if it solves the issues you have. 
Thank you 😊
