### ISSUE TITLE
Disk read strict mode violation 

### ISSUE THREAD

**Issue by aaronweihe** [Instabug/Instabug-Android#251]
### Steps to Reproduce the Problem
Add strict mode policy `SampleApplication#onCreate` in the sample
```java
StrictMode.setThreadPolicy(
  new StrictMode.ThreadPolicy.Builder().detectDiskReads()
    .detectDiskWrites()
    .penaltyDeath()
    .build());
```
### Expected Behavior
No disk read on main thread.
### Actual Behavior
Strict mode violated with such a stacktrace:
```
FATAL EXCEPTION: main
Process: com.example.instabug, PID: 5762
java.lang.RuntimeException: Unable to create application com.example.instabug.SampleApplication: java.lang.RuntimeException: StrictMode ThreadPolicy violation
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
    at android.app.ActivityThread.access$1300(ActivityThread.java:219)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.RuntimeException: StrictMode ThreadPolicy violation
    at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1768)
    at android.os.StrictMode$AndroidBlockGuardPolicy.handleViolationWithTimingAttempt(StrictMode.java:163
   0)
    at android.os.StrictMode$AndroidBlockGuardPolicy.startHandlingViolationException(StrictMode.java:1601
   )
    at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
    at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
    at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
    at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7246)
    at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
    at java.io.File.exists(File.java:815)
    at android.app.ContextImpl.getDataDir(ContextImpl.java:2340)
    at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:590)
    at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:787)
    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:439)
    at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
    at com.instabug.library.settings.b.<init>(PersistableSettings.java:2)
    at com.instabug.library.settings.b.a(PersistableSettings.java:1)
    at com.instabug.library.settings.SettingsManager.init(SettingsManager.java:2)
    at com.instabug.library.Instabug$Builder.build(Instabug.java:1)
    at com.instabug.library.Instabug$Builder.build(Instabug.java:57)
    at com.example.instabug.SampleApplication.onCreate(SampleApplication.java:40)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
```
### Instabug integration code
I used the sample project in this repo.

### SDK Version
9.0.3
### Android Version
I used Android 10 but I believe this'd happen on all devices
### Device Model
Pixel 3 XL
### [Optional] Project That Reproduces the Issue
The sample project.

**Comment by mzelzoghbi** [comment]
Thanks @aaronhe42 for reporting this, we will take a look and get back to you ASAP.

**Comment by mzelzoghbi** [comment]
Hi @aaronweihe ,

First of all, please accept our sincerest apologies for taking some time to come up with a fix for your issue. 

We created a **SNAPSHOT** that should fix the issue, Can you give it a try & let us know if it fixed the issue for you?
```
implementation 'com.instabug.library:instabug:9.0.3.16-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You
