### ISSUE TITLE
java.lang.VerifyError: Rejecting class com.instabug.library.c because it failed compile-time verification

### ISSUE THREAD

**Issue by mahmoudElfeel67** [Instabug/Instabug-Android#254]
### Steps to produce
Initialize the builder in Application 

 ` new Instabug.Builder(this, getString(R.string.instabug_app_token))
                .setInvocationEvents(BuildConfig.DEBUG ? InstabugInvocationEvent.FLOATING_BUTTON : InstabugInvocationEvent.SHAKE)
                .build();`

### Its crashing with error

`java.lang.VerifyError: Rejecting class com.instabug.library.c because it failed compile-time verification (declaration of 'com.instabug.library.c' appears in /data/app/com.abjjad.app-1/base.apk)
        at com.instabug.library.Instabug$Builder.<init>(Instabug.java:10)
        at com.instabug.library.Instabug$Builder.<init>(Instabug.java:2)
        at com.instabug.library.Instabug$Builder.<init>(Instabug.java:1)
        at com.abjjad.app.MainApplication.onCreate(MainApplication.java:70)`

### Instabug integration code
*Make sure to remove your app token.*

```
new Instabug.Builder(this, getString(R.string.instabug_app_token))
                .setInvocationEvents(BuildConfig.DEBUG ? InstabugInvocationEvent.FLOATING_BUTTON : InstabugInvocationEvent.SHAKE)
                .build();

        Instabug.setLocale(new Locale("ar"));
        BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK);
```

### SDK Version
```
    implementation 'com.instabug.library:instabug:9.0.3'
    implementation 'com.instabug.library:instabug-with-okhttp-interceptor:9.0.3'
```

### Android Version

API 23

### Device Model
Sony z3

### [Optional] Project That Reproduces the Issue

Instabug is not crashing with version 8.7.2
We are using android x

**Comment by mzelzoghbi** [comment]
Hello @mahmoudElfeel67 , Thanks for reporting this. 
Can you try to update the SDK to  **9.0.3 ** and tell us if this solved your issue?

**Comment by mahmoudElfeel67** [comment]
Hello @mzelzoghbi  I am already on version 9.0.3 as you can see on the issue 
thats where its crashing 

its is not crashing in version 8.7.2 though

**Comment by mzelzoghbi** [comment]
sorry @mahmoudElfeel67 my bad I thought you are on 8.7.2, not 9.0.3. is this issue reproducible on a sample app?

**Comment by mzelzoghbi** [comment]
Hi @mahmoudElfeel67
 I’m closing this issue because of inactivity. Please reopen if you still encounter this issue with the latest version `9.0.4` 

Thank you! 😊

**Comment by TAGASK** [comment]
@mzelzoghbi I get it too on the version 9.0.4

**Comment by mpaillet3821** [comment]
@mzelzoghbi happening to me as well on version 9.0.5

**Comment by mahmoudElfeel67** [comment]
@mpaillet3821 are you using relic library ?
Updating to the latest version fixes this issue

**Comment by mpaillet3821** [comment]
That fixed the issue. You are a life saver! thanks for the info ;)
