### ISSUE TITLE
"Fragment already added" error when showing InstabugDialogActivity sometimes

### ISSUE THREAD

**Issue by FrancoSabadini** [Instabug/Instabug-Android#263]
### Steps to Reproduce the Problem

I got this app crash through Crashlytics so not sure how to reproduce it. It has only happened once so far.

Checking the logs of the crash the last screen that was shown before this crash was `InstabugDialogActivity` so I think it has to be some issue with the Fragments shown inside that Activity.

This is the stack trace from Crashlytics:

```
Fatal Exception: java.lang.IllegalStateException: Fragment already added: b{9e59347 (d0adce10-a03e-4549-8b27-a32ee9fffa17) app.android.dashboard.b}
       at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:1379)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:399)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7081)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

### Expected Behavior

The app doesn't crash when trying to open the Instabug dialog.

### Actual Behavior

The app crashes when calling `Instabug.show()` sometimes.

### Instabug integration code

```gradle
implementation("com.instabug.library:instabug:8.7.0")
implementation("com.instabug.library:instabug-with-okhttp-interceptor:8.7.0")

implementation("androidx.core:core-ktx:1.1.0")
implementation("androidx.appcompat:appcompat:1.1.0")
implementation("androidx.collection:collection-ktx:1.1.0")
implementation("androidx.fragment:fragment-ktx:1.1.0")
implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.1.0")
implementation("androidx.annotation:annotation:1.1.0")
implementation("androidx.cardview:cardview:1.0.0")
implementation("androidx.recyclerview:recyclerview:1.0.0")
implementation("androidx.constraintlayout:constraintlayout:1.1.3")
implementation("androidx.drawerlayout:drawerlayout:1.1.0-alpha03")
```

```kotlin
Instabug.Builder(app, INSTABUG_TOKEN)
                .setInvocationEvents(SHAKE)
                .build()

Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
```

### SDK Version

8.7.0

### Android Version

9

### Device Model

Galaxy J6

**Comment by amrbrkt** [comment]
Hi @FrancoSabadini 
I'm not sure if this stack trace is related to Instabug, I can't see any of Instabug views in the stack. 
Please let me know if you have further information that can help me debug the issue.

**Comment by FrancoSabadini** [comment]
Hi @amrbrkt, I'm not sure if it's an issue in Instabug either, but checking the logs from before the crash seems like the user was in the Instabug Activity mentioned in the report. I'll try to find more info but if I can't find anything feel free to close this in a couple of days as it has only happened once.

**Comment by amrbrkt** [comment]
I'll close this issue for now. Please don't hesitate to reach us if you found any additional info.
