### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'int android.net.NetworkInfo.getType()'

### ISSUE THREAD

**Issue by yongjhih** [Instabug/Instabug-Android#264]
```
io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'int android.net.NetworkInfo.getType()' on a null object reference
	 at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	 at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	 at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	 at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
	 at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:46)
	 at io.reactivex.Observable.subscribe(Observable.java:12025)
	 at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
	 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	 at java.lang.Thread.run(Thread.java:764)

Caused by: 
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.net.NetworkInfo.getType()' on a null object reference
	 at android.os.Parcel.createException(Parcel.java:1956)
	 at android.os.Parcel.readException(Parcel.java:1918)
	 at android.os.Parcel.readException(Parcel.java:1868)
	 at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1275)
	 at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:1143)
	 at com.instabug.library.c.a.a.b.a(ConnectivityState.java:53) <<<<<<<<<<
	 at com.instabug.library.c.a.b(SessionProfiler.java:137)
	 at com.instabug.library.c.a.c(SessionProfiler.java:32)
	 at com.instabug.library.c.a$3.a(SessionProfiler.java:115)
	 at com.instabug.library.c.a$3.call(SessionProfiler.java:112)
	 at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
	 at io.reactivex.Observable.subscribe(Observable.java:12025)
	 at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
	 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	 at java.lang.Thread.run(Thread.java:764)

Caused by: 
android.os.RemoteException: Remote stack trace:
	at com.android.server.ConnectivityService.getNetworkInfoByWifiUid(ConnectivityService.java:1752)
	at com.android.server.ConnectivityService.getActiveNetworkInfo(ConnectivityService.java:1780)
	at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:85)
	at android.os.Binder.execTransact(Binder.java:731)
```

### Integration

```java
Instabug.Builder(app, getString(R.string.instabug_key))
                .setInvocationEvents(SHAKE)
                .build()
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
```

### SDK Version

```
'com.instabug.library:instabug:8.7.0'
```

### Android Version

Android 9

### Device Model

LGE LG G7 ThinQ (judyln)

**Comment by amrbrkt** [comment]
Thanks @yongjhih  for this report. We will take a look into the cause and come back to you ASAP. Would you please let me know how frequent this crash is?

**Comment by yongjhih** [comment]
Seems it's not often.

**Comment by mzelzoghbi** [comment]
Hi @yongjhih,

First of all, please accept our sincerest apologies for taking some time to come up with a fix for your issue. 

We created a **SNAPSHOT** that should fix the issue, Can you give it a try & let us know if it fixed the issue for you?
```
implementation 'com.instabug.library:instabug:9.0.5.11-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You 😊

**Comment by yongjhih** [comment]
It requires SDK v29, but crashed after upgraded SDK v29 from v28 while triggering instabug reporter.

```
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.flotechnologies, PID: 11789
E AndroidRuntime: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2071)
E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2039)
E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1987)
E AndroidRuntime: 	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
E AndroidRuntime: 	at android.media.projection.MediaProjection.<init>(MediaProjection.java:58)
E AndroidRuntime: 	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:104)
E AndroidRuntime: 	at c.l.f.a0.a.a(ScreenshotManager.java:13)
E AndroidRuntime: 	at c.l.f.a0.a$a.run(ScreenshotManager.java:2)
E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
E AndroidRuntime: 	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:476)
E AndroidRuntime: 	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:994)
E AndroidRuntime:
I System.out: SDK LOG: encryption: ivparameterV6ZdkaPpsCUev6q7 key: Xn2r4u7x!A%D*G-KaPdSgVkYp3s6v8y/
W ActivityTaskManager:   Force finishing activity .../.MainActivity
I WindowManager: WIN DEATH: Window{c631c9d u0 .../.MainActivity}
I Zygote  : Process 11789 exited due to signal 9 (Killed)
W ActivityManager: Scheduling restart of crashed service .../com.instabug.library.analytics.network.InstabugAnalyticsUploaderService in 1000ms
W ActivityManager: Scheduling restart of crashed service .../com.instabug.library.network.worker.uploader.InstabugSessionUploaderService in 11000ms
W ActivityManager: Scheduling restart of crashed service .../com.instabug.chat.network.InstabugMessageUploaderService in 21000ms
I DropBoxManagerService: add tag=platform_stats_bookmark isTagEnabled=true flags=0x2
```


```
| +++ b/android/app/build.gradle
| @@ -42,7 +42,7 @@ play {
|  }
|
|  android {
| -    compileSdkVersion 28
| +    compileSdkVersion 29
|
|      sourceSets {
|          main.java.srcDirs += 'src/main/kotlin'
| @@ -56,7 +56,7 @@ android {
|          // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
|          applicationId "com.flotechnologies"
|          minSdkVersion 19 // requires arm-v7
| -        targetSdkVersion 28
| +        targetSdkVersion 29
|          versionName gitVersionName
|          versionCode gitVersionCode
|          //testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
| @@ -237,6 +237,7 @@ dependencies {
|        transitive = true
|      }
| +    implementation 'com.instabug.library:instabug:9.0.5.11-SNAPSHOT'
|
|      testImplementation 'junit:junit:4.12'
|      //androidTestImplementation 'com.android.support.test:runner:1.0.2'
| diff --git a/android/build.gradle b/android/build.gradle
| index 28ed0854..a8816a72 100644
| --- a/android/build.gradle
| +++ b/android/build.gradle
| @@ -39,7 +39,7 @@ allprojects {
|          maven { url 'https://maven.fabric.io/public' }
|          maven { url "http://embrace-io.bintray.com/mvn-public" }
|          maven { url "https://jitpack.io" }
| -        //maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
| +        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
|      }
|  }
```

**Comment by Muhammadyoussef** [comment]
Hi @yongjhih,

This crash is not caused by Instabug. It seems that you are using media projection without adding `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` in your `AndroidManifest.xml`. You also need to make sure you call `startForeground()` before `getMediaProjection()`. Check this [StackOverflow answer](https://stackoverflow.com/a/57186064) for more details.
