### ISSUE TITLE
StrictMode Violation when initializing the sdk

### ISSUE THREAD

**Issue by marcorighini** [Instabug/Instabug-Android#267]
### Steps to Reproduce the Problem
Initialize Instabug with strict mode enabled
### Expected Behavior
No StrictMode Violation
### Actual Behavior
```
D/StrictMode: StrictMode policy violation; ~duration=1135 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=327687 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
        at java.io.File.exists(File.java:780)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:521)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:477)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:655)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:354)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:164)
        at com.instabug.library.settings.b.<init>(PersistableSettings.java:2)
        at com.instabug.library.settings.b.a(PersistableSettings.java:1)
        at com.instabug.library.settings.SettingsManager.init(SettingsManager.java:2)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:1)
        at com.instabug.library.Instabug$Builder.build(Instabug.java:57)
```
and many other similars for settings.

We are getting also this
```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
        at java.util.zip.Inflater.<init>(Inflater.java:104)
        at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
        at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:821)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
        at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:30)
        at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

### SDK Version
9.0.4

**Comment by amrbrkt** [comment]
Hi @marcorighini, 
Thanks for reporting this. We've created a SNAPSHOT that should fix the issue, would you please try it and tell us if it fixes the issue for you?

Please use: 
`implementation 'com.instabug.library:instabug:9.0.4.2411-SNAPSHOT'`
you will need to add these lines to your app `build.gradle` before your dependencies

```
repositories {
…
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This SNAPSHOT is completely safe to use and has no debug code at all, and the fix planned to be released in the coming releases. 

I'll close this issue for now. If you still facing the problem don't hesitate to reach us here again.
Thank You
