### ISSUE TITLE
App crash because of NPE thrown when calling onExtraScreenshotCaptured()

### ISSUE THREAD

**Issue by FrancoSabadini** [Instabug/Instabug-Android#270]
### Steps to Reproduce the Problem

I received this crash in Crashlytics so not sure how to reproduce it.

Stack trace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.bug.model.a com.instabug.bug.model.a.a(android.net.Uri, com.instabug.library.model.Attachment$Type)' on a null object reference
       at com.instabug.bug.screenshot.a.onExtraScreenshotCaptured(a.java:48)
       at com.instabug.library.screenshot.ExtraScreenshotHelper$3$1.onSuccess(ExtraScreenshotHelper.java:157)
       at com.instabug.library.util.BitmapUtils$3$1.run(BitmapUtils.java:291)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
```

### Expected Behavior

The app doesn't crash.

### Actual Behavior

The app crashes because of the NPE thrown in the Instabug SDK.

### Instabug integration code

```gradle
implementation("com.instabug.library:instabug:8.7.0")
implementation("com.instabug.library:instabug-with-okhttp-interceptor:8.7.0")
```

```kotlin
Instabug.Builder(app, INSTABUG_TOKEN)
                .setInvocationEvents(SHAKE)
                .build()

Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
```

### SDK Version

8.7.0

### Android Version

10

### Device Model

Galaxy S10

**Comment by amrbrkt** [comment]
Thanks @FrancoSabadini for your reports, we do appreciate it very much. 
We will look at this and let you know when it got fixed. However, we kindly advise you to update to our  latest SDK version `9.0.5`
Happy coding 😊

**Comment by FrancoSabadini** [comment]
Thanks @amrbrkt, I have updated to 9.0.5 already but we haven't released the new app version yet. These crashes were reported as part of the last app version which didn't include the new Instabug SDK version.
