### ISSUE TITLE
NPE when calling Uri.getPath()

### ISSUE THREAD

**Issue by FrancoSabadini** [Instabug/Instabug-Android#272]
### Steps to Reproduce the Problem

I received this crash in Crashlytics so not sure how to reproduce it.

Stack trace:

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65697, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/1/content://media/external/images/media/3418/ORIGINAL/NONE/image/jpeg/1043413335 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F3418/ORIGINAL/NONE/image%2Fjpeg/1043413335} }} to activity {app.android/com.instabug.chat.ui.ChatActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5096)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5137)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2146)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
       at com.instabug.chat.ui.b.d.a(d.java:234)
       at com.instabug.chat.ui.b.d.a(d.java:382)
       at com.instabug.chat.ui.b.c.onActivityResult(c.java:268)
       at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
       at com.instabug.chat.ui.ChatActivity.onActivityResult(ChatActivity.java:202)
       at android.app.Activity.dispatchActivityResult(Activity.java:8318)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5089)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5137)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2146)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
```

### Expected Behavior

The Instabug SDK catches this exception so the app doesn't crash.

### Actual Behavior

The app crashes because of the NPE thrown in the Instabug SDK.

### Instabug integration code

```gradle
implementation("com.instabug.library:instabug:8.7.0")
implementation("com.instabug.library:instabug-with-okhttp-interceptor:8.7.0")
```

```kotlin
Instabug.Builder(app, INSTABUG_TOKEN)
                .setInvocationEvents(SHAKE)
                .build()

Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
```

### SDK Version

8.7.0

### Android Version

10

### Device Model

Galaxy S10e

**Comment by mzelzoghbi** [comment]
@FrancoSabadini Thanks for reporting this. This issue has been solved in recent SDK Versions, Can you please upgrade Instabug SDK Version to 9.0.5 and tell us if the issue still persists.

Thank You

**Comment by FrancoSabadini** [comment]
Thanks for the quick answer @mzelzoghbi, I'll update to 9.0.5 and will re-open the issue if it happens again.
