### ISSUE TITLE
Version 9.0.4 crash

### ISSUE THREAD

**Issue by iordachiv** [Instabug/Instabug-Android#278]
Hello, 

Just caught this crash on library version 9.0.4

Fatal Exception: java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
       at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
       at com.instabug.library.internal.storage.cache.db.SQLiteDatabaseWrapper.endTransaction(SQLiteDatabaseWrapper.java:2)
       at com.instabug.survey.cache.a.a(a.java:620)
       at com.instabug.survey.cache.SurveysCacheManager$f.run(SurveysCacheManager.java:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at com.instabug.library.util.threading.b$a.run(b.java:8)
       at java.lang.Thread.run(Thread.java:818)

Device: Lenovo TAB 2 A10-30
Android:6.0.1

Another crash also for version 9.0.4

Caused by java.lang.IllegalArgumentException: Given work is not active: JobWorkItem{id=1 intent=Intent { cmp=hide.my.package/com.instabug.library.network.worker.uploader.InstabugSessionUploaderService } dcount=1}
       at android.app.job.JobParameters.completeWork(JobParameters.java:234)
       at androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete(JobIntentService.java:268)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:394)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

Device: itel A16
Android:8.1.0

**Comment by IslamMohamady** [comment]
Hello Vadim Thanks for reporting this.
We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
``` 
implementation 'com.instabug.library:instabug:9.0.5.12-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.
Thank You 😃
