### ISSUE TITLE
Crash on long press

### ISSUE THREAD

**Issue by adrinieto** [Instabug/Instabug-Android#293]
### Steps to Reproduce the Problem

The app crashes when you perform a long press.

### Expected Behavior

Don't crash.

### Actual Behavior

Crash with this stacktrace:

```
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.instabug.library.invocation.c.a(InvocationUtils.java:1)
        at com.instabug.library.p.a.a(MotionEventRecognizer.java:15)
        at com.instabug.library.p.a.a(MotionEventRecognizer.java:14)
        at com.instabug.library.p.a.a(MotionEventRecognizer.java:3)
        at com.instabug.library.p.a$c.onLongPress(MotionEventRecognizer.java:2)
        at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:868)
        at android.view.GestureDetector.access$300(GestureDetector.java:51)
        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:314)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

### Instabug integration code
```
    private fun setupInstabug() {
        Instabug.Builder(this, getString(R.string.instabug_key))
            .setInvocationEvents(InstabugInvocationEvent.NONE)
            .setTrackingUserStepsState(Feature.State.ENABLED)
            .setInAppMessagingState(Feature.State.ENABLED)
            .build()
        BugReporting.setVideoRecordingFloatingButtonPosition(InstabugVideoRecordingButtonPosition.BOTTOM_LEFT)
    }
```

### SDK Version

9.1.1. On 9.1.0 it works.

### Android Version

API 29

### Device Model

Android emulator

**Comment by Muhammadyoussef** [comment]
Hi @adrinieto, 

I created a SNAPSHOT for you that has the fix. Please give it a try & let me know if you face any issues.

```
implementation 'com.instabug.library:instabug:9.1.1.4-SNAPSHOT'
```

To consume the SNAPSHOT you will need to add the following to your app **`build.gradle`**
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This SNAPSHOT is completely safe to use and has no debug code at all.

**Comment by adrinieto** [comment]
@Muhammadyoussef Thanks for the fast response.
I have tried it and it works. :smile:

**Comment by Muhammadyoussef** [comment]
@adrinieto I'm glade this fixed your issue :)

Just to let you know, this fix made it to a stable release. You can now use the latest version of Instabug instead of relying on this snapshot. To consume the changes please update your dependency as follows

​`implementation 'com.instabug.library:instabug:9.1.2'`
