### ISSUE TITLE
io.reactivex.exceptions.UndeliverableException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/user/UserManager;

### ISSUE THREAD

**Issue by azubchenko** [Instabug/Instabug-Android#307]
### Steps to Reproduce the Problem
Application starts and crashes inside of the Instabug library

### Expected Behavior
No crashes

### Actual Behavior
Application starts and crashes inside of the Instabug library

### Instabug integration code
Where do I take this one?

### SDK Version
9.1.2

### Android Version
OS Level 28, 
### Device Model
samsung SM-G950F, motorola moto x4

### [Optional] Project That Reproduces the Issue
ojilifelab-Android - Live 

Application is built with:
**ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'**

**The log output:**
io.reactivex.exceptions.UndeliverableException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/user/UserManager;
	 at g.a.z.a.b(RxJavaPlugins.java:8)
	 at g.a.x.g.k.run(ScheduledRunnable.java:3)
	 at g.a.x.g.k.call(ScheduledRunnable.java:1)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	 at java.lang.Thread.run(Thread.java:764)

Caused by: 
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/user/UserManager;
	 at com.instabug.chat.synchronization.a.a(NewMessagesHandler.java:50)
	 at com.instabug.chat.synchronization.a.a(NewMessagesHandler.java:1)
	 at com.instabug.chat.synchronization.SynchronizationManager.handleReceivedMessages(SynchronizationManager.java:7)
	 at com.instabug.chat.synchronization.SynchronizationManager.handleSuccessResponse(SynchronizationManager.java:6)
	 at com.instabug.chat.synchronization.SynchronizationManager.access$300(SynchronizationManager.java:1)
	 at com.instabug.chat.synchronization.SynchronizationManager$c.a(SynchronizationManager.java:1)
	 at com.instabug.chat.synchronization.SynchronizationManager$c.onSucceeded(SynchronizationManager.java:1)
	 at com.instabug.chat.network.c.a$d.a(MessagingService.java:5)
	 at com.instabug.chat.network.c.a$d.onNext(MessagingService.java:1)
	 at g.a.x.e.c.x$a.onNext(ObservableSubscribeOn.java:1)
	 at g.a.x.e.c.c$a.onNext(ObservableCreate.java:3)
	 at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:16)
	 at g.a.x.e.c.c.b(ObservableCreate.java:3)
	 at g.a.m.a(Observable.java:82)
	 at g.a.x.e.c.x$b.run(ObservableSubscribeOn.java:1)
	 at g.a.r$a.run(Scheduler.java:2)
	 at g.a.x.g.k.run(ScheduledRunnable.java:2)
	 at g.a.x.g.k.call(ScheduledRunnable.java:1)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	 at java.lang.Thread.run(Thread.java:764)

Caused by: 
java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.user.UserManager" on path: DexPathList[[zip file "/data/app/com.ojimesh-kBj1Q27sE5XbkU6Xtc52fQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.ojimesh-kBj1Q27sE5XbkU6Xtc52fQ==/lib/arm64, /data/app/com.ojimesh-kBj1Q27sE5XbkU6Xtc52fQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	 at com.instabug.chat.synchronization.a.a(NewMessagesHandler.java:50)
	 at com.instabug.chat.synchronization.a.a(NewMessagesHandler.java:1)
	 at com.instabug.chat.synchronization.SynchronizationManager.handleReceivedMessages(SynchronizationManager.java:7)
	 at com.instabug.chat.synchronization.SynchronizationManager.handleSuccessResponse(SynchronizationManager.java:6)
	 at com.instabug.chat.synchronization.SynchronizationManager.access$300(SynchronizationManager.java:1)
	 at com.instabug.chat.synchronization.SynchronizationManager$c.a(SynchronizationManager.java:1)
	 at com.instabug.chat.synchronization.SynchronizationManager$c.onSucceeded(SynchronizationManager.java:1)
	 at com.instabug.chat.network.c.a$d.a(MessagingService.java:5)
	 at com.instabug.chat.network.c.a$d.onNext(MessagingService.java:1)
	 at g.a.x.e.c.x$a.onNext(ObservableSubscribeOn.java:1)
	 at g.a.x.e.c.c$a.onNext(ObservableCreate.java:3)
	 at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:16)
	 at g.a.x.e.c.c.b(ObservableCreate.java:3)
	 at g.a.m.a(Observable.java:82)
	 at g.a.x.e.c.x$b.run(ObservableSubscribeOn.java:1)
	 at g.a.r$a.run(Scheduler.java:2)
	 at g.a.x.g.k.run(ScheduledRunnable.java:2)
	 at g.a.x.g.k.call(ScheduledRunnable.java:1)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	 at java.lang.Thread.run(Thread.java:764)

**Comment by mzelzoghbi** [comment]
Hi @azubchenko Thanks for reporting this. 

This issue has been fixed and released in **9.1.4**. Please give it a try and feel free to reopen this issue if you encountered the same issue again.

Thank You!

**Comment by azubchenko** [comment]
Huh!

Thanks for the quick reply, Mohamed!
