### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by KORuL** [Instabug/Instabug-Android#308]
### Actual Behavior
Crash then start
### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
    implementation 'com.instabug.library:instabug:9.1.5'
### Android Version
all
### Device Model
all
### [Optional] Project That Reproduces the Issue
![image](https://user-images.githubusercontent.com/19871487/82574871-69274a80-9b90-11ea-942f-290dec0d913b.png)

**Comment by mzelzoghbi** [comment]
@KORuL Thanks for reporting this. Can you tell us is this happening on production or on debug builds and if it is reproducible or not from your side?

**Comment by KORuL** [comment]
I can't reproduce this in the debag, it's not from production, please solve this problem as soon as possible!

**Comment by mzelzoghbi** [comment]
We think that this may be a build cache issue. Could you try to make a clean build before trying the apk?
Please, Let me know if this didn't work.

Thanks.

**Comment by KORuL** [comment]
![image](https://user-images.githubusercontent.com/19871487/82739160-13949e80-9d46-11ea-9504-cbee06dbe084.png)

**Comment by KORuL** [comment]
it didn't work.

**Comment by mzelzoghbi** [comment]
@KORuL can you share with us the gradle build tools/wrapper version you are using? And if you have any special configuration added to gradle or your release process?

**Comment by MrJero** [comment]
I have the same issue. I can't reproduce it but I'm receiving this issue through Firebase Crashlytics.

Caused by java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.instabug.library.network.authorization.NetworkOfficer.getClientId() (tried Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId and Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId__)
       at com.instabug.library.network.authorization.NetworkOfficer.getClientId(NetworkOfficer.java)
       at com.instabug.library.network.authorization.NetworkOfficer.a(NetworkOfficer.java:9)
       at com.instabug.library.network.NetworkManager.buildConnection(NetworkManager.java:10)
       at com.instabug.library.network.NetworkManager.connectWithNormalType(NetworkManager.java:2)
       at com.instabug.library.network.NetworkManager.access$100(NetworkManager.java:1)
       at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:20)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
       at io.reactivex.Observable.subscribe(Observable.java:12284)
       at com.instabug.library.analytics.network.a.a(a.java:14)
       at com.instabug.library.analytics.network.InstabugAnalyticsUploaderService.a(InstabugAnalyticsUploaderService.java:4)
       at com.instabug.library.analytics.network.InstabugAnalyticsUploaderService.runBackgroundTask(InstabugAnalyticsUploaderService.java:2)
       at androidx.core.app.InstabugBackgroundService.onHandleWork(InstabugBackgroundService.java:6)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)


my code:

        Instabug.Builder(this, BuildConfig.INSTABUG_KEY)
            .build()
        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)

 implementation 'com.instabug.library:instabug:9.1.5'

**Comment by MahmoudAmin39** [comment]
Hi @KORuL and @MrJero ,
Please accept our apologies for the inconvenience we may have caused. We have been trying to reproduce the issue but unfortunately, we didn't reach anything. 
The only assumption is that your application may be shared via **.apk** from device to the other with different **CPU architectures** (Using sharing apps like shareit,,, etc), which led in missing `.so` libs that we use and depend on it to work.

To fix this you will need to avoid splitting **ABIs** while releasing **aab** by adding this snippet to your app's **build.gradle** file 
```
android {
     .....
    bundle {
        abi {
            enableSplit = false
        }
    }
}
```

Please try this and let us know if the issue still persists.

Thank You!

**Comment by MrJero** [comment]
ok, thanks! I'll keep you posted about this.

**Comment by KORuL** [comment]
![Screenshot_2020-08-04-06-18-42-710_com google android gm](https://user-images.githubusercontent.com/19871487/89249361-a9885780-d61a-11ea-90dc-fcf9654d3e7a.jpg)

**Comment by KORuL** [comment]
Please, help!
![Uploading Screenshot_2020-08-07-07-02-41-414_com.google.android.gm.jpg…]()

**Comment by KORuL** [comment]
I give up using your library. Farewell! I have not yet met such a pohuistic attitude! the library crashes, calls ANR, and you at least have something!

**Comment by Korazy** [comment]
Hey @KORuL 
Please accept my sincerest apologies for these issues you've been facing, we definitely don't want to let you down here. We always want to make sure that you have the best experience possible and will continue on working towards that and on making sure the SDK is in the best stat possible.  

We've been working on creating a snapshot for you with fixes for the crashes you shared. You should be able to find it on this snapshot here: 9.1.6.11-SNAPSHOT

Please note that this snapshot fixes 2 out of the 3 crashes you shared as we would need the full stack trace of the crash in order to get to work on the fix for it, so if you could share it, that would be super helpful!

Would you also be able to tell me if you had a chance to check the reply of my colleague @MahmoudAmin39 [here](https://github.com/Instabug/Instabug-Android/issues/308#issuecomment-658136862) and let me know if that also helps alleviate the issues you were facing?

Thank you in advance and thank you for understanding!
