### ISSUE TITLE
Lot of OutofMemoeryError 

### ISSUE THREAD

**Issue by rajiac2607** [Instabug/Instabug-Android#315]
We are seeing a lot of **OutOfMemoryErrors** happening on production namely on 6.0.1 and 7.0 os versions .
**Instabug SDK version = 9.1.0**
please find the below sample log

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 71196 byte allocation with 41728 free bytes and 40KB until OOM
       at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1091)
       at javax.crypto.Cipher.doFinal(Cipher.java:2056)
       at com.instabug.library.internal.storage.Encryptor.a(Encryptor.java:14)
       at com.instabug.library.internal.storage.Encryptor.c(Encryptor.java:2)
       at com.instabug.library.core.InstabugCore.encrypt(InstabugCore.java:1)
       at com.instabug.library.visualusersteps.g$d$a.onSuccess(VisualUserStepsProvider.java:14)
       at com.instabug.library.util.BitmapUtils$b.run(BitmapUtils.java:11)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at com.instabug.library.util.threading.b$a.run(PriorityThreadFactory.java:8)
       at java.lang.Thread.run(Thread.java:762)

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 1404796 byte allocation with 415680 free bytes and 402KB until OOM
       at com.instabug.library.internal.storage.Encryptor.a(Encryptor.java:9)
       at com.instabug.library.internal.storage.Encryptor.c(Encryptor.java:2)
       at com.instabug.library.core.InstabugCore.encrypt(InstabugCore.java:1)
       at com.instabug.library.visualusersteps.g$d$a.onSuccess(VisualUserStepsProvider.java:14)
       at com.instabug.library.util.BitmapUtils$b.run(BitmapUtils.java:11)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at com.instabug.library.util.threading.b$a.run(PriorityThreadFactory.java:8)
       at java.lang.Thread.run(Thread.java:762)

**Comment by Muhammadyoussef** [comment]
Hi @rajiac2607,

This has gotten fixed on our latest release **9.1.5**. Please feel free to reopen this issue if you encountered this again.

Thank You 😊
