### ISSUE TITLE
Crash : OutOfMemoryError 

### ISSUE THREAD

**Issue by guptakavya** [Instabug/Instabug-Android#319]
### Actual Behavior
Experiencing many Instabug crashes being reported in our Android app due to `OutOfMemoryErrors` in Instabug. 
The crashes seem to be happening in devices with Android 7 and 6 OS. 

We had been using Instabug Version : 8.7.0 but recently updated to the latest version 9.1.6 hoping that would resolve these OutOfMemory crashes?

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 1349951 byte allocation with 978944 free bytes and 956KB until OOM
       at com.instabug.library.internal.storage.Encryptor.a(Encryptor.java:55)
       at com.instabug.library.internal.storage.Encryptor.a(Encryptor.java:32)
       at com.instabug.library.core.InstabugCore.encrypt(InstabugCore.java:167)
       at com.instabug.library.visualusersteps.g$4$1.onSuccess(VisualUserStepsProvider.java:352)
       at com.instabug.library.util.BitmapUtils$2.run(BitmapUtils.java:257)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at com.instabug.library.util.threading.b$1.run(PriorityThreadFactory.java:28)
       at java.lang.Thread.run(Thread.java:761)
```
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 2209516 byte allocation with 1913504 free bytes and 1868KB until OOM
       at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1091)
       at javax.crypto.Cipher.doFinal(Cipher.java:2056)
       at com.instabug.library.internal.storage.Encryptor.a(Encryptor.java:60)
       at com.instabug.library.internal.storage.Encryptor.a(Encryptor.java:32)
       at com.instabug.library.core.InstabugCore.encrypt(InstabugCore.java:167)
       at com.instabug.library.visualusersteps.g$4$1.onSuccess(VisualUserStepsProvider.java:352)
       at com.instabug.library.util.BitmapUtils$2.run(BitmapUtils.java:257)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at com.instabug.library.util.threading.b$1.run(PriorityThreadFactory.java:28)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by MahmoudAmin39** [comment]
Hi @guptakavya , Thanks for reporting this.

We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
``` 
implementation 'com.instabug.library:instabug:9.1.6.2679-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You 😃

**Comment by MahmoudAmin39** [comment]
Hi @guptakavya,
I will be closing this for now. Please re-open it if you still encounter the issue.
Thank you 😊
