### ISSUE TITLE
Crash: Failed to connect to api.instabug.com

### ISSUE THREAD

**Issue by stwonary** [Instabug/Instabug-Android#320]
### Steps to Reproduce the Problem
Start App with Instabug Installed

### Expected Behavior
No crash

### Actual Behavior
Crash on app launched

### SDK Version
9.1.6

### Android Version
OS Level 27

### Device Model
LGE LM-X210(G)

### Crash stack trace caught by Instabug Crash Report 

```
data:text/text;charset=utf-8,
io.reactivex.exceptions.UndeliverableException: java.net.ConnectException: Failed to connect to api.instabug.com/52.5.141.140:443
	 at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	 at io.reactivex.internal.operators.completable.CompletableMergeIterable$MergeCompletableObserver.onError(CompletableMergeIterable.java:124)
	 at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
	 at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onError(CompletableConcatArray.java:60)
	 at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onError(CompletableConcatArray.java:60)
	 at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:96)
	 at io.reactivex.internal.operators.observable.ObservableIgnoreElementsCompletable$IgnoreObservable.onError(ObservableIgnoreElementsCompletable.java:61)
	 at io.reactivex.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.onError(ObservableRetryPredicate.java:89)
	 at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:85)
	 at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
	 at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:104)
	 at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	 at io.reactivex.Observable.subscribe(Observable.java:12025)
	 at io.reactivex.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.subscribeNext(ObservableRetryPredicate.java:111)
	 at io.reactivex.internal.operators.observable.ObservableRetryPredicate.subscribeActual(ObservableRetryPredicate.java:41)
	 at io.reactivex.Observable.subscribe(Observable.java:12025)
	 at io.reactivex.internal.operators.observable.ObservableIgnoreElementsCompletable.subscribeActual(ObservableIgnoreElementsCompletable.java:31)
	 at io.reactivex.Completable.subscribe(Completable.java:1919)
	 at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
	 at io.reactivex.Completable.subscribe(Completable.java:1919)
	 at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89)
	 at io.reactivex.internal.operators.completable.CompletableConcatArray.subscribeActual(CompletableConcatArray.java:33)
	 at io.reactivex.Completable.subscribe(Completable.java:1919)
	 at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89)
	 at io.reactivex.internal.operators.completable.CompletableConcatArray.subscribeActual(CompletableConcatArray.java:33)
	 at io.reactivex.Completable.subscribe(Completable.java:1919)
	 at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
	 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	 at java.lang.Thread.run(Thread.java:764)

Caused by: 
java.net.ConnectException: Failed to connect to api.instabug.com/52.5.141.140:443
	 at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:150)
	 at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:119)
	 at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	 at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	 at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	 at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:314)
	 at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:257)
	 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:478)
	 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:140)
	 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:271)
	 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
	 at com.instabug.library.network.NetworkManager.connectWithNormalType(NetworkManager.java:8)
	 at com.instabug.library.network.NetworkManager.access$100(NetworkManager.java:1)
	 at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:20)
	 at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	 at io.reactivex.Observable.subscribe(Observable.java:12025)
	 at io.reactivex.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.subscribeNext(ObservableRetryPredicate.java:111)
	 at io.reactivex.internal.operators.observable.ObservableRetryPredicate.subscribeActual(ObservableRetryPredicate.java:41)
	 at io.reactivex.Observable.subscribe(Observable.java:12025)
	 at io.reactivex.internal.operators.observable.ObservableIgnoreElementsCompletable.subscribeActual(ObservableIgnoreElementsCompletable.java:31)
	 at io.reactivex.Completable.subscribe(Completable.java:1919)
	 at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
	 at io.reactivex.Completable.subscribe(Completable.java:1919)
	 at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89)
	 at io.reactivex.internal.operators.completable.CompletableConcatArray.subscribeActual(CompletableConcatArray.java:33)
	 at io.reactivex.Completable.subscribe(Completable.java:1919)
	 at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89)
	 at io.reactivex.internal.operators.completable.CompletableConcatArray.subscribeActual(CompletableConcatArray.java:33)
	 at io.reactivex.Completable.subscribe(Completable.java:1919)
	 at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
	 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	 at java.lang.Thread.run(Thread.java:764)



```

**Comment by MahmoudAmin39** [comment]
Hi @simon-twonary ,
Thank you for reporting this issue. Please accept our apologies for facing it.

Can you please clarify the following points so we can investigate and debug the issue and to make sure you won't face it again in the future:
- Was this an error on logcat or this caused the app to crash?
- If possible, please share the Crash Url.
- Was this a one time incident or it was happening consistently on the device you specified?
- If it was consistent, please clarify if you are using any proxy or an AdBlocker on this device.

Thanks in advance

**Comment by simon-twonary** [comment]
- It's happening on production with real users
- How can I share it in private with you?
- It seems to be random. I see normal user activity before the crash.
- No idea if the client is using a VPN or any proxy

<img width="1595" alt="Screen Shot 2020-07-15 at 09 57 41" src="https://user-images.githubusercontent.com/59780143/87554710-776e8000-c682-11ea-9cda-b1f4c51bfe4f.png">

**Comment by MahmoudAmin39** [comment]
Thank you @simon-twonary for your quick reply 
For sharing the crash Url, please report the crash with the Instabug support team from Instabug's dashboard. 🙏

**Comment by stwonary** [comment]
Will try v9.1.7. Will reopen if still happening. Thanks
