### ISSUE TITLE
SQLiteBlobTooBigException at com.instabug.crash.b.a.a(CrashReportsDbHelper.java:45)

### ISSUE THREAD

**Issue by rajiac2607** [Instabug/Instabug-Android#321]
I am having the following exception in production

instabug version - 9.1.5
on Galaxy A50 on android OS 10, just after app launch

Fatal Exception: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1196)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:173)
       at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:134)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
       at com.instabug.crash.b.a.a(CrashReportsDbHelper.java:45)
       at com.instabug.crash.CrashPlugin$b.run(CrashPlugin.java:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.instabug.library.util.threading.b$a.run(PriorityThreadFactory.java:8)
       at java.lang.Thread.run(Thread.java:919)

**Comment by Muhammadyoussef** [comment]
Hi @rajiac2607,

That is quite unfortunate to hear, and I highly apologize for any sort of inconvenience you are running into. I created a snapshot for you that has the fix; please give it a try and let me know if you still face any issues.

```
implementation 'com.instabug.library:instabug:10.0.0.3169-SNAPSHOT'
```

To consume the snapshot you will need to add the following to your app `build.gradle` as well
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This snapshot is completely safe to use and has no debug code at all.
