### ISSUE TITLE
Fatal Exception: io.reactivex.exceptions.UndeliverableException: java.lang.UnsatisfiedLinkError: Native method not found: com.instabug.library.network.authorization.NetworkOfficer.getClientId:()Ljava/lang/String;

### ISSUE THREAD

**Issue by mahmoudElfeel67** [Instabug/Instabug-Android#324]
### Steps to Reproduce the Problem
I dont know
but here is the stack trace
`Fatal Exception: io.reactivex.exceptions.UndeliverableException: java.lang.UnsatisfiedLinkError: Native method not found: com.instabug.library.network.authorization.NetworkOfficer.getClientId:()Ljava/lang/String;
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)`

### Expected Behavior
Not to crash

### Actual Behavior
Crashes
### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
 implementation 'com.instabug.library:instabug:9.1.5'
    implementation 'com.instabug.library:instabug-with-okhttp-interceptor:8.7.2.7-SNAPSHOT'
### Android Version
 new Instabug.Builder(this, getString(R.string.instabug_app_token))
                    .setInvocationEvents(InstabugInvocationEvent.SHAKE)
                    .setReproStepsState(State.ENABLED_WITH_NO_SCREENSHOTS)
                    .build();

            Instabug.setLocale(new Locale("ar"));
            BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK);
### Device Model
70%
Android 4
30%
Android 5

**Comment by mzelzoghbi** [comment]
Hi @mahmoudElfeel67 , Thanks for reporting this. 
We are already aware of this issue, you can check this reply on how to avoid this issue from happening https://github.com/Instabug/Instabug-Android/issues/317#issuecomment-657295094 
Also, we always recommend using the same SDK version for the interceptor and the Core SDK. So both of them should be `9.1.5` or our latest `9.1.6`.

Please feel free to reach out again if the issue still happens after applying the above steps.

Thanks.

**Comment by mahmoudElfeel67** [comment]
@mzelzoghbi  okay thank you 

for the old implementation we use it because minSdkVersion 17
we use old okhttp that support these version com.squareup.okhttp3:okhttp:3.12.2
