### ISSUE TITLE
Crash NullPointException com.instabug.chat package

### ISSUE THREAD

**Issue by yunyh** [Instabug/Instabug-Android#327]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
       at o.biO.ǃ(:169)
       at o.biO.Ι(:58)
       at com.instabug.chat.ChatPlugin$ı.run(:1)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7458)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

### Steps to Reproduce the Problem
- None

### Expected Behavior
- None

### Actual Behavior
- None

### SDK Version
- 9.1.6

### Android Version
- All of support version.

### Device Model
-

**Comment by MahmoudAmin39** [comment]
Hi @yunyh, Thanks for reporting this.
We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
```
implementation 'com.instabug.library:instabug:9.1.6.2731-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You :smiley:

**Comment by yunyh** [comment]
Hello @MahmoudAmin39

Not reproduce crash used snapshot version.

Thank you.
