### ISSUE TITLE
File access on Schedulers.computation()

### ISSUE THREAD

**Issue by danh32** [Instabug/Instabug-Android#332]
We recently enabled StrictMode for RxJava's `Schedulers.computation()` threads - we had previously had issues with accidentally doing network or file system work on this limited threadpool, and wanted a way to detect this in the future. We noticed that Instabug's SDK is occasionally violating these StrictMode rules by calling `File.getTotalSpace()` on the computation scheduler. Here's the full stack trace:

```
2020-09-08 13:59:37.309 22692-22818/com.robinhood.android.dev D/StrictMode: StrictMode policy violation: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getSpace(UnixFileSystem.java:361)
        at java.io.File.getTotalSpace(File.java:1783)
        at com.instabug.library.util.DeviceStateProvider.getUsedStorage(DeviceStateProvider.java:2)
        at com.instabug.library.m.a.a(SessionProfiler.java:35)
        at com.instabug.library.m.a.a(SessionProfiler.java:1)
        at com.instabug.library.m.a$b.a(SessionProfiler.java:1)
        at com.instabug.library.m.a$b.accept(SessionProfiler.java:1)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
        at io.reactivex.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:82)
        at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:38)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.robinhood.android.util.RxSchedulerMonitor$ThreadFactoryWrapper$newThread$1.run(RxSchedulerMonitor.kt:48)
        at java.lang.Thread.run(Thread.java:764)
```

It would be great if the Instabug SDK could move this call to be on `Schedulers.io()` instead, since that's an unbounded threadpool that works better for I/O based work.

### Steps to Reproduce the Problem:

Enable StrictMode for all Schedulers.computation() generated threads. We did this to ensure StrictMode is set up for all threads generated by the computation scheduler:

```
object RxSchedulerMonitor {

    fun init() {
        val priority: Int = max(
            Thread.MIN_PRIORITY, min(
                Thread.MAX_PRIORITY,
                Integer.getInteger("rx2.computation-priority", Thread.NORM_PRIORITY)!!
            )
        )

        val originalFactory = RxThreadFactory("RxComputationThreadPool", priority, true)
        val wrappedFactory = ThreadFactoryWrapper(originalFactory)
        RxJavaPlugins.setInitComputationSchedulerHandler {
            ComputationScheduler(wrappedFactory)
        }
    }

    private class ThreadFactoryWrapper(private val delegate: ThreadFactory) : ThreadFactory {

        override fun newThread(r: Runnable): Thread {
            return delegate.newThread {
                // set up strictmode
                StrictMode.setThreadPolicy(StrictMode.ThreadPolicy.Builder()
                    .detectAll()
                    .penaltyLog()
                    .penaltyDeath()
                    .build()
                )

                // run original runnable
                r.run()
            }
        }
    }
}
``` 

### Expected Behavior

Schedulers.computation() should not be used for general I/O work (like reading from the file system).

### Actual Behavior

Schedulers.computation() is being used to do File size reads, which is violating our StrictMode rules.

### Instabug integration code
```
        Instabug.Builder(app, "abc123")
            .setInvocationEvents(InstabugInvocationEvent.SHAKE)
            .build()
        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
        Instabug.setSessionProfilerState(Feature.State.ENABLED)
        Instabug.setPrimaryColor(0xFF00C805.toInt()) // Mobius Prime 03
        Instabug.setReproStepsState(State.ENABLED_WITH_NO_SCREENSHOTS)
        Instabug.setUserAttribute(KEY_BACKEND, backendName)
        apolloNamespace?.let { Instabug.setUserAttribute(KEY_APOLLO_NAMESPACE, it) }
        CrashReporting.setState(Feature.State.DISABLED)
        Surveys.setAutoShowingEnabled(false)
        BugReporting.setOptions(Option.EMAIL_FIELD_OPTIONAL)
        BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK)
        BugReporting.setShakingThreshold(250) // default is 650
        Replies.setState(Feature.State.DISABLED)
```
### SDK Version
9.1.6

### Android Version
all

### Device Model
all

**Comment by danh32** [comment]
We're also seeing:

**Comment by amrbrkt** [comment]
@danh32 
I highly recommend updating to our latest version `10.2.0`, this should be fixed. 
I'm closing the issue, but please feel free to reopen it if you still facing the same warnings.

**Comment by danh32** [comment]
Thank you! We will update soon!
