### ISSUE TITLE
NullPointerException on java.util.List com.instabug.library.internal.storage.cache.InMemoryCache.getValues()

### ISSUE THREAD

**Issue by IgorMaineti** [Instabug/Instabug-Android#336]
### Steps to Reproduce the Problem

No specific steps to reproduce this issue.

### Expected Behavior

The app shouldn't crash.

### Actual Behavior

The app is crashing with the following stack trace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.instabug.library.internal.storage.cache.InMemoryCache.getValues()' on a null object reference
       at com.instabug.survey.cache.SurveysCacheManager.migrateOldCacheToDb(SurveysCacheManager.java:4)
       at com.instabug.survey.SurveyPlugin$e.run(SurveyPlugin.java:9)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.instabug.library.util.threading.b$a.run(b.java:8)
       at java.lang.Thread.run(Thread.java:919)
```

### Instabug integration code
```
        Instabug.Builder(this, INSTABUG_APP_TOKEN)
            .setInvocationEvents(InstabugInvocationEvent.NONE)
            .build(Feature.State.DISABLED)

        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
```

### SDK Version

9.1.7

### Android Version

10

### Device Model

 Brand: motorola
Model: Motorola one
Orientation: Portrait

**Comment by MahmoudAmin39** [comment]
Hi @IgorMaineti,
I will be closing this issue for duplication with [this one](https://github.com/Instabug/Instabug-Android/issues/335).
Thanks for understanding 🙏
