### ISSUE TITLE
IllegalStateException on instabug sqlite database when running tests

### ISSUE THREAD

**Issue by carstenhag** [Instabug/Instabug-Android#340]
### Steps to Reproduce the Problem
1. Update from Instabug 9.1.8 to 10.0.0 as dependency
2. Run unit tests (some with robolectric)

### Expected Behavior
No error when running unit tests or robolectric tests. On 9.1.8 there were no exceptions shown, so this was introduced with 10.0.0.

### Actual Behavior
This exception gets thrown like 50 times when I run one test class... Not sure how many hundreds of times when I run all unit tests. Seems to affect mostly tests where we use `@RunWith(RobolectricTestRunner::class)`, but not on all. Similar to #305 basically. Some of the tests where exceptions get thrown actually call something Instabug-related (`Instabug.logUserEvent`), but some don't.

`java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.`

<details>
<summary>logcat of the error</summary>

```
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:90)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:76)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:42)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.Completable.subscribe(Completable.java:2295)
	at com.instabug.library.i.a.uncaughtException(InstabugUncaughtExceptionHandler.java:10)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:90)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:76)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:42)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.Completable.subscribe(Completable.java:2295)
	at com.instabug.library.i.a.uncaughtException(InstabugUncaughtExceptionHandler.java:10)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:90)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:76)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:42)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.Completable.subscribe(Completable.java:2295)
	at com.instabug.library.i.a.uncaughtException(InstabugUncaughtExceptionHandler.java:10)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1959)
Caused by: java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
	at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:566)
	at com.instabug.library.internal.storage.cache.db.SQLiteDatabaseWrapper.endTransaction(SQLiteDatabaseWrapper.java:2)
	at com.instabug.library.m.c$d.subscribe(SessionsLocalDataSource.java:15)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)
	... 79 more
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:90)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:76)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:42)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.Completable.subscribe(Completable.java:2295)
	at com.instabug.library.i.a.uncaughtException(InstabugUncaughtExceptionHandler.java:10)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:90)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:76)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:42)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.Completable.subscribe(Completable.java:2295)
	at com.instabug.library.i.a.uncaughtException(InstabugUncaughtExceptionHandler.java:10)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:90)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:76)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:42)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.Completable.subscribe(Completable.java:2295)
	at com.instabug.library.i.a.uncaughtException(InstabugUncaughtExceptionHandler.java:10)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:90)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:76)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:42)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.Completable.subscribe(Completable.java:2295)
	at com.instabug.library.i.a.uncaughtException(InstabugUncaughtExceptionHandler.java:10)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:90)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:76)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:42)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.Completable.subscribe(Completable.java:2295)
	at com.instabug.library.i.a.uncaughtException(InstabugUncaughtExceptionHandler.java:10)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:90)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:76)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:42)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.Completable.subscribe(Completable.java:2295)
	at com.instabug.library.i.a.uncaughtException(InstabugUncaughtExceptionHandler.java:10)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:90)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:76)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:42)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.Completable.subscribe(Completable.java:2295)
	at com.instabug.library.i.a.uncaughtException(InstabugUncaughtExceptionHandler.java:10)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1959)
Caused by: java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
	at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:566)
	at com.instabug.library.internal.storage.cache.db.SQLiteDatabaseWrapper.endTransaction(SQLiteDatabaseWrapper.java:2)
	at com.instabug.library.m.c$d.subscribe(SessionsLocalDataSource.java:15)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)
	... 79 more
```

</details>

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
target & compile sdk: 29
### Android Version
not relevant
### Device Model
not relevant

**Comment by Muhammadyoussef** [comment]
Hi @carstenhag,

That is quite unfortunate to hear, and I highly apologize for any sort of inconvenience you are running into. I created a snapshot for you that has the fix; please give it a try and let me know if you still face any issues.

```
implementation 'com.instabug.library:instabug:10.0.0.0048-SNAPSHOT'
```

To consume the snapshot you will need to add the following to your app `build.gradle` as well
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This snapshot is completely safe to use and has no debug code at all.

**Comment by carstenhag** [comment]
Hello there, just tried it out. Not getting exceptions anymore, just this warning. But I'm totally fine with that ;)

```
Oct 08, 2020 7:02:02 PM com.almworks.sqlite4java.Internal log
WARNING: [sqlite] SQLite: cannot set library path, library already loaded
```

**Comment by Muhammadyoussef** [comment]
@carstenhag Awesome! For now, you can watch our [releases page](https://github.com/instabug/instabug-android/releases) to get notified whenever this fix makes it to a stable release. **ETA:** Within the coming few weeks.

And by the way, the warning message is most probably [caused by Robolectric](https://github.com/robolectric/robolectric/issues/958#issuecomment-35290584)

Thanks for understanding 😊
