### ISSUE TITLE
Crash "Foreign Key Constraints cannot be enabled or disabled while there are transactions in progress."

### ISSUE THREAD

**Issue by dung90it** [Instabug/Instabug-Android#349]
### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
10.0.1

### Android Version
Android 10, API 29

### Device Model
Samsung s10 plus

java.lang.IllegalStateException: Foreign Key Constraints cannot be enabled or disabled while there are transactions in progress.  Finish all transactions and release all active database connections first.
        at android.database.sqlite.SQLiteConnectionPool.reconfigure(SQLiteConnectionPool.java:516)
        at android.database.sqlite.SQLiteDatabase.setForeignKeyConstraintsEnabled(SQLiteDatabase.java:2510)
        at com.instabug.library.internal.storage.cache.db.a.onConfigure(InstabugDbHelper.java:3)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:462)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:391)
        at com.instabug.library.internal.storage.cache.db.SQLiteDatabaseWrapper.open(SQLiteDatabaseWrapper.java:4)
        at com.instabug.library.internal.storage.cache.db.DatabaseManager.openDatabase(DatabaseManager.java:1)
        at com.instabug.library.internal.storage.cache.user.a.a(UserDbHelper.java:38)
        at com.instabug.library.internal.storage.cache.user.UserCacheManager.insertIfNotExists(UserCacheManager.java:2)
        at com.instabug.library.user.b$c.run(UserManager.java:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.instabug.library.util.threading.b$a.run(PriorityThreadFactory.java:8)
        at java.lang.Thread.run(Thread.java:919)

**Comment by Muhammadyoussef** [comment]
Hi @dung90it ,

I highly apologize for any sort of inconvenience you are running into, and I assure you that this is taking priority. 

I noticed that you left the **"Steps to Reproduce the Problem"** section blank. Would you be able provide some steps to reproduce this issue? 🙏

**Comment by amrbrkt** [comment]
Hi @dung90it, 
I'm closing this issue, please don't hesitate to reopen and help us to reproduce it if you still facing it.
