### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteBlobTooBigException: CrashReportsDbHelper:45

### ISSUE THREAD

**Issue by rajiac2607** [Instabug/Instabug-Android#355]
Fatal Exception: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=9
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1060)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:149)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:259)
       at com.instabug.crash.b.a.a(CrashReportsDbHelper.java:45)
       at com.instabug.crash.CrashPlugin$b.run(CrashPlugin.java:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.instabug.library.util.threading.b$a.run(PriorityThreadFactory.java:8)
       at java.lang.Thread.run(Thread.java:764)

### Instabug integration code

`new Instabug.Builder(this, AppConstants.INSTABUG_APP_TOKEN)
                        .setInvocationEvents(InstabugInvocationEvent.NONE)
                        .build();`

 SDK Version : 9.1.5

 Android Version: 9 and 10

 Device Model:   HUAWEI Y5 2019 and  Galaxy Note8,Galaxy A8+(2018) etc

**Comment by mzelzoghbi** [comment]
Hi @rajiac2607,
This has been fixed in 10.1.1, please upgrade and feel free to reach out again if you faced any further issues. 

Thank you!
