### ISSUE TITLE
UnsatisfiedLinkError: NDKCrashManagerImpl.unregisterNDKCrashHandler()

### ISSUE THREAD

**Issue by micotom** [Instabug/Instabug-Android#377]
We are getting `UnsatisfiedLinkError`s via the ndk crash library after the application was opened via push notifications (Braze SDK) on the latest 10.5.0 version.

### Steps to Reproduce the Problem
- Opening the application via push notification

### Expected Behavior
- Does not crash

### Actual Behavior
- Is crashing

Stacktrace
```
java.lang.UnsatisfiedLinkError: No implementation found for void com.instabug.ndkcrash.NDKCrashManagerImpl.unregisterNDKCrashHandler() (tried Java_com_instabug_ndkcrash_NDKCrashManagerImpl_unregisterNDKCrashHandler and Java_com_instabug_ndkcrash_NDKCrashManagerImpl_unregisterNDKCrashHandler__)
    at com.instabug.ndkcrash.NDKCrashManagerImpl.unregisterNDKCrashHandler(NDKCrashManagerImpl.java)
    at com.instabug.ndkcrash.NDKCrashManagerImpl.a(NDKCrashManagerImpl.java:7)
    at com.instabug.ndkcrash.NDKCrashPlugin.handleSDKState(NDKCrashPlugin.java:4)
    at com.instabug.ndkcrash.NDKCrashPlugin.start(NDKCrashPlugin.java:1)
    at com.instabug.library.core.plugin.Plugin.startIfPossible(Plugin.java:2)
    at com.instabug.library.core.plugin.a.b(PluginsManager.java:5)
    at com.instabug.library.c.k(InstabugDelegate.java:5)
    at com.instabug.library.c.j(InstabugDelegate.java:4)
    at com.instabug.library.Instabug$Builder$a.run(Instabug.java:3)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at com.instabug.library.util.threading.b$a.run(PriorityThreadFactory.java:5)
    at java.lang.Thread.run(Thread.java:923)
```

### SDK Version
```
compileSdkVersion = 30
minSdkVersion = 21
targetSdkVersion = 30
buildToolsVersion = 29.0.2
```

### Instabug integration code
Gradle
```    
allProjects {
   ext {
      instabugVersion = '10.5.0'
   }
}
...
implementation "com.instabug.library:instabug:$instabugVersion"
implementation "com.instabug.library:instabug-ndk-crash:$instabugVersion"
```

Code
```
Instabug.Builder(application, application.getString(R.string.instabug_beta_id))
            .setInvocationEvents(InstabugInvocationEvent.SHAKE)
            .build()

        Instabug.setLocale(Locale.GERMAN)
        CrashReporting.setState(Feature.State.DISABLED)
        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
        Replies.setState(Feature.State.DISABLED)
        BugReporting.setShakingThreshold(900)

        BugReporting.setReportTypes(
            BugReporting.ReportType.BUG,
            BugReporting.ReportType.FEEDBACK
        )

        Instabug.setColorTheme(com.instabug.library.InstabugColorTheme.InstabugColorThemeDark)
        Instabug.setPrimaryColor(Color.WHITE)

        val textPlaceHolders = InstabugCustomTextPlaceHolder()
        textPlaceHolders.set(
            InstabugCustomTextPlaceHolder.Key.INVOCATION_HEADER,
            application.getString(R.string.instabug_invocation_dialog_title)
        )

        textPlaceHolders.set(
            InstabugCustomTextPlaceHolder.Key.REPORT_BUG,
            application.getString(R.string.instabug_report_bug)
        )

        textPlaceHolders.set(
            InstabugCustomTextPlaceHolder.Key.COMMENT_FIELD_HINT_FOR_BUG_REPORT,
            application.getString(R.string.instabug_report_bug_hint)
        )

        textPlaceHolders.set(
            InstabugCustomTextPlaceHolder.Key.REPORT_FEEDBACK,
            application.getString(R.string.instabug_report_feedback)
        )

        textPlaceHolders.set(
            InstabugCustomTextPlaceHolder.Key.COMMENT_FIELD_HINT_FOR_FEEDBACK,
            application.getString(R.string.instabug_report_feedback_hint)
        )
        Instabug.setCustomTextPlaceHolders(textPlaceHolders)

        Instabug.onReportSubmitHandler {
            // ...
        }
```

R8
`-keep class com.instabug.** {*;}`

### Android Version
Any (reports from 6.0.1 up to 11)

### Device Model
Any

**Comment by yaraabdelhakiim** [comment]
Thanks for reaching out @micotom, we'll look into it.

**Comment by yaraabdelhakiim** [comment]
Hi @micotom, 
The fix for this will be included in the next release, but in the meanwhile, we have created a snapshot containing it.
you can use it by adding this line in your app's `build.gradle` file :

`implementation 'com.instabug.library:instabug:10.5.0.3222-SNAPSHOT`

**Comment by micotom** [comment]
Thanks for the quick fix - will add that to our next release and inform you if it is solved on our end.

**Comment by micotom** [comment]
The issue was obviously fixed in the snapshot version - is the solution integrated in one of the releases from 10.6.0? In that case I would close the the report here and we could switch to an official version.

**Comment by IslamMohamady** [comment]
Hi @micotom
I will close this issue now as there are no updates in awhile. Feel free to reopen the issue if it is still exists
