### ISSUE TITLE
TransactionTooLargeException when opening InstabugDialogActivity

### ISSUE THREAD

**Issue by sdsantos** [Instabug/Instabug-Android#394]
### Steps to Reproduce the Problem

I haven't been able to reproduce the issue myself, but at least 81 users have triggered this crash 700 times. All occurrences seem to have been triggered by opening InstabugDialogActivity, both from our Instabug logs, as from our Crashlytics logs.

### Expected Behavior

Instabug components should not crash. At the very least fail gracefully.

### Actual Behavior

The app is crashing for our users.

### Instabug integration code

```
        Instabug.Builder(app, app.getString(R.string.instabug_app_token))
            .setInvocationEvents(InstabugInvocationEvent.SHAKE)
            .setReproStepsState(State.ENABLED_WITH_NO_SCREENSHOTS)
            .build()
        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
        BugReporting.setShakingThreshold(300)
        BugReporting.setOptions(Option.COMMENT_FIELD_REQUIRED)
```

### SDK Version

10.7.2

### Android Version

API 24-28

### Device Model

Too varied to mention.

**Comment by IslamMohamady** [comment]
Hi @sdsantos,

Thank you for reporting this. Could you please provide the full crash stacktrace?

**Comment by sdsantos** [comment]
Here's the stacktrace, but it's a generic one:

```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 520600 bytes
	 at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3865)
	 at android.os.Handler.handleCallback(Handler.java:836)
	 at android.os.Handler.dispatchMessage(Handler.java:103)
	 at android.os.Looper.loop(Looper.java:203)
	 at android.app.ActivityThread.main(ActivityThread.java:6253)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

Caused by:
android.os.TransactionTooLargeException: data parcel size 520600 bytes
	 at android.os.BinderProxy.transactNative(Native Method)
	 at android.os.BinderProxy.transact(Binder.java:622)
	 at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3708)
	 at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3857)
	 at android.os.Handler.handleCallback(Handler.java:836)
	 at android.os.Handler.dispatchMessage(Handler.java:103)
	 at android.os.Looper.loop(Looper.java:203)
	 at android.app.ActivityThread.main(ActivityThread.java:6253)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

The actual bytes amount varies from crash to crash.

**Comment by IslamMohamady** [comment]
Do you use parcels to save activity state when stopping it?

**Comment by sdsantos** [comment]
We don't have any explicit activity save being saved, just Android's default behaviour for it.

**Comment by IslamMohamady** [comment]
Can you try to reproduce it on our sample app?

**Comment by sdsantos** [comment]
We can't even reproduce it in our own app, we only have the crash reports. 

What kind of data is transacted to the `InstabugDialogActivity`? What state could lead that data to grow?

**Comment by IslamMohamady** [comment]
Can you share the categories you have for bug reporting?

**Comment by sdsantos** [comment]
Here they are:

![Screenshot 2021-08-10 at 12 31 04](https://user-images.githubusercontent.com/106415/128859554-0df65560-1414-4f25-b0a5-134a01d0516b.png)

**Comment by IslamMohamady** [comment]
And what are the subcategories?

**Comment by sdsantos** [comment]
No subcategories.

**Comment by IslamMohamady** [comment]
Can you report this issue using the chat bubble on your dashboard?
