### ISSUE TITLE
Crash due to java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by samuelcai-chancetop** [Instabug/Instabug-Android#399]
### Steps to Reproduce the Problem
Use app for some time

### Expected Behavior
No crash

### Actual Behavior
Crash after some steps (maybe 100 steps?)
I can't reproduce this every time, one time I used this app for some time, but no crash.

### Instabug integration code
"instabug-reactnative": "10.8.1" (but I change the android dependency to 10.8.2 to be consistent with interceptor version)
implementation 'com.instabug.library:instabug-apm-okhttp-interceptor:10.8.2'

### SDK Version
10.8.2

### Android Version
11

### Device Model
Galaxy Note10, Galaxy S10e, Pixel 3 XL

### Stack Track
1. 
java.lang.ArrayIndexOutOfBoundsException: length=100; index=100
        at java.util.ArrayList.add(ArrayList.java:468)
        at com.instabug.library.tracking.f$b.run(InstabugTrackingStepsProvider.java:13)
        at com.instabug.library.util.threading.PoolProvider$b.run(PoolProvider.java:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.instabug.library.util.threading.b$a.run(PriorityThreadFactory.java:5)
        at java.lang.Thread.run(Thread.java:923)

2. 
java.lang.ArrayIndexOutOfBoundsException: src.length=100 srcPos=1 dst.length=100 dstPos=0 length=100
        at java.lang.System.arraycopy(System.java:-2)
        at java.util.ArrayList.remove(ArrayList.java:510)
        at com.instabug.library.tracking.f.f(InstabugTrackingStepsProvider.java:2)
        at com.instabug.library.tracking.f.a(InstabugTrackingStepsProvider.java:2)
        at com.instabug.library.tracking.f$b.run(InstabugTrackingStepsProvider.java:12)
        at com.instabug.library.util.threading.PoolProvider$b.run(PoolProvider.java:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.instabug.library.util.threading.b$a.run(PriorityThreadFactory.java:5)
        at java.lang.Thread.run(Thread.java:923)

**Comment by samuelcai-chancetop** [comment]
Btw, The 10.8.x versions are not in public releases any more, is there any serious problem? https://github.com/Instabug/Instabug-Android/releases

**Comment by samuelcai-chancetop** [comment]
I added more times, although we can receive this exception, but sometimes no crash. So maybe this just an exception caught by our crash reporter (Bugsnag), but please check it.

**Comment by amrbrkt** [comment]
@samuelcai-chancetop 
Thanks for sharing this, we will check it and get back to you as soon as possible. 
In the meanwhile, would you let us know those shared logs belong to which version?

**Comment by samuelcai-chancetop** [comment]
@amrbrkt Those logs belong to 10.8.2. We used 10.4.3.4 before and did not have this error.

**Comment by amrbrkt** [comment]
@samuelcai-chancetop 
Thanks for your reply, we are currently working on a fix for this, we will share a snapshot with you as soon as we are done.

**Comment by samuelcai-chancetop** [comment]
@amrbrkt 
The support told me that there was a snapshot version 10.9.0.3438-INSD-5944, I tried but still seeing same errors. It's happening on all our Android devices, like Android 9, 11, Samsung Galaxy 9, Xiaomi etc.

**Comment by amrbrkt** [comment]
@samuelcai-chancetop 
Sorry for the inconvenience, we are checking with the support team and will get back to you sooner.

**Comment by amrbrkt** [comment]
@samuelcai-chancetop 
I'm closing this issue here, and we are keeping the support channel open until it be solved.
