### ISSUE TITLE
Announcment sql database crash

### ISSUE THREAD

**Issue by mahmoudElfeel67** [Instabug/Instabug-Android#401]
### Steps to Reproduce the Problem
dont know

### Expected Behavior
not to crash

### Actual Behavior
crashes

### Instabug integration code
        Instabug.Builder(application, application.getString(R.string.instabug_app_token))
            .setInvocationEvents(InstabugInvocationEvent.SHAKE)
            .setReproStepsState(State.ENABLED)
            .build()
        //CrashReporting.setState(Feature.State.DISABLED)
        Instabug.setLocale(Locale("ar"))
        BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK)
        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
        Surveys.setState(Feature.State.ENABLED)

### SDK Version
10.9.0

### Android Version
4.4.2 

### Device Model
 TAB 2 A7-30TC  LENOVO
 
### [Optional] Project That Reproduces the Issue
`Fatal Exception: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=4 (# cursors opened by this proc=4)
       at android.database.CursorWindow.<init>(CursorWindow.java:104)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:221)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:154)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:148)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
       at com.instabug.survey.announcements.cache.b.d(b.java:61)
       at com.instabug.survey.announcements.cache.AnnouncementCacheManager.getReadyToBeSend(AnnouncementCacheManager.java:1)
       at com.instabug.survey.SurveyPlugin$d.run(SurveyPlugin.java:1)
       at com.instabug.library.util.threading.PoolProvider$b.run(PoolProvider.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.instabug.library.util.threading.a$a.run(a.java:8)
       at java.lang.Thread.run(Thread.java:841)`

**Comment by amrbrkt** [comment]
Thanks @mahmoudElfeel67 for your report, we are taking care of this now and will let you know when it fixed.
