### ISSUE TITLE
f.java java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by huhx0015** [Instabug/Instabug-Android#402]
After updating the Instabug-Android SDK to **10.9.0**, we've been seeing a rather significant number of `ArrayIndexOutOfBoundsException` crashes originating from `com.instabug.library.tracking` from our Crashlytics reports.

The following are logs of the crashes that we've observed:

```
**com.instabug.library.tracking.f.f**

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=100 srcPos=1 dst.length=100 dstPos=0 length=100
       at java.lang.System.arraycopy(System.java)
       at java.util.ArrayList.remove(ArrayList.java:510)
       at com.instabug.library.tracking.f.f(f.java:2)
       at com.instabug.library.tracking.f$b.run(f.java:18)
       at com.instabug.library.util.threading.PoolProvider$b.run(PoolProvider.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.instabug.library.util.threading.b$a.run(b.java:8)
       at java.lang.Thread.run(Thread.java:923)
```

```
**com.instabug.library.tracking.f$b.run**

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=100; index=100
       at java.util.ArrayList.add(ArrayList.java:468)
       at com.instabug.library.tracking.f$b.run(f.java:19)
       at com.instabug.library.util.threading.PoolProvider$b.run(PoolProvider.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.instabug.library.util.threading.b$a.run(b.java:8)
       at java.lang.Thread.run(Thread.java:919)
```

### Steps to Reproduce the Problem
* We are unable to determine how to reproduce this crash.

### SDK Version
* Instabug-Android 10.9.0: https://github.com/Instabug/Instabug-Android/releases/tag/10.9.0

### Android Version
* Android 8.0.0
* Android 9
* Android 10
* Android 11
* Android 12

### Device Model
* OnePlus 6T
* Galaxy S20+ 5G
* Pixel 2 XL
* Pixel 3
* Galaxy S10
* Pixel 4
* OnePlus 7 Pro
* Honor 7X
* Pixel 4a
* moto e
* Pixel 4 XL
* Galaxy J6
* Galaxy S9
* Galaxy Note20 Ultra 5G
* Galaxy J5
* Galaxy A71 5G
* Galaxy S9+
* Galaxy S8
* HD1903
* P20 lite

**Comment by amrbrkt** [comment]
Thanks @huhx0015 for your report, and we are sorry for the inconvenience. 
We worked on a fix for this issue and will be included in our next release which is coming within the next 2 weeks. However you can use the following snapshot immediately 
* Snapshot version: 10.9.0.3433-SNAPSHOT

Add these to your **app-level** `build.gradle` file to grab snapshot:

```gradle 
dependencies {
  implementation 'com.instabug.library:instabug:10.9.0.3433-SNAPSHOT'
}
```
```gradle 
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

I'm closing this issue now, but please, don't hesitate to reopen it if you have any further enquiries.

**Comment by huhx0015** [comment]
Thanks @amrbrkt, much appreciated! 👍
