### ISSUE TITLE
ava.net.UnknownHostException: Unable to resolve host "api.instabug.com": No address associated with hostname

### ISSUE THREAD

**Issue by mahmoudElfeel67** [Instabug/Instabug-Android#405]
### Steps to Reproduce the Problem
Dont know

### Expected Behavior
not to crash
### Actual Behavior
crashes
### Instabug integration code
    Instabug.Builder(application, application.getString(R.string.instabug_app_token))
        .setInvocationEvents(InstabugInvocationEvent.SHAKE)
        .setReproStepsState(State.ENABLED)
        .build()
    //CrashReporting.setState(Feature.State.DISABLED)
    Instabug.setLocale(Locale("ar"))
    BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK)
    Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
    Surveys.setState(Feature.State.ENABLED)

### SDK Version
10.9.0
### Android Version
Pie (v9)(Level 28)

### Device Model
a lot of device models
### [Optional] Project That Reproduces the Issue
This crash is reported by the instabug sdk itself ! and its happening from ages not limited to the latest version
its mentioning com.google.firebase:firebase-perf@@19.0.5 :1  is there a correlation between the 2 ?

`data:text/text;charset=utf-8,
io.reactivex.exceptions.UndeliverableException: java.net.UnknownHostException: Unable to resolve host "api.instabug.com": No address associated with hostname
	 at j.b.c0.a.r(RxJavaPlugins.java:4)
	 at j.b.a0.e.a.f$a.onError(CompletableMergeIterable.java:4)
	 at j.b.a0.e.a.h$a.onError(CompletableSubscribeOn.java:1)
	 at j.b.a0.e.a.a$a.onError(CompletableConcatArray.java:1)
	 at j.b.a0.e.a.a$a.onError(CompletableConcatArray.java:1)
	 at j.b.a0.e.a.g$a.onError(CompletablePeek.java:7)
	 at j.b.a0.e.d.t$a.onError(ObservableIgnoreElementsCompletable.java:1)
	 at j.b.a0.e.d.a0$a.onError(ObservableRetryPredicate.java:5)
	 at j.b.a0.e.d.d$a.a(ObservableCreate.java:3)
	 at j.b.a0.e.d.d$a.onError(ObservableCreate.java:1)
	 at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:28)
	 at j.b.a0.e.d.d.e0(ObservableCreate.java:3)
	 at j.b.n.a(Observable.java:4)
	 at j.b.a0.e.d.a0$a.a(ObservableRetryPredicate.java:3)
	 at j.b.a0.e.d.a0.e0(ObservableRetryPredicate.java:4)
	 at j.b.n.a(Observable.java:4)
	 at j.b.a0.e.d.t.m(ObservableIgnoreElementsCompletable.java:1)
	 at j.b.b.b(Completable.java:3)
	 at j.b.a0.e.a.g.m(CompletablePeek.java:1)
	 at j.b.b.b(Completable.java:3)
	 at j.b.a0.e.a.a$a.a(CompletableConcatArray.java:8)
	 at j.b.a0.e.a.a.m(CompletableConcatArray.java:3)
	 at j.b.b.b(Completable.java:3)
	 at j.b.a0.e.a.a$a.a(CompletableConcatArray.java:8)
	 at j.b.a0.e.a.a.m(CompletableConcatArray.java:3)
	 at j.b.b.b(Completable.java:3)
	 at j.b.a0.e.a.h$a.run(CompletableSubscribeOn.java:1)
	 at j.b.s$a.run(Scheduler.java:2)
	 at j.b.a0.g.m.run(ScheduledRunnable.java:2)
	 at j.b.a0.g.m.call(ScheduledRunnable.java:1)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	 at java.lang.Thread.run(Thread.java:764)

Caused by:
java.net.UnknownHostException: Unable to resolve host "api.instabug.com": No address associated with hostname
	 at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:126)
	 at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
	 at java.net.InetAddress.getAllByName(InetAddress.java:1154)
	 at com.android.okhttp.Dns$1.lookup(Dns.java:39)
	 at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:196)
	 at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
	 at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:89)
	 at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:190)
	 at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142)
	 at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
	 at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
	 at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:325)
	 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:488)
	 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
	 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26)
	 at com.google.firebase.perf.network.d.C(com.google.firebase:firebase-perf@@19.0.5:1)
	 at com.google.firebase.perf.network.e.getOutputStream(com.google.firebase:firebase-perf@@19.0.5:1)
	 at com.instabug.library.network.NetworkManager.connectWithNormalType(NetworkManager.java:8)
	 at com.instabug.library.network.NetworkManager.access$100(NetworkManager.java:1)
	 at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:9)
	 at j.b.a0.e.d.d.e0(ObservableCreate.java:3)
	 at j.b.n.a(Observable.java:4)
	 at j.b.a0.e.d.a0$a.a(ObservableRetryPredicate.java:3)
	 at j.b.a0.e.d.a0.e0(ObservableRetryPredicate.java:4)
	 at j.b.n.a(Observable.java:4)
	 at j.b.a0.e.d.t.m(ObservableIgnoreElementsCompletable.java:1)
	 at j.b.b.b(Completable.java:3)
	 at j.b.a0.e.a.g.m(CompletablePeek.java:1)
	 at j.b.b.b(Completable.java:3)
	 at j.b.a0.e.a.a$a.a(CompletableConcatArray.java:8)
	 at j.b.a0.e.a.a.m(CompletableConcatArray.java:3)
	 at j.b.b.b(Completable.java:3)
	 at j.b.a0.e.a.a$a.a(CompletableConcatArray.java:8)
	 at j.b.a0.e.a.a.m(CompletableConcatArray.java:3)
	 at j.b.b.b(Completable.java:3)
	 at j.b.a0.e.a.h$a.run(CompletableSubscribeOn.java:1)
	 at j.b.s$a.run(Scheduler.java:2)
	 at j.b.a0.g.m.run(ScheduledRunnable.java:2)
	 at j.b.a0.g.m.call(ScheduledRunnable.java:1)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	 at java.lang.Thread.run(Thread.java:764)

`

**Comment by mahmoudElfeel67** [comment]
@amrbrkt  it happens in many countries according to what i saw on the dashboard some of the countries were morocco , Sudan , Yemen and Algeria ,

are you sure this is a real crash and not an error in the sdk ? doesnt seem like a crash in the app itself but the sdk doesnt work or something on api 28 ?? it doesnt appear on firebase crashytics or google play console
and no we dont use an special DNS or proxies 

i also noticed in the network logs all of our server requests has "No Response" in instabug dashboard but none of our users ever complained about app not working or it doesnt load on api 28
