### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by aliigamal** [Instabug/Instabug-Android#415]
### Steps to Reproduce the Problem

the issue happened in production in large scope users

**Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String com.instabug.library.visualusersteps.c.a()' on a null object reference**

### SDK Version 
10.12.1

### Android Version  
8,9,10,11

### Device Model
Samsung,Xiaomi,Realm,Oppo

**Comment by khalid-3lnagar** [comment]
@aliigamal  can you please share the full stack-trace 
thanks

**Comment by aliigamal** [comment]
@khalid-3lnagar Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.instabug.library.visualusersteps.c.a()' on a null object reference
       at com.instabug.library.visualusersteps.h.a(h.java:58)
       at com.instabug.library.visualusersteps.h.a(h.java:26)
       at com.instabug.library.visualusersteps.h.a(h.java:11)
       at com.instabug.library.visualusersteps.h.a(h.java:34)
       at com.instabug.library.util.c.onGlobalFocusChanged(c.java:26)
       at android.view.ViewTreeObserver.dispatchOnGlobalFocusChange(ViewTreeObserver.java:924)
       at android.view.View.handleFocusGainInternal(View.java:6946)
       at android.view.View.requestFocusNoSearch(View.java:11561)
       at android.view.View.requestFocus(View.java:11535)
       at android.view.View.requestFocus(View.java:11502)
       at android.view.View.requestFocus(View.java:11444)
       at com.a64bit.simswitcher.ui.views.SearchView.addNumber(SearchView.java:7)
       at com.a64bit.simswitcher.keypad.view.KeypadMainView.addNumber(KeypadMainView.java:22)
       at com.a64bit.simswitcher.ui.main.logs.LogsFragment.lambda$initKeypadObservable$10(LogsFragment.java:1)
       at com.a64bit.simswitcher.ui.main.logs.-$$Lambda$LogsFragment$rYOny0_POKjeux6heQnskwMJSvY.onChanged(-.java:4)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:29)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:44)
       at androidx.lifecycle.LiveData.setValue(LiveData.java:14)
       at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java)
       at com.a64bit.simswitcher.keypad.viewmodel.KeyPadViewModel.setKeyPadMessage(KeyPadViewModel.java:6)
       at com.a64bit.simswitcher.ui.main.logs.LogsFragment.keyPadMessage(LogsFragment.java:2)
       at com.a64bit.simswitcher.keypad.view.KeypadMainView.onClickButton(KeypadMainView.java:18)
       at com.a64bit.simswitcher.keypad.view.KeyPadView.handleNumberDialed(KeyPadView.java:2)
       at com.a64bit.simswitcher.keypad.view.KeyPadView.onClick(KeyPadView.java:13)
       at android.view.View.performClick(View.java:6608)
       at android.view.View.performClickInternal(View.java:6585)
       at android.view.View.access$3100(View.java:778)
       at android.view.View$PerformClick.run(View.java:25965)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6852)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by khalid-3lnagar** [comment]
@aliigamal  this issue is fixed  and included the fix in our latest build 10.12.3
I will close this issue for now, please feel free to reopen it again if you have any further issues.
Thank You
