### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by aliigamal** [Instabug/Instabug-Android#416]
### Steps to Reproduce the Problem

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'long com.instabug.chat.model.d.i()' on a null object reference

### SDK Version
10.12.1

**Comment by khalid-3lnagar** [comment]
can you please share the full stack-trace 🙏🏻

**Comment by aliigamal** [comment]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.instabug.chat.model.d.i()' on a null object reference
       at com.instabug.chat.model.d$a.a(d.java:44)
       at com.instabug.chat.model.d$a.compare(d.java:4)
       at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
       at java.util.TimSort.sort(TimSort.java:220)
       at java.util.Arrays.sort(Arrays.java:1498)
       at java.util.ArrayList.sort(ArrayList.java:1470)
       at java.util.Collections.sort(Collections.java:201)
       at com.instabug.chat.model.b.b(b.java:18)
       at com.instabug.chat.model.b.c(b.java)
       at com.instabug.chat.ui.chats.a.a(a.java:324)
       at com.instabug.chat.ui.chats.a.getView(a.java:40)
       at android.widget.AbsListView.obtainView(AbsListView.java:2413)
       at android.widget.ListView.makeAndAddView(ListView.java:2074)
       at android.widget.ListView.fillSpecific(ListView.java:1497)
       at android.widget.ListView.layoutChildren(ListView.java:1805)
       at android.widget.AbsListView.onLayout(AbsListView.java:2212)
       at android.view.View.layout(View.java:21119)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:21119)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1828)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:21119)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:21119)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
       at android.view.View.layout(View.java:21119)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:21119)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1828)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:21119)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:21119)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1828)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:21119)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:883)
       at android.view.View.layout(View.java:21119)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3514)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2928)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1928)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8374)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1077)
       at android.view.Choreographer.doCallbacks(Choreographer.java:889)
       at android.view.Choreographer.doFrame(Choreographer.java:821)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1063)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)``

**Comment by khalid-3lnagar** [comment]
@aliigamal  Thanks for reporting this, We're looking into it.

**Comment by khalid-3lnagar** [comment]
@aliigamal We are sorry for the inconvenience, our QC team are testing the fix and once they finish I'll inform you

**Comment by khalid-3lnagar** [comment]
Hi @aliigamal,
We included the fix in our latest build 10.13.0,
 please give it a try and feel free to re-open this ticket if the issue still exists.

Thank you 🙏🏻
