### ISSUE TITLE
Crash in CacheManager.subscribe

### ISSUE THREAD

**Issue by mahmoudElfeel67** [Instabug/Instabug-Android#420]
### Steps to Reproduce the Problem
I dont know
### Expected Behavior
not to crash
### Actual Behavior
crashes with stacktraces : 
`Fatal Exception: java.lang.IllegalArgumentException: No cache exists with this ID to subscribe to
       at com.instabug.library.internal.storage.cache.CacheManager.subscribe(CacheManager.java:7)
       at com.instabug.chat.ui.f.e.h(ChatPresenter.java:3)
       at com.instabug.chat.ui.f.d.onStart(ChatFragment.java:3)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3021)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
       at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at com.instabug.library.core.ui.BaseFragmentActivity.onStart(BaseFragmentActivity.java:2)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
       at android.app.Activity.performStart(Activity.java:7923)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3335)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7590)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`
### Instabug integration code
*Make sure to remove your app token.*
Instabug.Builder(application, application.getString(R.string.instabug_app_token))
            .setInvocationEvents(InstabugInvocationEvent.SHAKE)
            .setReproStepsState(State.ENABLED)
            .build()
        Instabug.setLocale(Locale("ar"))
        BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK)
        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
        Surveys.setState(Feature.State.ENABLED)
### SDK Version
10.10.0.3530-SNAPSHOT
### Android Version
android 10
### Device Model
Redmi Note 7

**Comment by kareem-waleed** [comment]
@mahmoudElfeel67 Thanks for reporting this, would you please send the issue details to contactus@instabug.com and we will be helping you out ASAP. 🙏

**Comment by Bashayer-reda** [comment]
Hello @mahmoudElfeel67 I hope you have a lovely day. We will close this one, but if you still have any issues, please don't hesitate to reopen it anytime. Thank you.
