### ISSUE TITLE
java.lang.IllegalArgumentException: STATE_SETTLING should not be set externally.

### ISSUE THREAD

**Issue by JurajKuliska** [Instabug/Instabug-Android#433]
### Steps to Reproduce the Problem
I couldn't reproduce the issue myself but found an Instabug report. It was most probably triggered by Shake for feedback as it was on a random screen in our app

### Expected Behavior
The app doesn't crash

### Actual Behavior
The app crashes with the following exception:
```
java.lang.IllegalArgumentException: STATE_SETTLING should not be set externally.
	 at com.google.android.material.bottomsheet.BottomSheetBehavior.setState(BottomSheetBehavior.java:109)
	 at com.instabug.bug.view.reporting.b.N(b.java:165)
	 at com.instabug.bug.view.reporting.b.initViews(b.java:142)
	 at com.instabug.library.core.ui.InstabugBaseFragment.onCreateView(InstabugBaseFragment.java:11)
	 at androidx.fragment.app.Fragment.performCreateView(Fragment.java:19)
	 at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:189)
	 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:115)
	 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:198)
	 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:81)
	 at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:21)
	 at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:3)
	 at android.os.Handler.handleCallback(Handler.java:938)
	 at android.os.Handler.dispatchMessage(Handler.java:99)
	 at android.os.Looper.loopOnce(Looper.java:226)
	 at android.os.Looper.loop(Looper.java:313)
	 at android.app.ActivityThread.main(ActivityThread.java:8669)
	 at java.lang.reflect.Method.invoke(Method.java)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### SDK Version
Android SDK 11.3.0.1

### Android Version
Android12 (v12)(Level 31)

### Device Model
Samsung SM-N981B

**Comment by mhashim6** [comment]
Hi @JurajKuliska 

Thank you for reporting this, a fix has already been implemented and should come out shortly in the coming release.
I'll close this issue for now, but please do open it if you have any further questions.
