### ISSUE TITLE
Multiple crashes occurring when launching application using Instabug "APM"

### ISSUE THREAD

**Issue by Orbyt** [Instabug/Instabug-Android#454]
### Steps to Reproduce the Problem
Integrate App Performance Monitoring via the integration guide (https://docs.instabug.com/docs/android-apm) and then launch application.

The application in question uses GraphQL and thus adds interceptors to a OkHTTP client. Perhaps that is related to the issue. Here is how the OkHTTP client is built:

```kotlin
 return OkHttpClient.Builder().apply {

            addInterceptor { chain ->
                val newRequest = chain.request().newBuilder()
                    .addHeader(Constants.userAgentHeaderKey, Constants.userAgentHeaderBaseValue)
                    .addHeader(Constants.APOLLO_CLIENT_NAME_KEY, "Android")
                    .addHeader(Constants.APOLLO_CLIENT_VERSION_KEY, BuildConfig.VERSION_CODE.toString())
                    .build()
                chain.proceed(newRequest)
            }

            val accessToken = appLevelData.getUserAccessToken()
            if (accessToken.isNotEmpty()) {
                val value = "Bearer $accessToken"
                addInterceptor { chain ->
                    val newRequest = chain.request().newBuilder()
                        .addHeader(Constants.authorizationHeaderKey, value)
                        .build()
                    chain.proceed(newRequest)
                }
            }

            if (Constants.notRelease) {
                val interceptor = HttpLoggingInterceptor()
                interceptor.level = HttpLoggingInterceptor.Level.BODY
                addInterceptor(interceptor)
            }
            readTimeout(30, TimeUnit.SECONDS)
            connectTimeout(30, TimeUnit.SECONDS)
            callTimeout(30, TimeUnit.SECONDS)
        }.build()
```

### Expected Behavior
Application works normally.

### Actual Behavior
Application crashes with many exceptions. Here is a part of the trace:
```
CrashReporting InstabugUncaughtExceptionHandler Caught an Unhandled Exception: java.lang.IllegalStateException
                 java.lang.IllegalStateException: closed
                 	at okio.RealBufferedSource.read(RealBufferedSource.kt:185)
                 	at com.apollographql.apollo.cache.http.ResponseBodyProxy$ProxySource.read(ResponseBodyProxy.java:75)
                 	at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
                 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:247)
                 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                 	at com.example.example.di.modules.NetworkModule$provideOkHttpClient$lambda-2$$inlined$-addInterceptor$2.intercept(OkHttpClient.kt:1083)
                 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                 	at com.example.example.di.modules.NetworkModule$provideOkHttpClient$lambda-2$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1085)
                 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                 	at java.lang.Thread.run(Thread.java:920)

E  InstabugUncaughtExceptionHandler Caught an Unhandled Exception: java.lang.IllegalStateException
                 java.lang.IllegalStateException: closed
                 	at okio.RealBufferedSource.read(RealBufferedSource.kt:185)
                 	at com.apollographql.apollo.cache.http.ResponseBodyProxy$ProxySource.read(ResponseBodyProxy.java:75)
                 	at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
                 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:247)
                 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                 	at com.example.grandrounds.di.modules.NetworkModule$provideOkHttpClient$lambda-2$$inlined$-addInterceptor$2.intercept(OkHttpClient.kt:1083)
                 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                 	at com.example.example.di.modules.NetworkModule$provideOkHttpClient$lambda-2$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1085)
                 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                 	at java.lang.Thread.run(Thread.java:920)
```

### SDK Version
11.10.0

### Android Version
API 31

### Device Model
Pixel 4

**Comment by yaraabdelhakiim** [comment]
@Orbyt Thank you for reporting this.
We'll look into it from out side and update you ASAP.

**Comment by AbanoubEdwar13** [comment]
@Orbyt 
I believe this is an issue with GraphQL itself
https://github.com/apollographql/apollo-kotlin/issues/2968
It would also happen if you added two HttpLogginInterceptors, without any Instabug dependencies 
we recommend upgrading GraphQL to `3.7.3` as we were able to reproduce the issue from our side, and when we migrated to that version, the issue was resolved
if migration is not an option for you, you have the following options
1- you could remove HttpLoggingInterceptor
2- Disable caching from Apollo 
Please try it, and update us if the issue was still happening

**Comment by Bashayer-reda** [comment]
Hello @Orbyt Thank you so much for reaching out. Please confirm that you have reviewed our comment above. I will go ahead and close the issue. However, if you encounter any further issues, please feel free to reopen it at any time
