### ISSUE TITLE
Crash when trying to record a video twice in one session on API 34

### ISSUE THREAD

**Issue by long-sh** [Instabug/Instabug-Android#462]
### Steps to Reproduce the Problem
1. start reporting a bug
2. record and save a video
3. start recording another video in the same bug or a new bug

### Expected Behavior
Can start recording

### Actual Behavior
Crash with:
```
ScreenRecordingService          E  Error while starting screen recorder
                                                java.lang.SecurityException: Don't re-use the resultData to retrieve the same projection instance, and don't use a token that has timed out. Don't take multiple captures by invoking MediaProjection#createVirtualDisplay multiple times on the same instance.
                                                    at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                                    at android.os.Parcel.createException(Parcel.java:3041)
                                                    at android.os.Parcel.readException(Parcel.java:3024)
                                                    at android.os.Parcel.readException(Parcel.java:2966)
                                                    at android.hardware.display.IDisplayManager$Stub$Proxy.createVirtualDisplay(IDisplayManager.java:1425)
                                                    at android.hardware.display.DisplayManagerGlobal.createVirtualDisplay(DisplayManagerGlobal.java:643)
                                                    at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:1134)
                                                    at android.media.projection.MediaProjection.createVirtualDisplay(MediaProjection.java:247)
                                                    at android.media.projection.MediaProjection.createVirtualDisplay(MediaProjection.java:216)
                                                    at com.instabug.library.internal.video.customencoding.q.d(SourceFile:26)
                                                    at com.instabug.library.internal.video.customencoding.q.a(SourceFile:1)
                                                    at com.instabug.library.internal.video.customencoding.r.handleMessage(SourceFile:4)
                                                    at android.os.Handler.dispatchMessage(Handler.java:106)
                                                    at android.os.Looper.loopOnce(Looper.java:205)
                                                    at android.os.Looper.loop(Looper.java:294)
                                                    at android.os.HandlerThread.run(HandlerThread.java:67)
                                                Caused by: android.os.RemoteException: Remote stack trace:
                                                    at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.isValid(MediaProjectionManagerService.java:1094)
                                                    at com.android.server.display.DisplayManagerService.createVirtualDisplayInternal(DisplayManagerService.java:1447)
                                                    at com.android.server.display.DisplayManagerService.-$$Nest$mcreateVirtualDisplayInternal(DisplayManagerService.java:0)
                                                    at com.android.server.display.DisplayManagerService$BinderService.createVirtualDisplay(DisplayManagerService.java:3706)
                                                    at android.hardware.display.IDisplayManager$Stub.onTransact(IDisplayManager.java:730)
```

### SDK Version
12.2.0

### Android Version
API 34

### Device Model
Any

### Additional Notes
Can only record another video after swiping the app away

Prior to this crash, there was a crash when trying to record a video at all on API 34. 
```
Caused by: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{bc2365d 16644:com.stationhead.app/u0a412} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION]
```
Which was fixed by adding the permission but then this crash occurs on additional recordings

**Comment by MohamedHefny** [comment]
@long-sh Thanks for reporting this issue. It has been fixed in version `12.5.1`. Please update the SDK version and check again.
I'll close this issue for now and please feel free to open it again if you still facing issues in this part 🙏🏻
