### ISSUE TITLE
Add support for 16kb page sizes in Android 15

### ISSUE THREAD

**Issue by mirixh** [Instabug/Instabug-Android#485]
### Steps to Reproduce the Problem

Install app on Android 15 image with 16kb pages enabled ( I used the emulator as suggested in the guide) 

https://developer.android.com/about/versions/15/behavior-changes-all#16-kb

### Expected Behavior

App runs smoothly and instabug can be used

### Actual Behavior

app crashes after some time with errors like the following

```
2024-07-16 08:31:16.353  2849-3299  IBG-Core                taxi.android.client.debug            E  Error loading native method
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.instabug.library.networkv2.service.synclogs.SyncLogKeyProvider.getNativeMatchingUuidSuffix() (tried Java_com_instabug_library_networkv2_service_synclogs_SyncLogKeyProvider_getNativeMatchingUuidSuffix and Java_com_instabug_library_networkv2_service_synclogs_SyncLogKeyProvider_getNativeMatchingUuidSuffix__) - is the library loaded, e.g. System.loadLibrary?
                                                                                                    	at com.instabug.library.networkv2.service.synclogs.SyncLogKeyProvider.getNativeMatchingUuidSuffix(Native Method)
                                                                                                    	at com.instabug.library.networkv2.service.synclogs.SyncLogKeyProvider.g(SourceFile:1)
                                                                                                    	at com.instabug.library.networkv2.service.synclogs.b.c(SourceFile:2)
                                                                                                    	at com.instabug.library.networkv2.service.synclogs.b.d(SourceFile:12)
                                                                                                    	at com.instabug.library.networkv2.service.synclogs.b.c(SourceFile:4)
                                                                                                    	at com.instabug.library.networkv2.service.synclogs.b.a(SourceFile:9)
                                                                                                    	at com.instabug.library.c.I(SourceFile:7)
                                                                                                    	at com.instabug.library.c.$r8$lambda$Wi_i0Px-rElAUh5_2PJJOYYv0iA(Unknown Source:0)
                                                                                                    	at com.instabug.library.c$$ExternalSyntheticLambda4.run(D8$$SyntheticClass:0)
                                                                                                    	at com.instabug.library.internal.orchestrator.ActionsOrchestrator.runAction(SourceFile:1)
                                                                                                    	at com.instabug.library.internal.orchestrator.ActionsOrchestrator.access$100(SourceFile:1)
                                                                                                    	at com.instabug.library.internal.orchestrator.ActionsOrchestrator$a.run(SourceFile:2)
                                                                                                    	at com.instabug.library.util.threading.PoolProvider$e.run(SourceFile:5)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at com.instabug.library.util.threading.PriorityThreadFactory.lambda$newThread$0$com-instabug-library-util-threading-PriorityThreadFactory(SourceFile:2)
                                                                                                    	at com.instabug.library.util.threading.PriorityThreadFactory$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	at com.instabug.library.util.threading.c$c.run(SourceFile:2)
2024-07-16 08:31:17.015  2849-3360  id.client.debug         taxi.android.client.debug            E  No implementation found for java.lang.String com.instabug.library.networkv2.authorization.NetworkOfficer.getClientId() (tried Java_com_instabug_library_networkv2_authorization_NetworkOfficer_getClientId and Java_com_instabug_library_networkv2_authorization_NetworkOfficer_getClientId__) - is the library loaded, e.g. System.loadLibrary?
2024-07-16 08:31:17.283  2849-3360  IBG-Core                taxi.android.client.debug            E  Network request got error
2024-07-16 08:31:17.291  2849-3360  IBG-Core                taxi.android.client.debug            E  Error getting Network request response: {"error": "Unauthorized"}
2024-07-16 08:31:17.428  2849-3360  IBG-Core                taxi.android.client.debug            E  Syncing Sessions filed due to: {"error": "Unauthorized"}
2024-07-16 08:31:17.782  2849-3360  id.client.debug         taxi.android.client.debug            E  No implementation found for java.lang.String com.instabug.library.networkv2.authorization.NetworkOfficer.getClientId() (tried Java_com_instabug_library_networkv2_authorization_NetworkOfficer_getClientId and Java_com_instabug_library_networkv2_authorization_NetworkOfficer_getClientId__) - is the library loaded, e.g. System.loadLibrary?
2024-07-16 08:31:18.552  2849-3360  IBG-Core                taxi.android.client.debug            E  Network request got error
2024-07-16 08:31:18.553  2849-3360  IBG-Core                taxi.android.client.debug            E  Error getting Network request response: {"error": "Unauthorized"}
2024-07-16 08:31:18.553  2849-3360  IBG-Core                taxi.android.client.debug            E  something went wrong while syncing sessions
                                                                                                    RequestException(requestCode = 401, message= {"error": "Unauthorized"}
                                                                                                    ) 
                                                                                                    	at com.instabug.library.networkv2.connection.InstabugBaseConnectionManagerImpl.handleServerError(SourceFile:11)
                                                                                                    	at com.instabug.library.networkv2.NetworkManager.performRequest(SourceFile:43)
                                                                                                    	at com.instabug.library.networkv2.NetworkManager.handleRequest(SourceFile:6)
                                                                                                    	at com.instabug.library.networkv2.NetworkManager.doRequestOnSameThread(SourceFile:1)
                                                                                                    	at com.instabug.library.networkv2.NetworkManager.doRequestOnSameThread(SourceFile:29)
                                                                                                    	at com.instabug.library.networkv2.NetworkManager.doRequestOnSameThread(SourceFile:2)
                                                                                                    	at com.instabug.library.sessionV3.sync.f.a(SourceFile:9)
                                                                                                    	at com.instabug.library.sessionV3.sync.f.a(SourceFile:6)
                                                                                                    	at com.instabug.library.sessionV3.sync.f.f(SourceFile:4)
                                                                                                    	at com.instabug.library.sessionV3.sync.f.e(SourceFile:8)
                                                                                                    	at com.instabug.library.sessionV3.sync.f.$r8$lambda$EwoPp4gmTrLiw_McLc_395TNlMQ(Unknown Source:0)
                                                                                                    	at com.instabug.library.sessionV3.sync.f$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at com.instabug.library.InstabugNetworkJob.executeRunnable(SourceFile:3)
                                                                                                    	at com.instabug.library.InstabugNetworkJob.enqueueJob$lambda-0(SourceFile:1)
                                                                                                    	at com.instabug.library.InstabugNetworkJob.$r8$lambda$ZGHaaS3vBNkBc8d_whCX96hwgj4(Unknown Source:0)
                                                                                                    	at com.instabug.library.InstabugNetworkJob$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at com.instabug.library.util.threading.DefensiveRunnableKt$a.run(SourceFile:1)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at com.instabug.library.util.threading.PriorityThreadFactory.lambda$newThread$0$com-instabug-library-util-threading-PriorityThreadFactory(SourceFile:2)
                                                                                                    	at com.instabug.library.util.threading.PriorityThreadFactory$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	at com.instabug.library.util.threading.c$c.run(SourceFile:2)
2024-07-16 08:31:19.903  2849-3360  id.client.debug         taxi.android.client.debug            E  No implementation found for java.lang.String com.instabug.library.networkv2.authorization.NetworkOfficer.getClientId() (tried Java_com_instabug_library_networkv2_authorization_NetworkOfficer_getClientId and Java_com_instabug_library_networkv2_authorization_NetworkOfficer_getClientId__) - is the library loaded, e.g. System.loadLibrary?
2024-07-16 08:31:20.239  2849-3360  IBG-Core                taxi.android.client.debug            E  Network request got error
2024-07-16 08:31:20.239  2849-3360  IBG-Core                taxi.android.client.debug            E  Error getting Network request response: {"error": "Unauthorized"}
2024-07-16 08:31:20.240  2849-3360  IBG-Core                taxi.android.client.debug            E  something went wrong while syncing sessions
                                                                                                    RequestException(requestCode = 401, message= {"error": "Unauthorized"}
                                                                                                    ) 
                                                                                                    	at com.instabug.library.networkv2.connection.InstabugBaseConnectionManagerImpl.handleServerError(SourceFile:11)
                                                                                                    	at com.instabug.library.networkv2.NetworkManager.performRequest(SourceFile:43)
                                                                                                    	at com.instabug.library.networkv2.NetworkManager.handleRequest(SourceFile:6)
                                                                                                    	at com.instabug.library.networkv2.NetworkManager.doRequestOnSameThread(SourceFile:1)
                                                                                                    	at com.instabug.library.networkv2.NetworkManager.doRequestOnSameThread(SourceFile:29)
                                                                                                    	at com.instabug.library.networkv2.NetworkManager.doRequestOnSameThread(SourceFile:2)
                                                                                                    	at com.instabug.library.sessionV3.sync.f.a(SourceFile:9)
                                                                                                    	at com.instabug.library.sessionV3.sync.f.a(SourceFile:6)
                                                                                                    	at com.instabug.library.sessionV3.sync.f.f(SourceFile:4)
                                                                                                    	at com.instabug.library.sessionV3.sync.f.e(SourceFile:8)
                                                                                                    	at com.instabug.library.sessionV3.sync.f.$r8$lambda$EwoPp4gmTrLiw_McLc_395TNlMQ(Unknown Source:0)
                                                                                                    	at com.instabug.library.sessionV3.sync.f$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at com.instabug.library.InstabugNetworkJob.executeRunnable(SourceFile:3)
                                                                                                    	at com.instabug.library.InstabugNetworkJob.enqueueJob$lambda-0(SourceFile:1)
                                                                                                    	at com.instabug.library.InstabugNetworkJob.$r8$lambda$ZGHaaS3vBNkBc8d_whCX96hwgj4(Unknown Source:0)
                                                                                                    	at com.instabug.library.InstabugNetworkJob$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at com.instabug.library.util.threading.DefensiveRunnableKt$a.run(SourceFile:1)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at com.instabug.library.util.threading.PriorityThreadFactory.lambda$newThread$0$com-instabug-library-util-threading-PriorityThreadFactory(SourceFile:2)
                                                                                                    	at com.instabug.library.util.threading.PriorityThreadFactory$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	at com.instabug.library.util.threading.c$c.run(SourceFile:2)
```

### SDK Version

13.2.0

### Android Version
15 Beta
### Device Model
Pixel 8

**Comment by IslamMohamady** [comment]
Hi @mirixh 
Thanks for reporting. We are aware of this change and we are working on accommodating it in our SDK.
