### ISSUE TITLE
com.instabug.library.util.LocaleUtils.getLocaleStringResource  NullPointerException

### ISSUE THREAD

**Issue by armen301** [Instabug/Instabug-Android#92]
`java.lang.NullPointerException
	at android.content.Context.getText(Context.java:348)
	at com.instabug.library.util.LocaleUtils.getLocaleStringResource(LocaleUtils.java:58)
	at com.instabug.bug.a.h(BugPluginWrapper.java:219)
	at com.instabug.bug.a.d(BugPluginWrapper.java:74)
	at com.instabug.bug.a.c(BugPluginWrapper.java:64)
	at com.instabug.bug.BugPlugin.getPromptOptions(BugPlugin.java:35)
	at com.instabug.library.core.plugin.a.c(PluginsManager.java:83)
	at com.instabug.library.invocation.b.k(InvocationManager.java:262)
	at com.instabug.library.invocation.b.b(InvocationManager.java:227)
	at com.instabug.library.invocation.b.a(InvocationManager.java:200)
	at com.instabug.library.invocation.b.a(InvocationManager.java:180)
	at com.instabug.library.invocation.b.j(InvocationManager.java:167)
	at com.instabug.library.invocation.b.a(InvocationManager.java:308)
	at com.instabug.library.invocation.a.e.c(ShakeInvoker.java:36)
	at com.instabug.library.util.d.onSensorChanged(ShakeDetector.java:52)
	at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:458)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:138)
	at android.os.Looper.loop(Looper.java:123)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
	at dalvik.system.NativeStart.main(Native Method)
`

**Comment by Korazy** [comment]
Hey @armen301 

Thanks for reaching out, this should be fixed in the latest release :)
