### ISSUE TITLE
BugReportingActivity.java line 171

### ISSUE THREAD

**Issue by Viked** [Instabug/Instabug-Android#94]
We have a crash

Steps to reproduce:
Shake device to get ReportBug form
Tap 'x' or device '<' button when form is opened
Observe result

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dartfleet.mobile/com.instabug.bug.view.BugReportingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.bug.model.Bug com.instabug.bug.model.Bug.a(com.instabug.bug.model.b)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.instabug.bug.model.Bug com.instabug.bug.model.Bug.a(com.instabug.bug.model.b)' on a null object reference
       at com.instabug.bug.view.BugReportingActivity.a(BugReportingActivity.java:171)
       at com.instabug.bug.view.f.a(BugReportingPresenter.java:34)
       at com.instabug.bug.view.BugReportingActivity.onCreate(BugReportingActivity.java:78)
       at android.app.Activity.performCreate(Activity.java:7174)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Samsung S8, Android 8.0.
Instabug sdk 4.13.1

**Comment by Korazy** [comment]
Hey @Viked 

Thanks for pointing this out, we're looking into a resolution for this.

**Comment by Korazy** [comment]
@Viked Can you please send the code you use to integrate instabug? Also, does this issue consistently occur across multiple devices or only this one?

**Comment by Viked** [comment]
@Korazy I am using this initialization: 
 new Instabug.Builder(context, BuildConfig.instabug)
.setInvocationEvent(InstabugInvocationEvent.SHAKE)
.setSurveysState(Feature.State.ENABLED)
.setPushNotificationState(Feature.State.DISABLED)
.setCrashReportingState(Feature.State.DISABLED)
.setConsoleLogState(Feature.State.DISABLED)
                .build()

Instabug.setPromptOptionsEnabled(false, true, false);
            Instabug.addTags(context.getString(R.string.app_name));
            Instabug.setIntroMessageEnabled(false);
            if (!Instabug.isEnabled()) {
                Instabug.enable();
            }

We checked on samsung SM-G955F and Nexus 6P

**Comment by Korazy** [comment]
Hey @Viked 

So sorry for the delay. Can you please try upgrading to the latest version now and let me know if it works?

**Comment by Korazy** [comment]
@Viked please feel free to reopen this issue if you run into it again :)
