### ISSUE TITLE
StrictMode Reports Resource Leak

### ISSUE THREAD

**Issue by JoshR604** [Instabug/Instabug-Android#95]
I was experiencing some UI lag in my app when switching activities.

I enabled strict mode to find out what was going on and the stack trace showed the that a resource is never being released and is occurring from a call in the NetworkManager.class.

Once I remove the Instabug builder/initialization this error does not appear in Strict mode as well as there is no longer any UI lag.

E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:184)
        at java.util.zip.Inflater.<init>(Inflater.java:82)
        at com.android.okio.GzipSource.<init>(GzipSource.java:57)
        at com.android.okhttp.internal.http.HttpEngine.initContentStream(HttpEngine.java:490)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:680)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
        at com.instabug.library.network.NetworkManager$1.a(NetworkManager.java:98)
        at com.instabug.library.network.NetworkManager$1.call(NetworkManager.java:73)
        at rx.Observable.unsafeSubscribe(Observable.java:10150)
        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by Korazy** [comment]
Hey @JoshR604 

Thanks for pointing that out. Can you please tell me the SDK version you're currently on?

**Comment by JoshR604** [comment]
Hello @Korazy 

I am on version 4.13.1

**Comment by Korazy** [comment]
@JoshR604 this issue should be solved within the next few weeks when the migration to Rxjava 2 is complete. Regarding the UI lag however, you should be able to reduce it by disabling the visual user steps which you do by adding .setReproStepsState(State.DISABLED) to the Instabug builder method.

**Comment by Korazy** [comment]
RxJava 2 is now released, please feel free to open this issue again if it's not fixed for you :)
